# -*- coding: utf-8 -*-
"""Untitled89.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlqqZpQUbSA4z2nKShoaAy0Rnf0FObDF
"""

"""
NSD PIPELINE v9.1 — MULTI-MODEL VISUAL RESIDUALIZATION + VOXELWISE PREDICTION
===============================================================================
Full run: subj01–07. Two L2 visual variants × three L3 models = 6 wiped arrays.

L2 variant A — broad ensemble:
  Gabor | VGG19-avgpool(512) | ResNet50(2048) | CLIP-vis(512) | EffNet-B0(1280)

L2 variant B — VGG multi-layer:
  Gabor | VGG-relu3_4→GAP(256) | VGG-relu4_4→GAP(512) | VGG-relu5_4→GAP(512)

L3 models (3): BERT(768), GPT-2(768), CLIP-text(512)
  Each wiped against Xa AND Xb → 6 keys: bert_Xa/Xb, gpt2_Xa/Xb, clip_Xa/Xb

Wipe: single 80/20 split. RidgeCV alpha on train 80%. Residual on test 20% only.
Voxelwise: KFold-5 Ridge on test-set trials → 6 R² maps per hemi per subject.
Stats: sign-flip (exact 2^N, primary) + t-test (secondary). FDR per wipe-key.
"""

# ════════════════════════════════════════════════════════════════════════════
# CHUNK 1 — SETUP / PACKAGES / CONFIG / COCO
# ════════════════════════════════════════════════════════════════════════════
import subprocess, sys, os, time, io, re, json, pickle, warnings

for pkg in ['nilearn', 'transformers', 'requests', 'timm']:
    subprocess.run([sys.executable, '-m', 'pip', 'install', pkg, '-q'], check=False)

import numpy as np
import pandas as pd
import zipfile, torch, cv2, requests
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
from PIL import Image
from torchvision import models, transforms
from transformers import BertTokenizer, BertModel
from scipy import stats
from sklearn.linear_model import Ridge, RidgeCV
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from joblib import Parallel, delayed
import statsmodels.stats.multitest as smm

warnings.filterwarnings('ignore')
t0 = time.time()
def elapsed(): return f"[{time.time()-t0:5.0f}s]"

# ═══════════════ EDIT CONFIG BELOW ═══════════════
SUBJ_ZIPS = [
    '/content/drive/MyDrive/nsd/subj01.zip',
    '/content/drive/MyDrive/nsd/subj02.zip',
    '/content/drive/MyDrive/nsd/subj03.zip',
    '/content/drive/MyDrive/nsd/subj04.zip',
    '/content/drive/MyDrive/nsd/subj05.zip',
    '/content/drive/MyDrive/nsd/subj06.zip',
    '/content/drive/MyDrive/nsd/subj07.zip',
    '/content/drive/MyDrive/nsd/subj08.zip'
]
STIM_PATH = '/content/drive/MyDrive/nsd_stim_info_merged.pkl'
OUT_DIR   = '/content/drive/MyDrive/nsd_results_v9.1'
# ══════════════════════════════════════════════════

N_JOBS        = 12
IMG_BATCH     = 128
BERT_BATCH    = 128
CMI_FOLDS     = 5
WIPE_TRAIN_FRAC = 0.80   # single 80/20 split for residualization (replaces 5-fold)
RIDGE_ALPHA   = 1e4
RIDGECV_ALPHAS = np.logspace(1, 6, 12)
RANDOM_STATE  = 42
ALPHA_SIG     = 0.05
VOXEL_BLOCK   = 6000

# L3 model registry (3 models)
L3_MODELS = ['bert', 'gpt2', 'clip']

# L2 visual variants
X_VIS_VARIANTS = ['Xa', 'Xb']   # Xa=broad ensemble, Xb=VGG multi-layer

# All 6 wipe combinations: {l3}_{xvar}
WIPE_KEYS = [f'{m}_{v}' for m in L3_MODELS for v in X_VIS_VARIANTS]
# → ['bert_Xa','bert_Xb','gpt2_Xa','gpt2_Xb','clip_Xa','clip_Xb']

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
SUBJ_ZIPS = [p for p in SUBJ_ZIPS if os.path.exists(p)]
assert len(SUBJ_ZIPS) >= 1, "No subject zips found"
N_SUBJ = len(SUBJ_ZIPS)
print(f"{elapsed()} Device:{DEVICE} | CPUs:{N_JOBS} | Subjects:{N_SUBJ}")

os.makedirs(OUT_DIR, exist_ok=True)
TABLES_DIR = os.path.join(OUT_DIR, 'tables');  os.makedirs(TABLES_DIR, exist_ok=True)
FIGS_DIR   = os.path.join(OUT_DIR, 'figures'); os.makedirs(FIGS_DIR,   exist_ok=True)
ARRAYS_DIR = os.path.join(OUT_DIR, 'arrays');  os.makedirs(ARRAYS_DIR, exist_ok=True)

# ROI definitions (unchanged from v8)
ROI_TYPES  = ['prf-visualrois', 'floc-bodies', 'floc-faces', 'floc-places', 'floc-words', 'streams']
ROI_LABELS = {
    'prf-visualrois': {1:'V1v',2:'V1d',3:'V2v',4:'V2d',5:'V3v',6:'V3d',7:'hV4'},
    'floc-bodies':    {1:'EBA',2:'FBA-1',3:'FBA-2',4:'mTL-bodies'},
    'floc-faces':     {1:'OFA',2:'FFA-1',3:'FFA-2',4:'mTL-faces',5:'aTL-faces'},
    'floc-places':    {1:'OPA',2:'PPA',3:'RSC'},
    'floc-words':     {1:'OWFA',2:'VWFA-1',3:'VWFA-2',4:'mfs-words',5:'mTL-words'},
    'streams':        {1:'early',2:'midventral',3:'midlateral',4:'midparietal',
                       5:'ventral',6:'lateral',7:'parietal'},
}
ROI_COLORS = {
    'prf-visualrois':'#FF6B6B','floc-bodies':'#4ECDC4','floc-faces':'#FFE66D',
    'floc-places':'#A8E6CF','floc-words':'#C3A6FF','streams':'#FF8C42',
}

np.random.seed(RANDOM_STATE); torch.manual_seed(RANDOM_STATE)

# ─── COCO annotations ────────────────────────────────────────────────────────
print(f"\n{elapsed()} COCO annotations...")
COCO_CACHE = '/tmp/nsd_coco_v9.pkl'
if os.path.exists(COCO_CACHE):
    with open(COCO_CACHE, 'rb') as _f: _cc = pickle.load(_f)
    std_tr      = _cc['std_tr'];      std_va      = _cc['std_va']
    caps_list_tr= _cc['caps_list_tr']; caps_list_va= _cc['caps_list_va']
    print("  COCO: loaded from cache")
else:
    ann_url = "http://images.cocodataset.org/annotations/annotations_trainval2017.zip"
    print(f"  Downloading {ann_url} ...")
    resp = requests.get(ann_url, stream=True, timeout=600); resp.raise_for_status()
    print(f"  Downloaded ({len(resp.content)/1e6:.0f} MB) — parsing...")
    with zipfile.ZipFile(io.BytesIO(resp.content)) as za:
        with za.open('annotations/instances_train2017.json') as f: _inst_tr = json.load(f)
        with za.open('annotations/instances_val2017.json')   as f: _inst_va = json.load(f)
        with za.open('annotations/captions_train2017.json')  as f: _caps_tr = json.load(f)
        with za.open('annotations/captions_val2017.json')    as f: _caps_va = json.load(f)
    del resp

    def _parse_coco(inst, cap):
        cats    = {c['id']: c for c in inst['categories']}
        std_map = {}
        for ann in inst['annotations']:
            iid, cid = ann['image_id'], ann['category_id']
            if cid not in cats: continue
            frag = f"{cats[cid]['name']} {cats[cid]['supercategory']}"
            std_map.setdefault(iid, {'c': [], 'a': []})['c'].append(frag)
        cap_list = {}
        for ann in cap['annotations']:
            iid = ann['image_id']
            std_map.setdefault(iid, {'c': [], 'a': []})['a'].append(ann['caption'])
            cap_list.setdefault(iid, []).append(ann['caption'])
        std_text = {iid: ' . '.join(d['c'] + d['a']) or 'image' for iid, d in std_map.items()}
        return std_text, cap_list

    std_tr, caps_list_tr = _parse_coco(_inst_tr, _caps_tr)
    std_va, caps_list_va = _parse_coco(_inst_va, _caps_va)
    del _inst_tr, _inst_va, _caps_tr, _caps_va
    with open(COCO_CACHE, 'wb') as _f:
        pickle.dump({'std_tr': std_tr, 'std_va': std_va,
                     'caps_list_tr': caps_list_tr, 'caps_list_va': caps_list_va}, _f)
    print(f"  COCO cached {elapsed()}")

with open(STIM_PATH, 'rb') as f: stim_info = pickle.load(f, encoding='latin1')
if isinstance(stim_info, dict): stim_info = pd.DataFrame(stim_info)

print(f"CHUNK 1 done {elapsed()}")


# ════════════════════════════════════════════════════════════════════════════
# CHUNK 2 — PER-SUBJECT fMRI + IMAGE LOADING
# ════════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}\nCHUNK 2: fMRI + IMAGE LOADING\n{'='*70}")
subj_data = {}

for zip_path in SUBJ_ZIPS:
    # Derive subject ID from the zip filename — authoritative, index-independent.
    # subj01.zip → 'subj01', subj03.zip → 'subj03', etc.
    sid = os.path.splitext(os.path.basename(zip_path))[0]   # e.g. 'subj01'
    print(f"\n-- {sid} -- {zip_path}")

    with zipfile.ZipFile(zip_path, 'r') as z:
        all_files = z.namelist()

        # fMRI
        with z.open(next(f for f in all_files if 'lh_training_fmri.npy' in f)) as f:
            lh_fmri = np.load(f)
        with z.open(next(f for f in all_files if 'rh_training_fmri.npy' in f)) as f:
            rh_fmri = np.load(f)

        # Training images — sorted by trial index
        training_images = sorted(
            [f for f in all_files if 'training_split' in f and f.endswith('.png')],
            key=lambda x: int(x.split('train-')[1].split('_')[0]))
        N = len(training_images)

        # NSD image IDs (index into stim_info)
        nsd_ids = np.array([
            int(os.path.basename(p).split('nsd-')[1].split('.')[0])
            for p in training_images])
        print(f"  LH:{lh_fmri.shape}  RH:{rh_fmri.shape}  N:{N}")

        # Cache raw image bytes in memory (avoids re-opening zip later)
        print("  Caching image bytes...")
        img_bytes = []
        for p in training_images:
            with z.open(p) as f: img_bytes.append(f.read())

        # ROI masks — challenge space only (used for aggregation)
        lh_roi_challenge, rh_roi_challenge = {}, {}
        for rt in ROI_TYPES:
            for hemi, chd in [('lh', lh_roi_challenge), ('rh', rh_roi_challenge)]:
                ch = [f for f in all_files
                      if f'{hemi}.{rt}_challenge_space' in f and f.endswith('.npy')]
                if ch:
                    with z.open(ch[0]) as f: chd[rt] = np.load(f)

    # Build voxel→ROI index maps
    def _build_vox_roi_map(roi_ch, hlbl):
        vmap = {}
        for rt in ROI_TYPES:
            if rt not in roi_ch: continue
            for lbl, rname in ROI_LABELS.get(rt, {}).items():
                idx = np.where(roi_ch[rt] == lbl)[0]
                if len(idx) > 0: vmap[f"{rname}_{hlbl}"] = idx
        return vmap

    lh_vox_roi = _build_vox_roi_map(lh_roi_challenge, 'LH')
    rh_vox_roi = _build_vox_roi_map(rh_roi_challenge, 'RH')
    print(f"  LH ROIs:{len(lh_vox_roi)}  RH ROIs:{len(rh_vox_roi)}")

    # Map each trial to its COCO captions via stim_info
    # stim_info.iloc[nsd_id] gives cocoId and cocoSplit
    trial_texts = []
    for nid in nsd_ids:
        row   = stim_info.iloc[nid]
        cid   = int(row['cocoId'])
        split = str(row.get('cocoSplit', 'train2017'))
        if split == 'train2017':
            trial_texts.append(std_tr.get(cid, 'image'))
        else:
            trial_texts.append(std_va.get(cid, 'image'))

    subj_data[sid] = {
        'lh_fmri': lh_fmri, 'rh_fmri': rh_fmri,
        'img_bytes': img_bytes,
        'nsd_ids': nsd_ids, 'N': N,
        'trial_texts': trial_texts,
        'lh_roi_challenge': lh_roi_challenge,
        'rh_roi_challenge': rh_roi_challenge,
        'lh_vox_roi': lh_vox_roi,
        'rh_vox_roi': rh_vox_roi,
    }

print(f"\nCHUNK 2 done — {N_SUBJ} subjects {elapsed()}")


# ════════════════════════════════════════════════════════════════════════════
# CHUNK 3 — FEATURE EXTRACTION
#   L1 : Gabor filterbank
#   L2a: VGG19-avgpool + ResNet50 + CLIP-visual + EfficientNet-B0  → X_vis_a
#   L2b: VGG19 multi-layer GAP (relu3/4/5) → X_vis_b
#   L3 : BERT + GPT-2 + CLIP-text  (each encoded separately, no RoBERTa)
# No PCA anywhere.
# ════════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}\nCHUNK 3: FEATURE EXTRACTION (L1 + L2a/b ensembles + L3×3)\n{'='*70}")

# ── L1: Gabor filterbank ──────────────────────────────────────────────────
def _make_gabors(ksize=21, n_or=8, n_sc=4):
    gs = []
    for sc in range(n_sc):
        sig, lam = 2**sc, 2**(sc+1)
        for o in range(n_or):
            k = cv2.getGaborKernel((ksize, ksize), sig, o*np.pi/n_or, lam, 0.5, 0)
            k /= np.abs(k).sum() + 1e-10
            gs.append(k)
    return gs

_GF = _make_gabors()

def _extract_l1(ib):
    """
    Full Gabor + colour histogram + edge features.
    Output dim = n_filters × n_scales × 2 stats  +  colour patches  +  edge cells
    Fixed for all images; exact dim printed at runtime.
    """
    img  = Image.open(io.BytesIO(ib)).convert('RGB')
    a    = np.array(img)
    gray = cv2.cvtColor(a, cv2.COLOR_RGB2GRAY).astype(np.float32)
    h, w = gray.shape
    feats = []

    # Gabor responses — mean + std in spatial grid (1×1, 2×2, 4×4)
    for gf in _GF:
        r = np.abs(cv2.filter2D(gray, cv2.CV_32F, gf))
        for lv in range(3):
            g = 2**lv
            for ri in range(g):
                for ci_ in range(g):
                    cell = r[ri*h//g:(ri+1)*h//g, ci_*w//g:(ci_+1)*w//g]
                    feats += [np.mean(cell), np.std(cell)]

    # HSV colour histograms in 2×2 spatial grid (16 bins × 3 channels × 4 patches)
    hsv = cv2.cvtColor(a, cv2.COLOR_RGB2HSV).astype(np.float32)
    for qi in range(2):
        for qj in range(2):
            patch = hsv[qi*h//2:(qi+1)*h//2, qj*w//2:(qj+1)*w//2]
            for ch in range(3):
                feats.extend(cv2.calcHist([patch], [ch], None, [16], [0, 256]).flatten())

    # Canny edge density in 2×2 grid, 3 threshold pairs
    for lo, hi in [(50, 100), (100, 200), (150, 300)]:
        edges = cv2.Canny(gray.astype(np.uint8), lo, hi)
        for qi in range(2):
            for qj in range(2):
                feats.append(
                    np.mean(edges[qi*h//2:(qi+1)*h//2, qj*w//2:(qj+1)*w//2] > 0))

    return np.array(feats, dtype=np.float32)

# ── L2a: VGG19 avgpool (512) ──────────────────────────────────────────────
class _VGGFeat(torch.nn.Module):
    def __init__(self, m):
        super().__init__()
        self.f = m.features; self.p = m.avgpool
    def forward(self, x):
        return self.p(self.f(x)).view(x.size(0), -1)

_img_tf_224 = transforms.Compose([
    transforms.Resize((224, 224)), transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]),
])

print(f"  Loading VGG19...")
_vgg_net = _VGGFeat(
    models.vgg19(weights=models.VGG19_Weights.IMAGENET1K_V1)
).to(DEVICE).eval()

# ── L2b: ResNet50 avgpool (2048) ──────────────────────────────────────────
print(f"  Loading ResNet50...")
_resnet = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1).to(DEVICE).eval()
# Hook avgpool output
_resnet_feats = {}
def _resnet_hook(m, i, o): _resnet_feats['out'] = o.squeeze(-1).squeeze(-1)
_resnet.avgpool.register_forward_hook(_resnet_hook)

# ── L2c: CLIP visual encoder (512) ───────────────────────────────────────
print(f"  Loading CLIP vision...")
from transformers import CLIPProcessor, CLIPModel
_clip_model = CLIPModel.from_pretrained('openai/clip-vit-base-patch32').to(DEVICE).eval()
_clip_proc  = CLIPProcessor.from_pretrained('openai/clip-vit-base-patch32')

# ── L2d: EfficientNet-B0 (1280) ───────────────────────────────────────────
print(f"  Loading EfficientNet-B0...")
import timm
_effnet = timm.create_model('efficientnet_b0', pretrained=True,
                             num_classes=0).to(DEVICE).eval()   # num_classes=0 → pooled features

def _extract_l2_ensemble(img_bytes_list, N_s):
    """
    Extract and concatenate all 4 L2 visual models.
    Returns (N, 512+2048+512+1280) = (N, 4352) float32.
    """
    vgg_out, res_out, clip_out, eff_out = [], [], [], []
    for bi in range(0, N_s, IMG_BATCH):
        batch_pil = [Image.open(io.BytesIO(img_bytes_list[i])).convert('RGB')
                     for i in range(bi, min(bi+IMG_BATCH, N_s))]

        # VGG19 + ResNet50 share the same 224×224 normalised transform
        t224 = torch.stack([_img_tf_224(p) for p in batch_pil]).to(DEVICE)
        with torch.no_grad():
            vgg_out.append(_vgg_net(t224).cpu().numpy())
            _resnet(t224)
            res_out.append(_resnet_feats['out'].cpu().numpy())

        # CLIP visual — use vision_model directly, take pooler_output (512-dim)
        clip_in = _clip_proc(images=batch_pil, return_tensors='pt')
        pv = clip_in['pixel_values'].to(DEVICE)
        with torch.no_grad():
            vis_out = _clip_model.vision_model(pixel_values=pv)
            # pooler_output is the [CLS] token projected — shape (B, 768)
            # get_image_features applies the visual projection → 512-dim
            cv = _clip_model.visual_projection(vis_out.pooler_output)
            clip_out.append(cv.cpu().numpy())

        # EfficientNet-B0 — timm's default transform (224×224 same norm)
        with torch.no_grad():
            eff_out.append(_effnet(t224).cpu().numpy())

    vgg_arr  = np.vstack(vgg_out).astype(np.float32)
    res_arr  = np.vstack(res_out).astype(np.float32)
    clip_arr = np.vstack(clip_out).astype(np.float32)
    eff_arr  = np.vstack(eff_out).astype(np.float32)
    combined = np.hstack([vgg_arr, res_arr, clip_arr, eff_arr])
    print(f"    L2a dims — VGG:{vgg_arr.shape[1]} ResNet:{res_arr.shape[1]} "
          f"CLIP-vis:{clip_arr.shape[1]} EffNet:{eff_arr.shape[1]} "
          f"total:{combined.shape[1]}")
    return combined

# ── L2b: VGG19 multi-layer global-average-pool ───────────────────────────
# Hooks on three intermediate relu outputs:
#   features[18] = relu3_4  → 256 channels
#   features[27] = relu4_4  → 512 channels
#   features[36] = relu5_4  → 512 channels
# Each spatial map is global-average-pooled → scalar per channel.
# Concat → 256+512+512 = 1280-dim.
# This captures hierarchical mid-level visual features absent from avgpool alone.
_vgg_full = models.vgg19(weights=models.VGG19_Weights.IMAGENET1K_V1).to(DEVICE).eval()
_vgg_layer_acts = {}

def _make_vgg_hook(name):
    def hook(m, i, o):
        # o shape: (B, C, H, W) → GAP → (B, C)
        _vgg_layer_acts[name] = o.mean(dim=(-2, -1))
    return hook

_vgg_full.features[18].register_forward_hook(_make_vgg_hook('relu3'))
_vgg_full.features[27].register_forward_hook(_make_vgg_hook('relu4'))
_vgg_full.features[36].register_forward_hook(_make_vgg_hook('relu5'))

def _extract_l2b_vgg_multilayer(img_bytes_list, N_s):
    """
    VGG19 multi-layer GAP features.
    Returns (N, 1280) float32  [256 + 512 + 512].
    """
    r3_out, r4_out, r5_out = [], [], []
    for bi in range(0, N_s, IMG_BATCH):
        batch_pil = [Image.open(io.BytesIO(img_bytes_list[i])).convert('RGB')
                     for i in range(bi, min(bi+IMG_BATCH, N_s))]
        t224 = torch.stack([_img_tf_224(p) for p in batch_pil]).to(DEVICE)
        with torch.no_grad():
            _vgg_full(t224)   # forward triggers all hooks
        r3_out.append(_vgg_layer_acts['relu3'].cpu().numpy())
        r4_out.append(_vgg_layer_acts['relu4'].cpu().numpy())
        r5_out.append(_vgg_layer_acts['relu5'].cpu().numpy())
    r3 = np.vstack(r3_out).astype(np.float32)
    r4 = np.vstack(r4_out).astype(np.float32)
    r5 = np.vstack(r5_out).astype(np.float32)
    combined = np.hstack([r3, r4, r5])
    print(f"    L2b dims — relu3:{r3.shape[1]} relu4:{r4.shape[1]} "
          f"relu5:{r5.shape[1]} total:{combined.shape[1]}")
    return combined

# ── L3a: BERT CLS (768) ───────────────────────────────────────────────────
print(f"  Loading BERT...")
from transformers import BertTokenizer, BertModel
_bert_tok = BertTokenizer.from_pretrained('bert-base-uncased')
_bert_mdl = BertModel.from_pretrained('bert-base-uncased').to(DEVICE).eval()

# ── L3b: GPT-2 last non-pad token hidden state (768) ─────────────────────
print(f"  Loading GPT-2...")
from transformers import GPT2Tokenizer, GPT2Model
_gpt2_tok = GPT2Tokenizer.from_pretrained('gpt2')
_gpt2_tok.pad_token = _gpt2_tok.eos_token   # GPT2 has no pad token by default
_gpt2_mdl = GPT2Model.from_pretrained('gpt2').to(DEVICE).eval()

# ── L3c: CLIP text encoder (512) ──────────────────────────────────────────
# _clip_model already loaded above

def _encode_bert(texts):
    parts = []
    for bi in range(0, len(texts), BERT_BATCH):
        enc = _bert_tok(texts[bi:bi+BERT_BATCH], padding=True,
                        truncation=True, max_length=512, return_tensors='pt')
        with torch.no_grad():
            out = _bert_mdl(**{k: v.to(DEVICE) for k, v in enc.items()})
        parts.append(out.last_hidden_state[:, 0, :].cpu().numpy())
    return np.vstack(parts).astype(np.float32)

def _encode_gpt2(texts):
    parts = []
    for bi in range(0, len(texts), BERT_BATCH):
        enc = _gpt2_tok(texts[bi:bi+BERT_BATCH], padding=True,
                        truncation=True, max_length=512, return_tensors='pt')
        enc = {k: v.to(DEVICE) for k, v in enc.items()}
        with torch.no_grad():
            out = _gpt2_mdl(**enc)
        # Last non-pad token: use attention_mask to find it
        hs   = out.last_hidden_state          # (B, T, 768)
        mask = enc['attention_mask']          # (B, T)
        last_idx = mask.sum(dim=1) - 1        # index of last real token
        batch_idx = torch.arange(hs.size(0), device=hs.device)
        parts.append(hs[batch_idx, last_idx, :].cpu().numpy())
    return np.vstack(parts).astype(np.float32)

def _encode_clip_text(texts):
    parts = []
    for bi in range(0, len(texts), BERT_BATCH):
        enc = _clip_proc(text=texts[bi:bi+BERT_BATCH], return_tensors='pt',
                         padding=True, truncation=True, max_length=77)
        input_ids      = enc['input_ids'].to(DEVICE)
        attention_mask = enc['attention_mask'].to(DEVICE)
        with torch.no_grad():
            txt_out = _clip_model.text_model(
                input_ids=input_ids, attention_mask=attention_mask)
            # pooler_output = last [EOS] token hidden state → text_projection → 512-dim
            feat = _clip_model.text_projection(txt_out.pooler_output)
        parts.append(feat.cpu().numpy())
    return np.vstack(parts).astype(np.float32)

L3_ENCODERS = {
    'bert':    _encode_bert,
    'gpt2':    _encode_gpt2,
    'clip':    _encode_clip_text,
}

# ── Per-subject extraction ────────────────────────────────────────────────
for sid, sd in subj_data.items():
    print(f"\n-- Features: {sid} --")
    N_s       = sd['N']
    img_bytes = sd['img_bytes']

    # L1: full Gabor (parallel across images)
    print(f"  L1 Gabor (N={N_s})...")
    gabor_raw = np.array(
        Parallel(n_jobs=N_JOBS)(delayed(_extract_l1)(b) for b in img_bytes),
        dtype=np.float32)
    print(f"  Gabor dim: {gabor_raw.shape[1]}")
    sd['gabor_raw'] = gabor_raw

    # L2a ensemble: VGG19 + ResNet50 + CLIP-visual + EfficientNet
    print(f"  L2a ensemble (N={N_s})...")
    l2a = _extract_l2_ensemble(img_bytes, N_s)
    sd['l2a'] = l2a

    # L2b: VGG multi-layer GAP
    print(f"  L2b VGG multi-layer (N={N_s})...")
    l2b = _extract_l2b_vgg_multilayer(img_bytes, N_s)
    sd['l2b'] = l2b

    # Two X_vis variants
    sd['X_vis_Xa'] = np.hstack([gabor_raw, l2a]).astype(np.float32)
    sd['X_vis_Xb'] = np.hstack([gabor_raw, l2b]).astype(np.float32)
    print(f"  X_vis_Xa dim: {sd['X_vis_Xa'].shape[1]}  "
          f"X_vis_Xb dim: {sd['X_vis_Xb'].shape[1]}  {elapsed()}")

    # L3: encode all 3 language models
    sd['l3_raw'] = {}
    for mkey, encoder in L3_ENCODERS.items():
        print(f"  L3 {mkey} (N={N_s})...")
        emb = encoder(sd['trial_texts'])
        sd['l3_raw'][mkey] = emb
        print(f"    {mkey} dim: {emb.shape[1]}")
        np.save(os.path.join(ARRAYS_DIR, f'{sid}_{mkey}_raw.npy'), emb)

    # Keep bert_raw at top level for backward-compat references
    sd['bert_raw'] = sd['l3_raw']['bert']

del _vgg_net, _vgg_full, _resnet, _clip_model, _bert_mdl, _gpt2_mdl
torch.cuda.empty_cache() if torch.cuda.is_available() else None
print(f"\nCHUNK 3 done {elapsed()}")


# ════════════════════════════════════════════════════════════════════════════
# CHUNK 4 — VISUAL RESIDUALIZATION (single 80/20 split, per L3 model)
#
# For each L3 model separately:
#   1. Split trials into train 80% / test 20% (stratified by subject).
#   2. RidgeCV on train set to select alpha (search over RIDGECV_ALPHAS).
#   3. Fit Ridge(alpha_best) on train X_vis → train L3.
#   4. Residual on TEST set only: L3_wiped[te] = L3_raw[te] - Ridge.predict(X_vis[te])
#   5. Train residuals are discarded — only te indices used in Chunk 5.
#
# Rationale for single fold: N~9000 trials → 20% = ~1800 test samples, more
# than sufficient for stable voxelwise R² estimates. Avoids 5× runtime cost.
# ════════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}\nCHUNK 4: VISUAL RESIDUALIZATION (80/20, per L3 model)\n{'='*70}")

from sklearn.model_selection import train_test_split

def wipe_visual_single_fold(X_vis, l3_raw, model_name,
                             train_frac=WIPE_TRAIN_FRAC,
                             alphas=RIDGECV_ALPHAS,
                             seed=RANDOM_STATE):
    """
    Single 80/20 split residualization of l3_raw against X_vis.

    Returns
    -------
    l3_wiped_te : (N_te, D) residuals on held-out test set
    te_idx      : (N_te,)  trial indices corresponding to l3_wiped_te
    alpha_best  : float
    r2_vis_tr   : float    mean R² on train set (diagnostic, in-sample)
    r2_vis_te   : float    mean R² on test set  (diagnostic, out-of-sample)
    """
    N = l3_raw.shape[0]
    tr_idx, te_idx = train_test_split(
        np.arange(N), train_size=train_frac,
        random_state=seed, shuffle=True)

    # Scale on train only
    sc = StandardScaler().fit(X_vis[tr_idx])
    X_tr = sc.transform(X_vis[tr_idx])
    X_te = sc.transform(X_vis[te_idx])

    # RidgeCV alpha selection on train set
    rcv = RidgeCV(alphas=alphas, fit_intercept=True, cv=5).fit(X_tr, l3_raw[tr_idx])
    alpha_best = float(rcv.alpha_)

    # Fit final Ridge on train, residualise test
    rid = Ridge(alpha=alpha_best, fit_intercept=True).fit(X_tr, l3_raw[tr_idx])
    pred_tr = rid.predict(X_tr)
    pred_te = rid.predict(X_te)

    # Diagnostic R²
    r2_tr = float(np.mean([
        r2_score(l3_raw[tr_idx, d], pred_tr[:, d])
        for d in range(l3_raw.shape[1])]))
    r2_te = float(np.mean([
        r2_score(l3_raw[te_idx, d], pred_te[:, d])
        for d in range(l3_raw.shape[1])]))

    l3_wiped_te = (l3_raw[te_idx] - pred_te).astype(np.float32)

    print(f"    [{model_name}] alpha={alpha_best:.1e}  "
          f"R²_vis→L3 train={r2_tr:.4f}  test={r2_te:.4f}  "
          f"N_te={len(te_idx)}")
    var_raw = float(np.var(l3_raw[te_idx]))
    var_wip = float(np.var(l3_wiped_te))
    print(f"    [{model_name}] variance retained: {var_wip/var_raw*100:.1f}%")

    return l3_wiped_te, te_idx, alpha_best, r2_tr, r2_te

for sid, sd in subj_data.items():
    print(f"\n-- Wipe: {sid} --")
    sd['l3_wiped']    = {}   # wipe_key → (N_te, D) wiped embeddings
    sd['wipe_te_idx'] = {}   # wipe_key → (N_te,) test indices
    sd['wipe_meta']   = {}   # wipe_key → {alpha, r2_vis_tr, r2_vis_te}

    for mkey in L3_MODELS:
        l3_raw = sd['l3_raw'][mkey]
        for xvar in X_VIS_VARIANTS:
            wkey   = f'{mkey}_{xvar}'
            X_vis  = sd[f'X_vis_{xvar}']
            wiped, te_idx, alpha, r2_tr, r2_te = wipe_visual_single_fold(
                X_vis, l3_raw, wkey)
            sd['l3_wiped'][wkey]    = wiped
            sd['wipe_te_idx'][wkey] = te_idx
            sd['wipe_meta'][wkey]   = {'alpha': alpha,
                                        'r2_vis_tr': r2_tr,
                                        'r2_vis_te': r2_te}
            np.save(os.path.join(ARRAYS_DIR, f'{sid}_{wkey}_wiped.npy'), wiped)
            np.save(os.path.join(ARRAYS_DIR, f'{sid}_{wkey}_te_idx.npy'), te_idx)

    # Keep bert_Xa backward-compat aliases
    sd['bert_wiped']  = sd['l3_wiped']['bert_Xa']
    sd['alpha_wipe']  = sd['wipe_meta']['bert_Xa']['alpha']
    sd['r2_vis_bert'] = sd['wipe_meta']['bert_Xa']['r2_vis_te']

print(f"\nCHUNK 4 done {elapsed()}")


# ════════════════════════════════════════════════════════════════════════════
# CHUNK 5 — VOXELWISE R² PREDICTION (per L3 model + BERT-raw baseline)
#
# For each model: KFold-5 Ridge from L3_wiped[te_idx] → fMRI[te_idx].
# Only test-set trials (from the 80/20 wipe split) are used.
# This ensures the wiped embeddings are truly out-of-sample w.r.t. the wipe.
#
# Outputs per subject per hemi:
#   {sid}_{hemi}_r2_{model}_wiped_vox.npy   (4 models)
#   {sid}_{hemi}_r2_raw_vox.npy             (BERT-raw baseline, full N)
# ════════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}\nCHUNK 5: VOXELWISE R² PREDICTION\n{'='*70}")

def _r2_batch(Y_block, X, alpha=RIDGE_ALPHA, n_splits=CMI_FOLDS):
    N_  = Y_block.shape[0]
    kf  = KFold(n_splits=n_splits, shuffle=True, random_state=RANDOM_STATE)
    ss_res = np.zeros(Y_block.shape[1], dtype=np.float64)
    ss_tot = np.zeros(Y_block.shape[1], dtype=np.float64)
    for tr, te in kf.split(np.arange(N_)):
        sc   = StandardScaler().fit(X[tr])
        rid  = Ridge(alpha=alpha, fit_intercept=True).fit(sc.transform(X[tr]), Y_block[tr])
        pred = rid.predict(sc.transform(X[te]))
        res  = Y_block[te] - pred
        tot  = Y_block[te] - Y_block[te].mean(0, keepdims=True)
        ss_res += (res**2).sum(0)
        ss_tot += (tot**2).sum(0)
    return (1.0 - ss_res / (ss_tot + 1e-12)).astype(np.float32)

def _run_voxelwise_r2(fmri, X, desc=''):
    V      = fmri.shape[1]
    blocks = [(i, min(i+VOXEL_BLOCK, V)) for i in range(0, V, VOXEL_BLOCK)]
    print(f"  {desc}: {V} vox | {len(blocks)} blocks {elapsed()}")
    out = np.concatenate(
        Parallel(n_jobs=N_JOBS, prefer='threads')(
            delayed(_r2_batch)(fmri[:, s:e], X) for s, e in blocks))
    print(f"  {desc} done | mean_R²={out.mean():.5f} max_R²={out.max():.5f} {elapsed()}")
    return out

for sid, sd in subj_data.items():
    print(f"\n{'='*50}\nVoxelwise R²: {sid}\n{'='*50}")
    sd['r2_wiped'] = {}   # wipe_key → {hemi: array}
    sd['r2_raw']   = {}

    for hemi, fmri_h in [('LH', sd['lh_fmri']), ('RH', sd['rh_fmri'])]:
        print(f"\n  == {hemi} ({fmri_h.shape[1]} voxels) ==")
        sd['r2_wiped'][hemi] = {}

        # BERT-raw baseline — full N trials
        r2_raw = _run_voxelwise_r2(fmri_h, sd['bert_raw'],
                                    desc=f'{sid}/{hemi}/BERT-raw')
        sd['r2_raw'][hemi] = r2_raw
        np.save(os.path.join(ARRAYS_DIR, f'{sid}_{hemi}_r2_raw_vox.npy'), r2_raw)

        # 6 wiped combinations
        for wkey in WIPE_KEYS:
            te_idx  = sd['wipe_te_idx'][wkey]
            wiped   = sd['l3_wiped'][wkey]
            fmri_te = fmri_h[te_idx]
            r2_w = _run_voxelwise_r2(fmri_te, wiped,
                                      desc=f'{sid}/{hemi}/{wkey}')
            sd['r2_wiped'][hemi][wkey] = r2_w
            np.save(os.path.join(ARRAYS_DIR,
                                  f'{sid}_{hemi}_r2_{wkey}_wiped_vox.npy'), r2_w)

        # Backward compat
        sd[f'{hemi}_r2_wiped'] = sd['r2_wiped'][hemi]['bert_Xa']
        sd[f'{hemi}_r2_raw']   = r2_raw

print(f"\nCHUNK 5 done {elapsed()}")


# ════════════════════════════════════════════════════════════════════════════
# CHUNK 6 — ROI AGGREGATION + TABLES
# T1: one row per subject × hemi × ROI × wipe_key  (6 wipe keys)
# T2: per-subject voxelwise summary per wipe_key
# Column 'wipe_key' encodes both L3 model and X_vis variant, e.g. 'bert_Xa'
# ════════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}\nCHUNK 6: ROI AGGREGATION\n{'='*70}")

def _roi_r2_stats(vidx, r2_wiped, r2_raw):
    w = r2_wiped[vidx]; r = r2_raw[vidx]
    return {
        'r2_wiped_mean':   float(w.mean()),
        'r2_wiped_median': float(np.median(w)),
        'r2_wiped_std':    float(w.std()),
        'r2_wiped_p95':    float(np.percentile(w, 95)),
        'r2_raw_mean':     float(r.mean()),
        'r2_raw_median':   float(np.median(r)),
        'delta_r2_mean':   float((w - r).mean()),
        'frac_pos_wiped':  float((w > 0).mean()),
        'n_voxels':        len(vidx),
    }

t1_rows = []
for sid, sd in subj_data.items():
    for hemi, roi_ch_dict in [('LH', sd['lh_roi_challenge']),
                               ('RH', sd['rh_roi_challenge'])]:
        r2_r = sd[f'{hemi}_r2_raw']
        for wkey in WIPE_KEYS:
            r2_w = sd['r2_wiped'][hemi][wkey]
            l3m, xvar = wkey.rsplit('_', 1)   # e.g. 'bert', 'Xa'
            for rt in ROI_TYPES:
                if rt not in roi_ch_dict: continue
                ch_mask = roi_ch_dict[rt]
                for lbl in np.unique(ch_mask[ch_mask != 0]):
                    lbl   = int(lbl)
                    rname = ROI_LABELS.get(rt, {}).get(lbl, f'R{lbl}')
                    vidx  = np.where(ch_mask == lbl)[0]
                    if len(vidx) < 5: continue
                    stats_d = _roi_r2_stats(vidx, r2_w, r2_r)
                    stats_d.update({'subject': sid, 'hemi': hemi,
                                    'roi_type': rt, 'roi_name': rname,
                                    'wipe_key': wkey,
                                    'l3_model': l3m, 'x_variant': xvar})
                    t1_rows.append(stats_d)

T1 = pd.DataFrame(t1_rows)
T1.to_csv(os.path.join(TABLES_DIR, 'T1_roi_r2.csv'), index=False)
print(f"  T1 (ROI×wipe_key): {len(T1)} rows")

# Per-subject voxelwise summary per wipe_key
vox_rows = []
for sid, sd in subj_data.items():
    for hemi in ['LH', 'RH']:
        r2_r = sd[f'{hemi}_r2_raw']
        for wkey in WIPE_KEYS:
            r2_w = sd['r2_wiped'][hemi][wkey]
            meta = sd['wipe_meta'][wkey]
            l3m, xvar = wkey.rsplit('_', 1)
            vox_rows.append({
                'subject': sid, 'hemi': hemi,
                'wipe_key': wkey, 'l3_model': l3m, 'x_variant': xvar,
                'n_voxels':             len(r2_w),
                'n_te_trials':          len(sd['wipe_te_idx'][wkey]),
                'r2_wiped_mean':        float(r2_w.mean()),
                'r2_wiped_positive_frac': float((r2_w > 0).mean()),
                'r2_raw_mean':          float(r2_r.mean()),
                'delta_r2_mean':        float((r2_w - r2_r).mean()),
                'alpha_wipe':           meta['alpha'],
                'r2_vis_tr':            meta['r2_vis_tr'],
                'r2_vis_te':            meta['r2_vis_te'],
            })
T2 = pd.DataFrame(vox_rows)
T2.to_csv(os.path.join(TABLES_DIR, 'T2_voxelwise_r2_summary.csv'), index=False)
print(f"  T2 (vox summary): {len(T2)} rows")
print(T2[['subject','hemi','wipe_key','r2_wiped_mean','r2_wiped_positive_frac',
          'r2_raw_mean','alpha_wipe','r2_vis_te']].to_string(index=False))

print(f"\nCHUNK 6 done {elapsed()}")


# ════════════════════════════════════════════════════════════════════════════

# ════════════════════════════════════════════════════════════════════════════
# CHUNK 7 — GROUP AGGREGATION + PUBLICATION FIGURES
#
# Per model: random-effects t-test + EXACT sign-flip test (2^N permutations),
# Hedge's g, BH-FDR (applied per model separately).
# Semantic independence ratio = r2_wiped / r2_raw.
#
# Figures (300 DPI PDF) — one set per L3 model:
#   fig1_{model}.pdf  — regional dissociation (paired LH/RH bars, ROI-grouped)
#   fig2_{model}.pdf  — subject-level replication (3 key ROIs, paired lines)
# Plus one shared set:
#   fig3_flatmap_{hemi}_{view}.pdf — group cortical flatmap (BERT model)
#
# CSVs:
#   T3_group_roi_r2.csv       — all models, all ROIs, full stats
#   T4_fig1_{model}.csv       — Fig 1 data per model
#   T5_fig2_{model}.csv       — Fig 2 data per model
#   T6_flatmap_group.csv      — per-vertex flatmap (BERT)
# ════════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}\nCHUNK 7: GROUP AGGREGATION + PUBLICATION FIGURES (N={N_SUBJ})\n{'='*70}")

import itertools
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
import matplotlib.gridspec as gridspec

DPI = 300

# ── Palette + display order ───────────────────────────────────────────────
_ROI_PAL = {
    'prf-visualrois': '#B0413E',
    'floc-bodies':    '#2B8C7E',
    'floc-faces':     '#E8A838',
    'floc-places':    '#4A7FB5',
    'floc-words':     '#7B52AB',
    'streams':        '#5A8A5A',
}
_ROI_TYPE_ORDER = ['floc-bodies','floc-faces','floc-places','floc-words',
                   'streams','prf-visualrois']
_ROI_TYPE_LABEL = {
    'prf-visualrois': 'Visual (V1–V4)',
    'floc-bodies':    'Body-selective',
    'floc-faces':     'Face-selective',
    'floc-places':    'Place-selective',
    'floc-words':     'Word-selective',
    'streams':        'Streams',
}
_MODEL_LABEL = {
    'bert':  'BERT',
    'gpt2':  'GPT-2',
    'clip':  'CLIP-text',
}
_XVAR_LABEL = {
    'Xa': 'X_vis-A (ensemble)',
    'Xb': 'X_vis-B (VGG-multilayer)',
}
def _wkey_label(wkey):
    l3m, xvar = wkey.rsplit('_', 1)
    return f"{_MODEL_LABEL.get(l3m,l3m)} | {_XVAR_LABEL.get(xvar,xvar)}"

def _hedges_g(vals):
    n = len(vals); m = float(np.mean(vals)); s = float(np.std(vals, ddof=1))
    if s < 1e-12 or n < 2: return 0.0
    return (m / s) * (1.0 - 3.0 / (4.0*(n-1) - 1))

def _sign_flip_p(vals):
    """Exact one-tailed sign-flip test. H0: mean(vals) <= 0."""
    vals = np.asarray(vals, dtype=np.float64)
    obs  = vals.mean()
    signs = np.array(list(itertools.product([-1,1], repeat=len(vals))),
                     dtype=np.float64)
    null_means = (signs * vals[np.newaxis,:]).mean(axis=1)
    return float((null_means >= obs).mean())

# ── Build group table (all 6 wipe keys) ───────────────────────────────────
grp_rows = []
roi_keys = T1[['hemi','roi_type','roi_name']].drop_duplicates().values.tolist()

for wkey in WIPE_KEYS:
    l3m, xvar = wkey.rsplit('_', 1)
    T1_w = T1[T1['wipe_key'] == wkey]
    p_vals_all = []
    row_buf    = []

    for hemi, rt, rname in roi_keys:
        sub_df = T1_w[(T1_w['hemi']==hemi) & (T1_w['roi_name']==rname)]
        sub_w  = sub_df['r2_wiped_mean'].values
        sub_r  = sub_df['r2_raw_mean'].values
        n      = len(sub_w)
        if n < 2: continue

        m_w   = float(sub_w.mean())
        sem_w = float(sub_w.std(ddof=1) / np.sqrt(n))
        m_r   = float(sub_r.mean())
        sem_r = float(sub_r.std(ddof=1) / np.sqrt(n))
        t, p_t = stats.ttest_1samp(sub_w, 0.0)
        g       = _hedges_g(sub_w)
        p_sf    = _sign_flip_p(sub_w)
        ratios  = sub_w / np.maximum(sub_r, 1e-8)

        row_buf.append({
            'wipe_key': wkey, 'l3_model': l3m, 'x_variant': xvar,
            'hemi': hemi, 'roi_type': rt, 'roi_name': rname,
            'n_subjects':    n,
            'r2_wiped_mean': m_w,  'r2_wiped_sem': sem_w,
            'r2_raw_mean':   m_r,  'r2_raw_sem':   sem_r,
            'ratio_mean':  float(ratios.mean()),
            'ratio_sem':   float(ratios.std(ddof=1)/np.sqrt(n)),
            't_stat': float(t), 'p_ttest': float(p_t),
            'p_signflip': p_sf,  'hedges_g': g,
        })
        p_vals_all.append(p_sf)

    if not row_buf: continue
    _, q_sf, _, _ = smm.multipletests(p_vals_all, alpha=0.05, method='fdr_bh')
    p_t_all = [r['p_ttest'] for r in row_buf]
    _, q_t,  _, _ = smm.multipletests(p_t_all,  alpha=0.05, method='fdr_bh')
    for i, row in enumerate(row_buf):
        row['q_signflip'] = float(q_sf[i])
        row['q_ttest']    = float(q_t[i])
        row['sig']        = row['q_signflip'] < 0.05
        grp_rows.append(row)

T_group = pd.DataFrame(grp_rows)
T_group.to_csv(os.path.join(TABLES_DIR, 'T3_group_roi_r2.csv'), index=False)
print(f"  T_group: {len(T_group)} rows")
if T_group.empty:
    print(f"  WARNING: T_group is empty — need N≥2 subjects for group stats.")
    print(f"  Sign-flip test requires at least 2 subjects. Run with subj01–07.")
else:
    for wkey in WIPE_KEYS:
        n_sig = T_group[(T_group['wipe_key']==wkey) & T_group['sig']].shape[0]
        print(f"    {wkey:12s}: FDR-sig (sign-flip q<0.05) = {n_sig}")

# ── Figure helpers ────────────────────────────────────────────────────────
def _build_fig1_order(tg_model):
    tg_avg = (tg_model.groupby(['roi_type','roi_name'])['r2_wiped_mean']
                       .mean().reset_index())
    rows = []
    for rt in _ROI_TYPE_ORDER:
        sub = tg_avg[tg_avg['roi_type']==rt].sort_values(
                  'r2_wiped_mean', ascending=False)
        for _, row in sub.iterrows():
            rows.append((row['roi_name'], row['roi_type']))
    return rows

def _get_grp(tg, rname, hemi):
    rows = tg[(tg['roi_name']==rname) & (tg['hemi']==hemi)]
    return rows.iloc[0] if len(rows) else None

def _get_subj_vals(T1_m, rname, hemi, col='r2_wiped_mean'):
    rows = T1_m[(T1_m['roi_name']==rname) & (T1_m['hemi']==hemi)]
    return rows[col].values if len(rows) else np.array([])

# ── Loop over 6 wipe keys — Fig 1 + Fig 2 ────────────────────────────────
T4_all, T5_all = [], []
rng  = np.random.RandomState(42)
rng2 = np.random.RandomState(7)

if T_group.empty:
    print("  Skipping figures — T_group empty (need N≥2 subjects).")
else:
    for wkey in WIPE_KEYS:
        mlabel = _wkey_label(wkey)
        l3m, xvar = wkey.rsplit('_', 1)
        T1_w   = T1[T1['wipe_key'] == wkey]
        tg_m   = T_group[T_group['wipe_key'] == wkey]
        if tg_m.empty: continue

        print(f"\n  Fig 1+2 for {wkey} {elapsed()}")

        roi_order_f1 = _build_fig1_order(tg_m)
        roi_names_f1 = [r for r,_ in roi_order_f1]
        roi_types_f1 = [t for _,t in roi_order_f1]
        N_ROI = len(roi_names_f1)
        BAR_W = 0.35
        xs_lh = np.arange(N_ROI) - BAR_W/2
        xs_rh = np.arange(N_ROI) + BAR_W/2

        # Build bar arrays
        lh_w,lh_sem,lh_ratio,lh_rsem,lh_sig = [],[],[],[],[]
        rh_w,rh_sem,rh_ratio,rh_rsem,rh_sig = [],[],[],[],[]
        for rname in roi_names_f1:
            for store_w,store_s,store_ra,store_rs,store_sig,hemi in [
                (lh_w,lh_sem,lh_ratio,lh_rsem,lh_sig,'LH'),
                (rh_w,rh_sem,rh_ratio,rh_rsem,rh_sig,'RH'),
            ]:
                row = _get_grp(tg_m, rname, hemi)
                if row is not None:
                    store_w.append(row['r2_wiped_mean'])
                    store_s.append(row['r2_wiped_sem'])
                    store_ra.append(row['ratio_mean'])
                    store_rs.append(row['ratio_sem'])
                    store_sig.append(bool(row['sig']))
                else:
                    store_w.append(np.nan); store_s.append(0)
                    store_ra.append(np.nan); store_rs.append(0)
                    store_sig.append(False)

        # ── Figure 1 ──────────────────────────────────────────────────────
        fig1, (ax1, ax2) = plt.subplots(1, 2, figsize=(22, 6))
        for ax, vals_lh,sems_lh,vals_rh,sems_rh,sig_lh,sig_rh,ylabel,title_sfx in [
            (ax1, lh_w,lh_sem,rh_w,rh_sem,lh_sig,rh_sig,
             'Mean R²_wiped ± SEM (across subjects)', f'R²_wiped — {mlabel}'),
            (ax2, lh_ratio,lh_rsem,rh_ratio,rh_rsem,lh_sig,rh_sig,
             'Semantic independence ratio  (R²_wiped / R²_raw)',
             f'Independence ratio — {mlabel}'),
        ]:
            clrs = [_ROI_PAL.get(rt,'#888') for rt in roi_types_f1]
            ax.bar(xs_lh, vals_lh, width=BAR_W, color=clrs, alpha=0.60,
                   edgecolor='white', linewidth=0.4, zorder=2, label='LH')
            ax.errorbar(xs_lh, vals_lh, yerr=sems_lh,
                        fmt='none', color='#333', capsize=2, linewidth=0.8, zorder=3)
            ax.bar(xs_rh, vals_rh, width=BAR_W, color=clrs, alpha=0.95,
                   edgecolor='white', linewidth=0.4, hatch='//', zorder=2, label='RH')
            ax.errorbar(xs_rh, vals_rh, yerr=sems_rh,
                        fmt='none', color='#111', capsize=2, linewidth=0.8, zorder=3)

            all_tops = [v+s for v,s in zip(vals_lh+vals_rh, sems_lh+sems_rh)
                        if not np.isnan(v)]
            y_hi = max(all_tops) if all_tops else 0.01
            y_lo = min([v for v in vals_lh+vals_rh if not np.isnan(v)] or [0])
            y_rng = max(y_hi-y_lo, 1e-6)
            for xi in range(N_ROI):
                for xs_h,vals_h,sems_h,sig_h,offset in [
                    (xs_lh,vals_lh,sems_lh,sig_lh,-BAR_W/2),
                    (xs_rh,vals_rh,sems_rh,sig_rh, BAR_W/2),
                ]:
                    if sig_h[xi] and not np.isnan(vals_h[xi]):
                        ax.text(xi+offset, vals_h[xi]+sems_h[xi]+y_rng*0.015,
                                '★', ha='center', va='bottom', fontsize=7,
                                color='#111', fontweight='bold', zorder=5)

            if ax is ax2:
                for xi, rname in enumerate(roi_names_f1):
                    for xs_h, hemi in [(xs_lh[xi],'LH'),(xs_rh[xi],'RH')]:
                        w_v = _get_subj_vals(T1_w, rname, hemi, 'r2_wiped_mean')
                        r_v = _get_subj_vals(T1_w, rname, hemi, 'r2_raw_mean')
                        if len(w_v) == 0: continue
                        rat = w_v / np.maximum(r_v, 1e-8)
                        jit = rng.uniform(-0.06, 0.06, len(rat))
                        ax.scatter(xs_h+jit, rat, s=9, color='#111',
                                   alpha=0.50, zorder=4, linewidths=0)

            ax.axhline(0, color='#444', linewidth=0.5, linestyle='--', zorder=1)
            ax.set_xticks(np.arange(N_ROI))
            ax.set_xticklabels(roi_names_f1, rotation=50, ha='right', fontsize=7)
            ax.set_ylabel(ylabel, fontsize=9)
            ax.set_title(f'{title_sfx}  (N={N_SUBJ})  ★ = sign-flip FDR q<0.05',
                         fontsize=10, pad=8)

            prev_rt = None; type_starts = {}
            for xi, (_,rt) in enumerate(roi_order_f1):
                if rt != prev_rt:
                    if xi > 0: ax.axvline(xi-0.5, color='#bbb', linewidth=0.7,
                                           linestyle=':', zorder=0)
                    type_starts[rt] = xi; prev_rt = rt
            for rt, xi_s in type_starts.items():
                xi_e = max(j for j,(_,t) in enumerate(roi_order_f1) if t==rt)
                ax.text((xi_s+xi_e)/2, ax.get_ylim()[1]*0.97,
                        _ROI_TYPE_LABEL.get(rt,rt), ha='center', va='top',
                        fontsize=6.5, color=_ROI_PAL.get(rt,'#888'),
                        fontweight='bold', style='italic')

            leg_hemi = [Patch(fc='grey',alpha=0.60,ec='none',label='LH'),
                        Patch(fc='grey',alpha=0.95,hatch='//',ec='none',label='RH')]
            leg_type = [Patch(fc=_ROI_PAL[rt],ec='none',
                              label=_ROI_TYPE_LABEL.get(rt,rt))
                        for rt in _ROI_TYPE_ORDER if rt in roi_types_f1]
            ax.legend(handles=leg_hemi+leg_type, fontsize=6.5,
                      loc='upper right', framealpha=0.85, edgecolor='none', ncol=2)

        fig1.suptitle(
            f'Figure 1 — Regional dissociation  [{mlabel}]\n'
            'R²_wiped: fMRI variance explained by vision-residualised language embedding',
            fontsize=11, y=1.01)
        plt.tight_layout()
        p1 = os.path.join(FIGS_DIR, f'fig1_{wkey}.pdf')
        fig1.savefig(p1, dpi=DPI, bbox_inches='tight'); plt.close(fig1)
        print(f"    Saved {p1}")

        # Save T4 for this wipe_key
        for rname, rt in roi_order_f1:
            for hemi in ['LH','RH']:
                row = _get_grp(tg_m, rname, hemi)
                if row is None: continue
                T4_all.append({
                    'wipe_key': wkey, 'l3_model': l3m, 'x_variant': xvar,
                    'roi_name': rname, 'roi_type': rt, 'hemi': hemi,
                    'n_subjects':    row['n_subjects'],
                    'r2_wiped_mean': row['r2_wiped_mean'],
                    'r2_wiped_sem':  row['r2_wiped_sem'],
                    'r2_raw_mean':   row['r2_raw_mean'],
                    'ratio_mean':    row['ratio_mean'],
                    'ratio_sem':     row['ratio_sem'],
                    't_stat':        row['t_stat'],
                    'p_ttest':       row['p_ttest'],
                    'q_ttest':       row['q_ttest'],
                    'p_signflip':    row['p_signflip'],
                    'q_signflip':    row['q_signflip'],
                    'sig':           row['sig'],
                    'hedges_g':      row['hedges_g'],
                })

        # ── Figure 2 ──────────────────────────────────────────────────────
        _KEY_ROIS = [
            ('EBA',     'RH', 'Body-selective\n(EBA, RH)'),
            ('ventral', 'LH', 'Ventral stream\n(LH)'),
            ('V1v',     'LH', 'Early visual\n(V1v, LH) — null'),
        ]
        fig2_rows = []
        for rname, pref_hemi, label in _KEY_ROIS:
            sub_df = T1_w[(T1_w['roi_name']==rname) & (T1_w['hemi']==pref_hemi)]
            if sub_df.empty:
                sub_df = T1_w[T1_w['roi_name']==rname]
                if sub_df.empty: continue
                pref_hemi = sub_df['hemi'].iloc[0]
            for _, row in sub_df.iterrows():
                fig2_rows.append({
                    'wipe_key': wkey, 'l3_model': l3m, 'x_variant': xvar,
                    'subject': row['subject'],
                    'roi_name': rname, 'roi_label': label, 'hemi': pref_hemi,
                    'r2_wiped': row['r2_wiped_mean'],
                    'r2_raw':   row['r2_raw_mean'],
                    'ratio':    row['r2_wiped_mean'] / max(row['r2_raw_mean'], 1e-8),
                })
        T5_all.extend(fig2_rows)

        T5_m = pd.DataFrame(fig2_rows)
        if T5_m.empty: continue
        key_rnames = [r for r,_,_ in _KEY_ROIS if r in T5_m['roi_name'].values]
        key_labels = {r: l for r,_,l in _KEY_ROIS}
        key_clrs   = {'EBA': _ROI_PAL['floc-bodies'],
                      'ventral': _ROI_PAL['streams'],
                      'V1v': _ROI_PAL['prf-visualrois']}
        xs_f2 = np.arange(len(key_rnames))

        fig2, ax2m = plt.subplots(figsize=(6, 5.5))
        grp_m  = [T5_m[T5_m['roi_name']==r]['ratio'].mean() for r in key_rnames]
        grp_se = [T5_m[T5_m['roi_name']==r]['ratio'].std(ddof=1) /
                  np.sqrt(max(len(T5_m[T5_m['roi_name']==r]),1)) for r in key_rnames]
        ax2m.bar(xs_f2, grp_m, color=[key_clrs.get(r,'#888') for r in key_rnames],
                 edgecolor='white', linewidth=0.4, zorder=2, width=0.45, alpha=0.65)
        ax2m.errorbar(xs_f2, grp_m, yerr=grp_se,
                      fmt='none', color='#111', capsize=5, linewidth=1.2, zorder=3)

        subjects  = sorted(T5_m['subject'].unique())
        subj_pal  = plt.cm.tab10(np.linspace(0, 0.9, len(subjects)))
        subj_col  = {s: subj_pal[i] for i,s in enumerate(subjects)}
        for sid in subjects:
            xs_s, ys_s = [], []
            for xi, rname in enumerate(key_rnames):
                row_s = T5_m[(T5_m['subject']==sid) & (T5_m['roi_name']==rname)]
                if row_s.empty: continue
                xs_s.append(xi); ys_s.append(float(row_s['ratio'].values[0]))
            if len(xs_s) > 1:
                ax2m.plot(xs_s, ys_s, color=subj_col[sid], alpha=0.4,
                          linewidth=1.0, zorder=3)
            jit = rng2.uniform(-0.07, 0.07, len(xs_s))
            ax2m.scatter([x+j for x,j in zip(xs_s,jit)], ys_s,
                         s=38, color=subj_col[sid], alpha=0.9,
                         zorder=4, linewidths=0.5, edgecolors='white')

        ax2m.axhline(0, color='#444', linewidth=0.6, linestyle='--', zorder=1)
        ax2m.set_xticks(xs_f2)
        ax2m.set_xticklabels([key_labels.get(r,r) for r in key_rnames], fontsize=9)
        ax2m.set_ylabel('Semantic independence ratio  (R²_wiped / R²_raw)', fontsize=9)
        ax2m.set_title(f'Figure 2 — Subject replication  [{mlabel}]  (N={N_SUBJ})\n'
                       'Bars = group mean ± SEM   •  = individual subjects', fontsize=10)
        leg = [Line2D([0],[0], marker='o', color=subj_col[s], lw=0.9,
                      markersize=5, label=s) for s in subjects]
        ax2m.legend(handles=leg, fontsize=6.5, loc='upper right',
                    ncol=2, framealpha=0.85, edgecolor='none')
        plt.tight_layout()
        p2 = os.path.join(FIGS_DIR, f'fig2_{wkey}.pdf')
        fig2.savefig(p2, dpi=DPI, bbox_inches='tight'); plt.close(fig2)
        print(f"    Saved {p2}")


# ── Figure 3 — Cortical flatmap (BERT only for pilot) ─────────────────────
print(f"\n  Generating Figure 3 (flatmaps, BERT) {elapsed()}")
flatmap_csv_rows = []
try:
    from nilearn import plotting as nilplot
    from nilearn import datasets as nildatasets
    fsaverage = nildatasets.fetch_surf_fsaverage('fsaverage')

    for hemi_u, hemi_l, fs_surf, fs_bg in [
        ('LH','lh','infl_left','sulc_left'),
        ('RH','rh','infl_right','sulc_right'),
    ]:
        N_VERT   = 163842
        sum_map  = np.zeros(N_VERT, dtype=np.float64)
        cnt_map  = np.zeros(N_VERT, dtype=np.int32)

        for sid in list(subj_data.keys()):
            zpath = next((z for z in SUBJ_ZIPS if sid in z), None)
            if zpath is None: continue
            try:
                with zipfile.ZipFile(zpath,'r') as z:
                    af = z.namelist()
                    mf = [f for f in af
                          if f'{hemi_l}.all-vertices_fsaverage_space' in f
                          and f.endswith('.npy')]
                    if not mf: continue
                    with z.open(mf[0]) as f:
                        vert_mask = np.load(f).astype(bool)
            except Exception as e:
                print(f"    Warning fsaverage mask {sid}: {e}"); continue

            r2w_path = os.path.join(ARRAYS_DIR, f'{sid}_{hemi_u}_r2_bert_Xa_wiped_vox.npy')
            if not os.path.exists(r2w_path): continue
            r2w_ch = np.load(r2w_path).astype(np.float64)
            vert_idx = np.where(vert_mask)[0]
            n_match  = min(len(vert_idx), r2w_ch.shape[0])
            sum_map[vert_idx[:n_match]] += r2w_ch[:n_match]
            cnt_map[vert_idx[:n_match]] += 1

        grp_map = np.full(N_VERT, np.nan, dtype=np.float32)
        valid   = cnt_map > 0
        grp_map[valid] = (sum_map[valid] / cnt_map[valid]).astype(np.float32)
        np.save(os.path.join(ARRAYS_DIR, f'group_{hemi_u}_r2_wiped_fsaverage.npy'), grp_map)

        for vi in np.where(valid)[0]:
            flatmap_csv_rows.append({'hemi': hemi_u, 'vertex': int(vi),
                'r2_wiped_group_mean': float(grp_map[vi]),
                'n_subjects': int(cnt_map[vi])})

        pos_vals = grp_map[valid & (grp_map > 0)]
        vmax = float(np.percentile(pos_vals, 99)) if len(pos_vals) else 0.05
        vmax = max(vmax, 1e-4)

        for view, vtag in [('lateral','lateral'),('ventral','ventral')]:
            fig3, ax3 = plt.subplots(figsize=(11, 4.5))
            ax3.axis('off')
            nilplot.plot_surf_stat_map(
                surf_mesh=getattr(fsaverage, fs_surf),
                stat_map=grp_map, hemi=hemi_l, view=view,
                bg_map=getattr(fsaverage, fs_bg),
                cmap='RdBu_r', vmax=vmax, symmetric_cbar=True, colorbar=True,
                title=(f'Figure 3 — Group R²_wiped [BERT]  {hemi_u} ({vtag})'
                       f'  N={int(cnt_map.max())}'),
                figure=fig3, axes=ax3)
            p3 = os.path.join(FIGS_DIR, f'fig3_flatmap_{hemi_u}_{vtag}.pdf')
            fig3.savefig(p3, dpi=DPI, bbox_inches='tight'); plt.close(fig3)
            print(f"    Saved {p3}")

    if flatmap_csv_rows:
        T6 = pd.DataFrame(flatmap_csv_rows)
        T6.to_csv(os.path.join(TABLES_DIR,'T6_flatmap_group.csv'), index=False)
        print(f"    Saved T6_flatmap_group.csv ({len(T6)} vertices)")

except ImportError:
    print("    nilearn not available — skipping Figure 3")
except Exception as e:
    print(f"    Figure 3 failed: {e}"); import traceback; traceback.print_exc()

# ── Summary ───────────────────────────────────────────────────────────────
print(f"\nCHUNK 7 done {elapsed()}")
print(f"\n{'='*70}\nPIPELINE v9.1 COMPLETE {elapsed()}  |  N={N_SUBJ} subjects\n{'='*70}")
print(f"Outputs in: {OUT_DIR}")
print(f"  arrays/ : {{sid}}_{{hemi}}_r2_{{model}}_wiped_vox.npy  (×{len(L3_MODELS)} models)")
print(f"            {{sid}}_{{model}}_wiped.npy  {{sid}}_{{model}}_raw.npy")
print(f"            group_LH/RH_r2_wiped_fsaverage.npy")
print(f"  tables/ : T1_roi_r2.csv  T2_voxelwise_r2_summary.csv")
print(f"            T3_group_roi_r2.csv  T4_fig1_plot_data.csv")
print(f"            T5_fig2_subject_dots.csv  T6_flatmap_group.csv")
print(f"  figures/: fig1_{{model}}.pdf  fig2_{{model}}.pdf  (×{len(L3_MODELS)} models)")
print(f"            fig3_flatmap_LH/RH_lateral/ventral.pdf")

"""
NSD ARCHIVE CHUNK — Complete state serialisation after v9.1
============================================================
Run this immediately after nsd_pipeline_v9.1.py completes (same Colab session).
Saves every intermediate and final value from every chunk to Google Drive so
you can reload and plot later without re-running the pipeline.

Outputs written to:  {OUT_DIR}/archive/
  subj_data_core.pkl          — per-subject arrays (fMRI, features, wipes, R² maps)
  tables_all.pkl              — all DataFrames (T1–T6, T_group)
  config_snapshot.json        — all config values + dim info + wipe metadata
  {sid}_full_state.pkl        — one pkl per subject with every array
  README_archive.txt          — human-readable inventory of everything saved

All arrays also remain in {OUT_DIR}/arrays/ as individual .npy files (written
by the pipeline itself). This chunk adds Python-native pkls + a config snapshot
so you have a single-load entry point for plotting.
"""

import os, json, pickle, numpy as np, pandas as pd
from datetime import datetime

# ── Locate output directories (set by pipeline) ───────────────────────────
# These variables must already exist in the session from running v9.1
ARCHIVE_DIR = os.path.join(OUT_DIR, 'archive')
os.makedirs(ARCHIVE_DIR, exist_ok=True)
print(f"Archive dir: {ARCHIVE_DIR}")
TIMESTAMP = datetime.now().strftime('%Y%m%d_%H%M%S')

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 1 — CONFIG SNAPSHOT
# Everything you'd need to reconstruct exactly what was run
# ═══════════════════════════════════════════════════════════════════════════
print("\n── Section 1: Config snapshot ──")

config = {
    'timestamp':        TIMESTAMP,
    'pipeline_version': 'v9.1',
    'subjects':         list(subj_data.keys()),
    'n_subjects':       N_SUBJ,
    'out_dir':          OUT_DIR,
    'l3_models':        L3_MODELS,
    'x_vis_variants':   X_VIS_VARIANTS,
    'wipe_keys':        WIPE_KEYS,
    'wipe_train_frac':  WIPE_TRAIN_FRAC,
    'ridgecv_alphas':   RIDGECV_ALPHAS.tolist(),
    'ridge_alpha_vox':  RIDGE_ALPHA,
    'n_jobs':           N_JOBS,
    'img_batch':        IMG_BATCH,
    'bert_batch':       BERT_BATCH,
    'cmi_folds':        CMI_FOLDS,
    'voxel_block':      VOXEL_BLOCK,
    'random_state':     RANDOM_STATE,
    'alpha_sig':        ALPHA_SIG,
    'gabor_n_orient':   8,
    'gabor_n_scale':    4,
}

# Per-subject dimension info
config['subject_dims'] = {}
for sid, sd in subj_data.items():
    config['subject_dims'][sid] = {
        'n_trials':       int(sd['N']),
        'lh_n_voxels':    int(sd['lh_fmri'].shape[1]),
        'rh_n_voxels':    int(sd['rh_fmri'].shape[1]),
        'gabor_dim':      int(sd['gabor_raw'].shape[1]),
        'l2a_dim':        int(sd['l2a'].shape[1]),
        'l2b_dim':        int(sd['l2b'].shape[1]),
        'x_vis_Xa_dim':   int(sd['X_vis_Xa'].shape[1]),
        'x_vis_Xb_dim':   int(sd['X_vis_Xb'].shape[1]),
        'l3_dims':        {m: int(sd['l3_raw'][m].shape[1]) for m in L3_MODELS},
        'n_te_trials':    {wk: int(len(sd['wipe_te_idx'][wk])) for wk in WIPE_KEYS},
        'wipe_alpha':     {wk: float(sd['wipe_meta'][wk]['alpha']) for wk in WIPE_KEYS},
        'wipe_r2_vis_tr': {wk: float(sd['wipe_meta'][wk]['r2_vis_tr']) for wk in WIPE_KEYS},
        'wipe_r2_vis_te': {wk: float(sd['wipe_meta'][wk]['r2_vis_te']) for wk in WIPE_KEYS},
        'r2_wiped_mean':  {
            hemi: {wk: float(sd['r2_wiped'][hemi][wk].mean()) for wk in WIPE_KEYS}
            for hemi in ['LH','RH']
        },
        'r2_wiped_max':   {
            hemi: {wk: float(sd['r2_wiped'][hemi][wk].max()) for wk in WIPE_KEYS}
            for hemi in ['LH','RH']
        },
        'r2_wiped_pos_frac': {
            hemi: {wk: float((sd['r2_wiped'][hemi][wk] > 0).mean()) for wk in WIPE_KEYS}
            for hemi in ['LH','RH']
        },
        'r2_raw_mean': {
            hemi: float(sd['r2_raw'][hemi].mean())
            for hemi in ['LH','RH']
        },
    }

config_path = os.path.join(ARCHIVE_DIR, 'config_snapshot.json')
with open(config_path, 'w') as f:
    json.dump(config, f, indent=2)
print(f"  Saved: config_snapshot.json")

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 2 — ALL DATAFRAMES
# ═══════════════════════════════════════════════════════════════════════════
print("\n── Section 2: DataFrames ──")

tables = {
    'T1_roi_r2':           T1,
    'T2_voxelwise_summary': T2,
    'T3_group_roi_r2':      T_group,
}

# T4/T5/T6 may not exist if T_group was empty (N=1 run)
try:
    T4 = pd.read_csv(os.path.join(TABLES_DIR, 'T4_fig1_plot_data.csv'))
    tables['T4_fig1_plot_data'] = T4
except FileNotFoundError:
    print("  T4 not found (expected if N=1)")
try:
    T5 = pd.read_csv(os.path.join(TABLES_DIR, 'T5_fig2_subject_dots.csv'))
    tables['T5_fig2_subject_dots'] = T5
except FileNotFoundError:
    print("  T5 not found (expected if N=1)")
try:
    T6 = pd.read_csv(os.path.join(TABLES_DIR, 'T6_flatmap_group.csv'))
    tables['T6_flatmap_group'] = T6
except FileNotFoundError:
    print("  T6 not found (no flatmap run)")

tables_path = os.path.join(ARCHIVE_DIR, 'tables_all.pkl')
with open(tables_path, 'wb') as f:
    pickle.dump(tables, f, protocol=4)
print(f"  Saved: tables_all.pkl  ({len(tables)} tables)")
for k, v in tables.items():
    print(f"    {k}: {len(v)} rows × {len(v.columns)} cols")

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 3 — PER-SUBJECT FULL STATE (arrays)
# ═══════════════════════════════════════════════════════════════════════════
print("\n── Section 3: Per-subject arrays ──")

# What to save per subject — every array produced at every stage
ARRAY_KEYS = {
    # ── Chunk 3: features ──────────────────────────────────────────────
    'gabor_raw':    'L1 Gabor features (N, gabor_dim)',
    'l2a':          'L2a broad ensemble features (N, l2a_dim)',
    'l2b':          'L2b VGG multi-layer GAP (N, 1280)',
    'X_vis_Xa':     'X_vis variant A = Gabor+L2a (N, Xa_dim)',
    'X_vis_Xb':     'X_vis variant B = Gabor+L2b (N, Xb_dim)',
    'bert_raw':     'BERT CLS embeddings (N, 768)',
}
# l3_raw: one per L3 model
# l3_wiped: one per wipe_key
# wipe_te_idx: one per wipe_key
# r2_wiped: hemi → wipe_key → (V,)
# r2_raw:   hemi → (V,)

for sid, sd in subj_data.items():
    print(f"  Saving {sid}...")
    state = {'subject': sid}

    # Fixed-key arrays
    for key, desc in ARRAY_KEYS.items():
        if key in sd:
            state[key] = sd[key]

    # L3 raw embeddings
    state['l3_raw'] = {m: sd['l3_raw'][m] for m in L3_MODELS}

    # Wipe outputs
    state['l3_wiped']    = {wk: sd['l3_wiped'][wk]    for wk in WIPE_KEYS}
    state['wipe_te_idx'] = {wk: sd['wipe_te_idx'][wk] for wk in WIPE_KEYS}
    state['wipe_meta']   = sd['wipe_meta']   # dict of dicts (serialisable)

    # Voxelwise R²
    state['r2_wiped'] = {
        hemi: {wk: sd['r2_wiped'][hemi][wk] for wk in WIPE_KEYS}
        for hemi in ['LH', 'RH']
    }
    state['r2_raw'] = {
        hemi: sd['r2_raw'][hemi]
        for hemi in ['LH', 'RH']
    }

    # fMRI (large — save separately, skip if memory-constrained)
    # Uncomment if you want to archive the raw fMRI too:
    # state['lh_fmri'] = sd['lh_fmri']
    # state['rh_fmri'] = sd['rh_fmri']

    # ROI masks (compact)
    state['lh_roi_challenge'] = sd.get('lh_roi_challenge', {})
    state['rh_roi_challenge'] = sd.get('rh_roi_challenge', {})

    pkl_path = os.path.join(ARCHIVE_DIR, f'{sid}_full_state.pkl')
    with open(pkl_path, 'wb') as f:
        pickle.dump(state, f, protocol=4)
    size_mb = os.path.getsize(pkl_path) / 1e6
    print(f"    {sid}_full_state.pkl  ({size_mb:.0f} MB)")

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 4 — CONSOLIDATED CORE (lighter pkl for quick plotting)
# Contains only R² maps + ROI aggregations — no raw embeddings
# ═══════════════════════════════════════════════════════════════════════════
print("\n── Section 4: Core summary pkl (light, for plotting) ──")

core = {
    'config':      config,
    'tables':      tables,
    'r2_maps':     {},   # sid → hemi → wipe_key → (V,) array
    'r2_raw_maps': {},   # sid → hemi → (V,) array
    'roi_masks':   {},   # sid → hemi → roi_type → mask array
    'wipe_meta':   {},   # sid → wipe_key → {alpha, r2_vis_tr, r2_vis_te}
    'te_idx':      {},   # sid → wipe_key → (N_te,) index array
}

for sid, sd in subj_data.items():
    core['r2_maps'][sid]     = {h: dict(sd['r2_wiped'][h]) for h in ['LH','RH']}
    core['r2_raw_maps'][sid] = {h: sd['r2_raw'][h]         for h in ['LH','RH']}
    core['wipe_meta'][sid]   = sd['wipe_meta']
    core['te_idx'][sid]      = {wk: sd['wipe_te_idx'][wk]  for wk in WIPE_KEYS}
    core['roi_masks'][sid]   = {
        'LH': sd.get('lh_roi_challenge', {}),
        'RH': sd.get('rh_roi_challenge', {}),
    }

core_path = os.path.join(ARCHIVE_DIR, 'core_for_plotting.pkl')
with open(core_path, 'wb') as f:
    pickle.dump(core, f, protocol=4)
size_mb = os.path.getsize(core_path) / 1e6
print(f"  Saved: core_for_plotting.pkl  ({size_mb:.0f} MB)")

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 5 — README
# ═══════════════════════════════════════════════════════════════════════════
print("\n── Section 5: README ──")

readme_lines = [
    f"NSD PIPELINE v9.1 — ARCHIVE",
    f"Generated: {TIMESTAMP}",
    f"Subjects:  {', '.join(config['subjects'])}",
    f"Wipe keys: {', '.join(WIPE_KEYS)}",
    "",
    "FILES IN THIS DIRECTORY",
    "═" * 60,
    "",
    "config_snapshot.json",
    "  All hyperparameters, subject dimensions, per-wipe-key alpha values,",
    "  and R² summary statistics. Load with json.load().",
    "",
    "tables_all.pkl",
    "  dict of DataFrames: T1 (ROI×wipe_key), T2 (vox summary),",
    "  T3 (group stats), T4 (Fig1 data), T5 (Fig2 data), T6 (flatmap).",
    "  Load with: tables = pickle.load(open('tables_all.pkl','rb'))",
    "",
    "core_for_plotting.pkl",
    "  Lightweight single-file entry point for all plotting.",
    "  Contains: config, all DataFrames, R² voxel maps, ROI masks,",
    "  wipe metadata, and test-set indices.",
    "  Load with: core = pickle.load(open('core_for_plotting.pkl','rb'))",
    "  Access:    core['r2_maps']['subj01']['LH']['bert_Xa']  → (V,) array",
    "             core['tables']['T1']  → DataFrame",
    "             core['config']['subject_dims']['subj01']  → dim info",
    "",
    "{sid}_full_state.pkl  (one per subject)",
    "  Every per-subject array: gabor_raw, l2a, l2b, X_vis_Xa/Xb,",
    "  l3_raw (bert/gpt2/clip), l3_wiped (6 wipe_keys),",
    "  wipe_te_idx, wipe_meta, r2_wiped, r2_raw, roi_masks.",
    "  fMRI arrays NOT included (large; load from arrays/ .npy files).",
    "",
    "═" * 60,
    "INDIVIDUAL .NPY FILES (in ../arrays/)",
    "═" * 60,
    "",
    "Per-subject feature arrays:",
]
for sid in config['subjects']:
    readme_lines += [
        f"  {sid}_bert_raw.npy         BERT CLS (N, 768)",
        f"  {sid}_gpt2_raw.npy         GPT-2 last-token (N, 768)",
        f"  {sid}_clip_raw.npy         CLIP-text (N, 512)",
    ]
    for wk in WIPE_KEYS:
        readme_lines += [
            f"  {sid}_{wk}_wiped.npy    Vision-wiped L3 (N_te, D)",
            f"  {sid}_{wk}_te_idx.npy   Test-set trial indices (N_te,)",
        ]
    for hemi in ['LH','RH']:
        for wk in WIPE_KEYS:
            readme_lines.append(
                f"  {sid}_{hemi}_r2_{wk}_wiped_vox.npy   R² map (V_vox,)")
        readme_lines.append(
            f"  {sid}_{hemi}_r2_raw_vox.npy             BERT-raw R² map (V_vox,)")

readme_lines += [
    "",
    "TABLE COLUMNS",
    "═" * 60,
    "",
    "T1 (ROI × wipe_key, per subject):",
    "  subject hemi wipe_key l3_model x_variant roi_type roi_name",
    "  r2_wiped_mean r2_wiped_median r2_wiped_std r2_wiped_p95",
    "  r2_raw_mean r2_raw_median delta_r2_mean frac_pos_wiped n_voxels",
    "",
    "T2 (voxelwise summary, per subject × hemi × wipe_key):",
    "  subject hemi wipe_key l3_model x_variant",
    "  n_voxels n_te_trials r2_wiped_mean r2_wiped_positive_frac",
    "  r2_raw_mean delta_r2_mean alpha_wipe r2_vis_tr r2_vis_te",
    "",
    "T3 (group stats, per wipe_key × hemi × ROI, needs N≥2):",
    "  wipe_key l3_model x_variant hemi roi_type roi_name n_subjects",
    "  r2_wiped_mean r2_wiped_sem r2_raw_mean r2_raw_sem",
    "  ratio_mean ratio_sem t_stat p_ttest q_ttest",
    "  p_signflip q_signflip sig hedges_g",
    "",
    "WIPE KEYS",
    "═" * 60,
    "  Xa = X_vis-A: Gabor + VGG19-avgpool(512) + ResNet50(2048)",
    "                + CLIP-visual(512) + EfficientNet-B0(1280)",
    "  Xb = X_vis-B: Gabor + VGG-relu3_4→GAP(256)",
    "                + VGG-relu4_4→GAP(512) + VGG-relu5_4→GAP(512)",
    "  bert_Xa  bert_Xb  gpt2_Xa  gpt2_Xb  clip_Xa  clip_Xb",
]

readme_path = os.path.join(ARCHIVE_DIR, 'README_archive.txt')
with open(readme_path, 'w') as f:
    f.write('\n'.join(readme_lines))
print(f"  Saved: README_archive.txt")

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 6 — QUICK SANITY PRINT
# ═══════════════════════════════════════════════════════════════════════════
print("\n── Section 6: Archive sanity check ──")
archive_files = sorted(os.listdir(ARCHIVE_DIR))
total_mb = sum(os.path.getsize(os.path.join(ARCHIVE_DIR,f))/1e6
               for f in archive_files)
print(f"  {len(archive_files)} files  |  {total_mb:.0f} MB total")
for fn in archive_files:
    size = os.path.getsize(os.path.join(ARCHIVE_DIR, fn)) / 1e6
    print(f"    {fn:<45s}  {size:6.1f} MB")

print(f"\nARCHIVE COMPLETE — all values saved to {ARCHIVE_DIR}")
print("""
To reload in a future session:
    import pickle, json
    core    = pickle.load(open(f'{ARCHIVE_DIR}/core_for_plotting.pkl','rb'))
    tables  = core['tables']
    config  = core['config']
    r2_maps = core['r2_maps']   # [sid][hemi][wipe_key] → (V,) array
    T1 = tables['T1']
    T3 = tables['T3_group_roi_r2']
""")

