# -*- coding: utf-8 -*-
"""Untitled87.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3L1qTsgT3XSocSWF6bOjGI7qvzr4Pkh
"""

"""
NSD PIPELINE v9 — VISUAL RESIDUALIZATION + VOXELWISE PREDICTION
=================================================================
Design:
  1. Extract full-dim Gabor (L1) and full-dim VGG19 (L2) features — no PCA anywhere.
  2. Per-subject RidgeCV to select alpha for visual→BERT regression.
  3. KFold-5 cross-validated residualization:
       BERT_wiped[te] = BERT_raw[te] - Ridge(alpha).fit(X_vis[tr], BERT[tr]).predict(X_vis[te])
     X_vis = hstack[gabor_raw, vgg_raw]  (full dimensionality, StandardScaler per fold)
  4. Voxelwise prediction: Ridge KFold-5 from BERT_wiped → fMRI.
     R²_vox = variance in brain response explained purely by non-visual language content.
  5. ROI aggregation + tables. No LEACE, no NLI, no RSA, no multi-model loops.

Inputs:
  SUBJ_ZIPS  : list of per-subject zips (lh/rh fMRI npy, training PNGs, ROI npy masks)
  STIM_PATH  : nsd_stim_info_merged.pkl  (NSD-id → cocoId + cocoSplit)
  COCO annotations downloaded automatically from images.cocodataset.org

Outputs (OUT_DIR):
  tables/  : T1_roi_r2.csv, T2_voxelwise_r2_summary.csv
  arrays/  : {sid}_{hemi}_r2_wiped_vox.npy, {sid}_{hemi}_r2_raw_vox.npy
  figures/ : r2_roi_barplot.png
"""

# ════════════════════════════════════════════════════════════════════════════
# CHUNK 1 — SETUP / PACKAGES / CONFIG / COCO
# ════════════════════════════════════════════════════════════════════════════
import subprocess, sys, os, time, io, re, json, pickle, warnings

for pkg in ['nilearn', 'transformers', 'requests']:
    subprocess.run([sys.executable, '-m', 'pip', 'install', pkg, '-q'], check=False)

import numpy as np
import pandas as pd
import zipfile, torch, cv2, requests
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
from PIL import Image
from torchvision import models, transforms
from transformers import BertTokenizer, BertModel
from scipy import stats
from sklearn.linear_model import Ridge, RidgeCV
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from joblib import Parallel, delayed
import statsmodels.stats.multitest as smm

warnings.filterwarnings('ignore')
t0 = time.time()
def elapsed(): return f"[{time.time()-t0:5.0f}s]"

# ═══════════════ EDIT CONFIG BELOW ═══════════════
SUBJ_ZIPS = [
    '/content/drive/MyDrive/nsd/subj01.zip',
    '/content/drive/MyDrive/nsd/subj02.zip',
    '/content/drive/MyDrive/nsd/subj03.zip',
    '/content/drive/MyDrive/nsd/subj04.zip',
    '/content/drive/MyDrive/nsd/subj05.zip',
    '/content/drive/MyDrive/nsd/subj06.zip',
    '/content/drive/MyDrive/nsd/subj07.zip',
    '/content/drive/MyDrive/nsd/subj08.zip',
]
STIM_PATH = '/content/drive/MyDrive/nsd_stim_info_merged.pkl'
OUT_DIR   = '/content/drive/MyDrive/nsd_results_v9'
# ══════════════════════════════════════════════════

N_JOBS        = 12
IMG_BATCH     = 64
BERT_BATCH    = 128
CMI_FOLDS     = 5
WIPE_FOLDS    = 5
RIDGE_ALPHA   = 1e4        # voxelwise prediction alpha (fixed; dimensionality is low post-wipe)
RIDGECV_ALPHAS = np.logspace(1, 6, 12)   # search grid for residualization alpha
RANDOM_STATE  = 42
ALPHA_SIG     = 0.05
VOXEL_BLOCK   = 5000

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
SUBJ_ZIPS = [p for p in SUBJ_ZIPS if os.path.exists(p)]
assert len(SUBJ_ZIPS) >= 1, "No subject zips found"
N_SUBJ = len(SUBJ_ZIPS)
print(f"{elapsed()} Device:{DEVICE} | CPUs:{N_JOBS} | Subjects:{N_SUBJ}")

os.makedirs(OUT_DIR, exist_ok=True)
TABLES_DIR = os.path.join(OUT_DIR, 'tables');  os.makedirs(TABLES_DIR, exist_ok=True)
FIGS_DIR   = os.path.join(OUT_DIR, 'figures'); os.makedirs(FIGS_DIR,   exist_ok=True)
ARRAYS_DIR = os.path.join(OUT_DIR, 'arrays');  os.makedirs(ARRAYS_DIR, exist_ok=True)

# ROI definitions (unchanged from v8)
ROI_TYPES  = ['prf-visualrois', 'floc-bodies', 'floc-faces', 'floc-places', 'floc-words', 'streams']
ROI_LABELS = {
    'prf-visualrois': {1:'V1v',2:'V1d',3:'V2v',4:'V2d',5:'V3v',6:'V3d',7:'hV4'},
    'floc-bodies':    {1:'EBA',2:'FBA-1',3:'FBA-2',4:'mTL-bodies'},
    'floc-faces':     {1:'OFA',2:'FFA-1',3:'FFA-2',4:'mTL-faces',5:'aTL-faces'},
    'floc-places':    {1:'OPA',2:'PPA',3:'RSC'},
    'floc-words':     {1:'OWFA',2:'VWFA-1',3:'VWFA-2',4:'mfs-words',5:'mTL-words'},
    'streams':        {1:'early',2:'midventral',3:'midlateral',4:'midparietal',
                       5:'ventral',6:'lateral',7:'parietal'},
}
ROI_COLORS = {
    'prf-visualrois':'#FF6B6B','floc-bodies':'#4ECDC4','floc-faces':'#FFE66D',
    'floc-places':'#A8E6CF','floc-words':'#C3A6FF','streams':'#FF8C42',
}

np.random.seed(RANDOM_STATE); torch.manual_seed(RANDOM_STATE)

# ─── COCO annotations ────────────────────────────────────────────────────────
print(f"\n{elapsed()} COCO annotations...")
COCO_CACHE = '/tmp/nsd_coco_v9.pkl'
if os.path.exists(COCO_CACHE):
    with open(COCO_CACHE, 'rb') as _f: _cc = pickle.load(_f)
    std_tr      = _cc['std_tr'];      std_va      = _cc['std_va']
    caps_list_tr= _cc['caps_list_tr']; caps_list_va= _cc['caps_list_va']
    print("  COCO: loaded from cache")
else:
    ann_url = "http://images.cocodataset.org/annotations/annotations_trainval2017.zip"
    print(f"  Downloading {ann_url} ...")
    resp = requests.get(ann_url, stream=True, timeout=600); resp.raise_for_status()
    print(f"  Downloaded ({len(resp.content)/1e6:.0f} MB) — parsing...")
    with zipfile.ZipFile(io.BytesIO(resp.content)) as za:
        with za.open('annotations/instances_train2017.json') as f: _inst_tr = json.load(f)
        with za.open('annotations/instances_val2017.json')   as f: _inst_va = json.load(f)
        with za.open('annotations/captions_train2017.json')  as f: _caps_tr = json.load(f)
        with za.open('annotations/captions_val2017.json')    as f: _caps_va = json.load(f)
    del resp

    def _parse_coco(inst, cap):
        cats    = {c['id']: c for c in inst['categories']}
        std_map = {}
        for ann in inst['annotations']:
            iid, cid = ann['image_id'], ann['category_id']
            if cid not in cats: continue
            frag = f"{cats[cid]['name']} {cats[cid]['supercategory']}"
            std_map.setdefault(iid, {'c': [], 'a': []})['c'].append(frag)
        cap_list = {}
        for ann in cap['annotations']:
            iid = ann['image_id']
            std_map.setdefault(iid, {'c': [], 'a': []})['a'].append(ann['caption'])
            cap_list.setdefault(iid, []).append(ann['caption'])
        std_text = {iid: ' . '.join(d['c'] + d['a']) or 'image' for iid, d in std_map.items()}
        return std_text, cap_list

    std_tr, caps_list_tr = _parse_coco(_inst_tr, _caps_tr)
    std_va, caps_list_va = _parse_coco(_inst_va, _caps_va)
    del _inst_tr, _inst_va, _caps_tr, _caps_va
    with open(COCO_CACHE, 'wb') as _f:
        pickle.dump({'std_tr': std_tr, 'std_va': std_va,
                     'caps_list_tr': caps_list_tr, 'caps_list_va': caps_list_va}, _f)
    print(f"  COCO cached {elapsed()}")

with open(STIM_PATH, 'rb') as f: stim_info = pickle.load(f, encoding='latin1')
if isinstance(stim_info, dict): stim_info = pd.DataFrame(stim_info)

print(f"CHUNK 1 done {elapsed()}")


# ════════════════════════════════════════════════════════════════════════════
# CHUNK 2 — PER-SUBJECT fMRI + IMAGE LOADING
# ════════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}\nCHUNK 2: fMRI + IMAGE LOADING\n{'='*70}")
subj_data = {}

for zip_path in SUBJ_ZIPS:
    # Derive subject ID from the zip filename — authoritative, index-independent.
    # subj01.zip → 'subj01', subj03.zip → 'subj03', etc.
    sid = os.path.splitext(os.path.basename(zip_path))[0]   # e.g. 'subj01'
    print(f"\n-- {sid} -- {zip_path}")

    with zipfile.ZipFile(zip_path, 'r') as z:
        all_files = z.namelist()

        # fMRI
        with z.open(next(f for f in all_files if 'lh_training_fmri.npy' in f)) as f:
            lh_fmri = np.load(f)
        with z.open(next(f for f in all_files if 'rh_training_fmri.npy' in f)) as f:
            rh_fmri = np.load(f)

        # Training images — sorted by trial index
        training_images = sorted(
            [f for f in all_files if 'training_split' in f and f.endswith('.png')],
            key=lambda x: int(x.split('train-')[1].split('_')[0]))
        N = len(training_images)

        # NSD image IDs (index into stim_info)
        nsd_ids = np.array([
            int(os.path.basename(p).split('nsd-')[1].split('.')[0])
            for p in training_images])
        print(f"  LH:{lh_fmri.shape}  RH:{rh_fmri.shape}  N:{N}")

        # Cache raw image bytes in memory (avoids re-opening zip later)
        print("  Caching image bytes...")
        img_bytes = []
        for p in training_images:
            with z.open(p) as f: img_bytes.append(f.read())

        # ROI masks — challenge space only (used for aggregation)
        lh_roi_challenge, rh_roi_challenge = {}, {}
        for rt in ROI_TYPES:
            for hemi, chd in [('lh', lh_roi_challenge), ('rh', rh_roi_challenge)]:
                ch = [f for f in all_files
                      if f'{hemi}.{rt}_challenge_space' in f and f.endswith('.npy')]
                if ch:
                    with z.open(ch[0]) as f: chd[rt] = np.load(f)

    # Build voxel→ROI index maps
    def _build_vox_roi_map(roi_ch, hlbl):
        vmap = {}
        for rt in ROI_TYPES:
            if rt not in roi_ch: continue
            for lbl, rname in ROI_LABELS.get(rt, {}).items():
                idx = np.where(roi_ch[rt] == lbl)[0]
                if len(idx) > 0: vmap[f"{rname}_{hlbl}"] = idx
        return vmap

    lh_vox_roi = _build_vox_roi_map(lh_roi_challenge, 'LH')
    rh_vox_roi = _build_vox_roi_map(rh_roi_challenge, 'RH')
    print(f"  LH ROIs:{len(lh_vox_roi)}  RH ROIs:{len(rh_vox_roi)}")

    # Map each trial to its COCO captions via stim_info
    # stim_info.iloc[nsd_id] gives cocoId and cocoSplit
    trial_texts = []
    for nid in nsd_ids:
        row   = stim_info.iloc[nid]
        cid   = int(row['cocoId'])
        split = str(row.get('cocoSplit', 'train2017'))
        if split == 'train2017':
            trial_texts.append(std_tr.get(cid, 'image'))
        else:
            trial_texts.append(std_va.get(cid, 'image'))

    subj_data[sid] = {
        'lh_fmri': lh_fmri, 'rh_fmri': rh_fmri,
        'img_bytes': img_bytes,
        'nsd_ids': nsd_ids, 'N': N,
        'trial_texts': trial_texts,
        'lh_roi_challenge': lh_roi_challenge,
        'rh_roi_challenge': rh_roi_challenge,
        'lh_vox_roi': lh_vox_roi,
        'rh_vox_roi': rh_vox_roi,
    }

print(f"\nCHUNK 2 done — {N_SUBJ} subjects {elapsed()}")


# ════════════════════════════════════════════════════════════════════════════
# CHUNK 3 — FEATURE EXTRACTION (full-dim Gabor L1, full-dim VGG19 L2, BERT L3)
# No PCA. No dimensionality reduction of any kind on visual features.
# ════════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}\nCHUNK 3: FEATURE EXTRACTION (full-dim L1 + L2 + BERT)\n{'='*70}")

# ── L1: Gabor filterbank ──────────────────────────────────────────────────
def _make_gabors(ksize=21, n_or=8, n_sc=4):
    gs = []
    for sc in range(n_sc):
        sig, lam = 2**sc, 2**(sc+1)
        for o in range(n_or):
            k = cv2.getGaborKernel((ksize, ksize), sig, o*np.pi/n_or, lam, 0.5, 0)
            k /= np.abs(k).sum() + 1e-10
            gs.append(k)
    return gs

_GF = _make_gabors()

def _extract_l1(ib):
    """
    Full Gabor + colour histogram + edge features.
    Output dim = n_filters × n_scales × 2 stats  +  colour patches  +  edge cells
    Fixed for all images; exact dim printed at runtime.
    """
    img  = Image.open(io.BytesIO(ib)).convert('RGB')
    a    = np.array(img)
    gray = cv2.cvtColor(a, cv2.COLOR_RGB2GRAY).astype(np.float32)
    h, w = gray.shape
    feats = []

    # Gabor responses — mean + std in spatial grid (1×1, 2×2, 4×4)
    for gf in _GF:
        r = np.abs(cv2.filter2D(gray, cv2.CV_32F, gf))
        for lv in range(3):
            g = 2**lv
            for ri in range(g):
                for ci_ in range(g):
                    cell = r[ri*h//g:(ri+1)*h//g, ci_*w//g:(ci_+1)*w//g]
                    feats += [np.mean(cell), np.std(cell)]

    # HSV colour histograms in 2×2 spatial grid (16 bins × 3 channels × 4 patches)
    hsv = cv2.cvtColor(a, cv2.COLOR_RGB2HSV).astype(np.float32)
    for qi in range(2):
        for qj in range(2):
            patch = hsv[qi*h//2:(qi+1)*h//2, qj*w//2:(qj+1)*w//2]
            for ch in range(3):
                feats.extend(cv2.calcHist([patch], [ch], None, [16], [0, 256]).flatten())

    # Canny edge density in 2×2 grid, 3 threshold pairs
    for lo, hi in [(50, 100), (100, 200), (150, 300)]:
        edges = cv2.Canny(gray.astype(np.uint8), lo, hi)
        for qi in range(2):
            for qj in range(2):
                feats.append(
                    np.mean(edges[qi*h//2:(qi+1)*h//2, qj*w//2:(qj+1)*w//2] > 0))

    return np.array(feats, dtype=np.float32)

# ── L2: VGG19 full avgpool output (512-dim) ───────────────────────────────
class _VGGFeat(torch.nn.Module):
    def __init__(self, m):
        super().__init__()
        self.f = m.features
        self.p = m.avgpool
    def forward(self, x):
        return self.p(self.f(x)).view(x.size(0), -1)

_img_tf = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

_vgg_net = _VGGFeat(
    models.vgg19(weights=models.VGG19_Weights.IMAGENET1K_V1)
).to(DEVICE).eval()

def _extract_l2(img_bytes_list, N_s):
    """Full 512-dim VGG19 avgpool features for all N_s images."""
    parts = []
    for bi in range(0, N_s, IMG_BATCH):
        batch = torch.stack([
            _img_tf(Image.open(io.BytesIO(img_bytes_list[i])).convert('RGB'))
            for i in range(bi, min(bi + IMG_BATCH, N_s))
        ]).to(DEVICE)
        with torch.no_grad():
            parts.append(_vgg_net(batch).cpu().numpy())
    return np.vstack(parts).astype(np.float32)   # (N, 512)

# ── L3: BERT CLS embeddings (768-dim) ─────────────────────────────────────
_bert_tok = BertTokenizer.from_pretrained('bert-base-uncased')
_bert_mdl = BertModel.from_pretrained('bert-base-uncased').to(DEVICE).eval()

def _encode_bert(texts):
    parts = []
    for bi in range(0, len(texts), BERT_BATCH):
        enc = _bert_tok(
            texts[bi:bi+BERT_BATCH],
            padding=True, truncation=True, max_length=512, return_tensors='pt')
        with torch.no_grad():
            out = _bert_mdl(**{k: v.to(DEVICE) for k, v in enc.items()})
        parts.append(out.last_hidden_state[:, 0, :].cpu().numpy())
    return np.vstack(parts).astype(np.float32)   # (N, 768)

# ── Per-subject extraction ────────────────────────────────────────────────
for sid, sd in subj_data.items():
    print(f"\n-- Features: {sid} --")
    N_s       = sd['N']
    img_bytes = sd['img_bytes']

    # L1: full Gabor (parallel across images)
    print(f"  L1 Gabor (N={N_s})...")
    gabor_raw = np.array(
        Parallel(n_jobs=N_JOBS)(delayed(_extract_l1)(b) for b in img_bytes),
        dtype=np.float32)
    print(f"  Gabor dim: {gabor_raw.shape[1]}")   # log exact dim
    sd['gabor_raw'] = gabor_raw

    # L2: full VGG19 512-dim
    print(f"  L2 VGG19 (N={N_s})...")
    vgg_raw = _extract_l2(img_bytes, N_s)
    print(f"  VGG dim: {vgg_raw.shape[1]}")        # always 512
    sd['vgg_raw'] = vgg_raw

    # L3: BERT CLS 768-dim
    print(f"  L3 BERT (N={N_s})...")
    bert_raw = _encode_bert(sd['trial_texts'])
    print(f"  BERT dim: {bert_raw.shape[1]}")       # always 768
    sd['bert_raw'] = bert_raw

    # Build combined visual feature matrix (no reduction)
    # X_vis shape: (N, gabor_dim + 512)
    sd['X_vis'] = np.hstack([gabor_raw, vgg_raw]).astype(np.float32)
    print(f"  X_vis combined dim: {sd['X_vis'].shape[1]}  {elapsed()}")

del _vgg_net
torch.cuda.empty_cache() if torch.cuda.is_available() else None
print(f"\nCHUNK 3 done {elapsed()}")


# ════════════════════════════════════════════════════════════════════════════
# CHUNK 4 — VISUAL RESIDUALIZATION OF BERT
#
# Goal: remove all BERT variance that is linearly predictable from visual features.
#
# Method:
#   1. RidgeCV on full training data to select the best alpha from RIDGECV_ALPHAS.
#      This gives one alpha per subject — conservative, data-driven.
#   2. KFold-5 cross-validated residualization with that alpha:
#        - StandardScaler fit on train fold of X_vis, applied to test fold
#        - Ridge(alpha).fit(X_vis_tr_scaled, BERT_tr)
#        - BERT_wiped[te] = BERT_raw[te] - Ridge.predict(X_vis_te_scaled)
#      Out-of-fold residuals prevent in-sample overfitting from artificially
#      inflating the amount of BERT signal removed.
#
# Result: BERT_wiped contains only BERT variance orthogonal to the full
#         linear span of [Gabor | VGG19]. This is the quantity predicted
#         downstream to voxelwise fMRI.
# ════════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}\nCHUNK 4: VISUAL RESIDUALIZATION OF BERT\n{'='*70}")

def wipe_visual_subspace(X_vis, bert_raw, alphas=RIDGECV_ALPHAS,
                          n_folds=WIPE_FOLDS, seed=RANDOM_STATE):
    """
    Cross-validated projection of bert_raw onto the null space of X_vis.

    Parameters
    ----------
    X_vis    : (N, V_dim) — full-dim visual features [Gabor | VGG19], unscaled
    bert_raw : (N, 768)  — raw BERT CLS embeddings
    alphas   : search grid for RidgeCV (fit once on full data to choose alpha)
    n_folds  : number of CV folds for out-of-fold residuals

    Returns
    -------
    bert_wiped : (N, 768) — BERT with visual component subtracted, out-of-fold
    alpha_best : float    — alpha selected by RidgeCV
    r2_vis     : float    — mean R² of visual→BERT regression (diagnostic)
    """
    N = bert_raw.shape[0]

    # Step 1: select alpha via RidgeCV on full data
    # Fit on full standardized X_vis; score = mean R² across 768 BERT dims
    sc_full = StandardScaler().fit(X_vis)
    X_sc    = sc_full.transform(X_vis)
    rcv     = RidgeCV(alphas=alphas, fit_intercept=True,
                      scoring='r2', cv=5).fit(X_sc, bert_raw)
    alpha_best = float(rcv.alpha_)
    # Diagnostic: mean R² across BERT dims
    bert_pred_full = rcv.predict(X_sc)
    r2_vis = float(np.mean([
        r2_score(bert_raw[:, d], bert_pred_full[:, d])
        for d in range(bert_raw.shape[1])
    ]))
    print(f"  RidgeCV selected alpha={alpha_best:.1e}  |  "
          f"mean R²(visual→BERT)={r2_vis:.4f}")

    # Step 2: KFold cross-validated residuals
    bert_wiped = np.zeros_like(bert_raw)
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=seed)
    for fold, (tr, te) in enumerate(kf.split(np.arange(N))):
        sc_fold = StandardScaler().fit(X_vis[tr])          # fit scaler on train fold only
        X_tr_sc = sc_fold.transform(X_vis[tr])
        X_te_sc = sc_fold.transform(X_vis[te])
        rid     = Ridge(alpha=alpha_best, fit_intercept=True).fit(X_tr_sc, bert_raw[tr])
        bert_wiped[te] = bert_raw[te] - rid.predict(X_te_sc)
        fold_r2 = float(np.mean([
            r2_score(bert_raw[te, d], rid.predict(X_te_sc)[:, d])
            for d in range(bert_raw.shape[1])
        ]))
        print(f"    fold {fold+1}/{n_folds}  te_size={len(te)}  "
              f"R²_vis_on_fold={fold_r2:.4f}")

    return bert_wiped.astype(np.float32), alpha_best, r2_vis

for sid, sd in subj_data.items():
    print(f"\n-- Residualization: {sid} --")
    bert_wiped, alpha_best, r2_vis = wipe_visual_subspace(
        sd['X_vis'], sd['bert_raw'])
    sd['bert_wiped']  = bert_wiped
    sd['alpha_wipe']  = alpha_best
    sd['r2_vis_bert'] = r2_vis

    # Sanity check: variance explained by wiped vs raw BERT
    var_raw   = float(np.var(sd['bert_raw']))
    var_wiped = float(np.var(bert_wiped))
    print(f"  Variance retained after wipe: {var_wiped/var_raw*100:.1f}%  "
          f"({var_wiped:.4f} / {var_raw:.4f})")

    # Save wiped BERT
    np.save(os.path.join(ARRAYS_DIR, f'{sid}_bert_wiped.npy'), bert_wiped)
    np.save(os.path.join(ARRAYS_DIR, f'{sid}_bert_raw.npy'),   sd['bert_raw'])

print(f"\nCHUNK 4 done {elapsed()}")


# ════════════════════════════════════════════════════════════════════════════
# CHUNK 5 — VOXELWISE R² PREDICTION
#
# Predict fMRI voxel responses from BERT_wiped (and BERT_raw for comparison).
# Method: KFold-5 Ridge regression, compute R² per voxel on held-out folds.
#
# R²_wiped > 0  → voxel encodes linguistic content not explained by vision alone.
# ΔR² = R²_wiped - R²_raw < 0 by construction; magnitude = cost of wiping.
# ════════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}\nCHUNK 5: VOXELWISE R² PREDICTION\n{'='*70}")

def _r2_batch(Y_block, X, alpha=RIDGE_ALPHA, n_splits=CMI_FOLDS):
    """
    Cross-validated R² for each voxel in Y_block given features X.
    Returns shape (n_voxels,).
    """
    N_  = Y_block.shape[0]
    kf  = KFold(n_splits=n_splits, shuffle=True, random_state=RANDOM_STATE)
    ss_res = np.zeros(Y_block.shape[1], dtype=np.float64)
    ss_tot = np.zeros(Y_block.shape[1], dtype=np.float64)
    for tr, te in kf.split(np.arange(N_)):
        sc   = StandardScaler().fit(X[tr])
        rid  = Ridge(alpha=alpha, fit_intercept=True).fit(sc.transform(X[tr]), Y_block[tr])
        pred = rid.predict(sc.transform(X[te]))
        res  = Y_block[te] - pred
        tot  = Y_block[te] - Y_block[te].mean(0, keepdims=True)
        ss_res += (res**2).sum(0)
        ss_tot += (tot**2).sum(0)
    r2 = 1.0 - ss_res / (ss_tot + 1e-12)
    return r2.astype(np.float32)

def _run_voxelwise_r2(fmri, X, desc=''):
    """Parallel voxelwise R² across VOXEL_BLOCK-sized chunks."""
    V       = fmri.shape[1]
    blocks  = [(i, min(i + VOXEL_BLOCK, V)) for i in range(0, V, VOXEL_BLOCK)]
    print(f"  {desc}: {V} vox | {len(blocks)} blocks {elapsed()}")
    results = Parallel(n_jobs=N_JOBS, prefer='threads')(
        delayed(_r2_batch)(fmri[:, s:e], X) for s, e in blocks)
    out = np.concatenate(results)
    print(f"  {desc} done | mean_R²={out.mean():.5f} max_R²={out.max():.5f} {elapsed()}")
    return out

for sid, sd in subj_data.items():
    print(f"\n{'='*50}\nVoxelwise R²: {sid}\n{'='*50}")
    bert_raw   = sd['bert_raw']
    bert_wiped = sd['bert_wiped']

    for hemi, fmri_h in [('LH', sd['lh_fmri']), ('RH', sd['rh_fmri'])]:
        print(f"\n  == {hemi} ({fmri_h.shape[1]} voxels) ==")

        # R² from BERT_wiped (primary quantity of interest)
        r2_wiped = _run_voxelwise_r2(fmri_h, bert_wiped,
                                      desc=f'{sid}/{hemi}/BERT_wiped')
        # R² from BERT_raw (comparison baseline)
        r2_raw   = _run_voxelwise_r2(fmri_h, bert_raw,
                                      desc=f'{sid}/{hemi}/BERT_raw')

        delta_r2 = r2_wiped - r2_raw   # negative: wiping removes some signal
        print(f"  ΔR² (wiped−raw): mean={delta_r2.mean():.5f}  "
              f"median={np.median(delta_r2):.5f}")

        sd[f'{hemi}_r2_wiped'] = r2_wiped
        sd[f'{hemi}_r2_raw']   = r2_raw
        sd[f'{hemi}_delta_r2'] = delta_r2

        np.save(os.path.join(ARRAYS_DIR, f'{sid}_{hemi}_r2_wiped_vox.npy'), r2_wiped)
        np.save(os.path.join(ARRAYS_DIR, f'{sid}_{hemi}_r2_raw_vox.npy'),   r2_raw)
        np.save(os.path.join(ARRAYS_DIR, f'{sid}_{hemi}_delta_r2_vox.npy'), delta_r2)

print(f"\nCHUNK 5 done {elapsed()}")


# ════════════════════════════════════════════════════════════════════════════
# CHUNK 6 — ROI AGGREGATION + TABLES + FIGURES
# ════════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}\nCHUNK 6: ROI AGGREGATION\n{'='*70}")

def _roi_r2_stats(vidx, r2_wiped, r2_raw):
    w = r2_wiped[vidx]; r = r2_raw[vidx]; d = w - r
    return {
        'r2_wiped_mean':   float(w.mean()),
        'r2_wiped_median': float(np.median(w)),
        'r2_wiped_std':    float(w.std()),
        'r2_wiped_p95':    float(np.percentile(w, 95)),
        'r2_raw_mean':     float(r.mean()),
        'r2_raw_median':   float(np.median(r)),
        'delta_r2_mean':   float(d.mean()),
        'frac_pos_wiped':  float((w > 0).mean()),  # fraction of voxels with R²_wiped > 0
        'n_voxels':        len(vidx),
    }

t1_rows = []
for sid, sd in subj_data.items():
    for hemi, roi_ch_dict in [('LH', sd['lh_roi_challenge']),
                               ('RH', sd['rh_roi_challenge'])]:
        r2_w = sd[f'{hemi}_r2_wiped']
        r2_r = sd[f'{hemi}_r2_raw']
        for rt in ROI_TYPES:
            if rt not in roi_ch_dict: continue
            ch_mask = roi_ch_dict[rt]
            for lbl in np.unique(ch_mask[ch_mask != 0]):
                lbl    = int(lbl)
                rname  = ROI_LABELS.get(rt, {}).get(lbl, f'R{lbl}')
                vidx   = np.where(ch_mask == lbl)[0]
                if len(vidx) < 5: continue
                stats_d = _roi_r2_stats(vidx, r2_w, r2_r)
                stats_d.update({'subject': sid, 'hemi': hemi,
                                 'roi_type': rt, 'roi_name': rname})
                t1_rows.append(stats_d)

T1 = pd.DataFrame(t1_rows)
T1.to_csv(os.path.join(TABLES_DIR, 'T1_roi_r2.csv'), index=False)

# Per-voxel summary table
vox_rows = []
for sid, sd in subj_data.items():
    for hemi in ['LH', 'RH']:
        w = sd[f'{hemi}_r2_wiped']; r = sd[f'{hemi}_r2_raw']
        V = len(w)
        vox_rows.append({
            'subject': sid, 'hemi': hemi,
            'n_voxels': V,
            'r2_wiped_mean': float(w.mean()),
            'r2_wiped_positive_frac': float((w > 0).mean()),
            'r2_raw_mean': float(r.mean()),
            'delta_r2_mean': float((w - r).mean()),
            'alpha_wipe': sd['alpha_wipe'],
            'r2_vis_bert': sd['r2_vis_bert'],
        })
T2 = pd.DataFrame(vox_rows)
T2.to_csv(os.path.join(TABLES_DIR, 'T2_voxelwise_r2_summary.csv'), index=False)

print(f"  T1 (ROI): {len(T1)} rows")
print(f"  T2 (vox summary): {len(T2)} rows")
print(T2[['subject','hemi','r2_wiped_mean','r2_wiped_positive_frac',
          'r2_raw_mean','delta_r2_mean','alpha_wipe']].to_string(index=False))

# ── Figure: R²_wiped by ROI ───────────────────────────────────────────────
if len(T1) > 0:
    fig, axes = plt.subplots(1, 2, figsize=(18, 6), sharey=False)
    for ax, hemi in zip(axes, ['LH', 'RH']):
        df_h = T1[T1['hemi'] == hemi].copy()
        if df_h.empty: ax.set_visible(False); continue
        df_h = df_h.sort_values('r2_wiped_mean', ascending=False)
        colors = [ROI_COLORS.get(rt, '#888888') for rt in df_h['roi_type']]
        bars = ax.bar(range(len(df_h)), df_h['r2_wiped_mean'], color=colors,
                      edgecolor='white', linewidth=0.5)
        ax.errorbar(range(len(df_h)), df_h['r2_wiped_mean'],
                    yerr=df_h['r2_wiped_std'] / np.sqrt(df_h['n_voxels']),
                    fmt='none', color='black', capsize=2, linewidth=0.8)
        ax.set_xticks(range(len(df_h)))
        ax.set_xticklabels(df_h['roi_name'], rotation=45, ha='right', fontsize=8)
        ax.axhline(0, color='black', linewidth=0.5, linestyle='--')
        ax.set_title(f'{hemi} — R² (BERT wiped of visual)', fontsize=11)
        ax.set_ylabel('Mean cross-validated R²')
        # legend for ROI types
        seen = set()
        patches = []
        for rt, col in ROI_COLORS.items():
            if rt in df_h['roi_type'].values and rt not in seen:
                patches.append(plt.Rectangle((0,0),1,1, fc=col, label=rt))
                seen.add(rt)
        ax.legend(handles=patches, fontsize=7, loc='upper right')
    plt.suptitle('Voxelwise R² from BERT wiped of visual features\n'
                 '(non-visual linguistic content → brain)', fontsize=12)
    plt.tight_layout()
    fig_path = os.path.join(FIGS_DIR, 'r2_roi_barplot.png')
    plt.savefig(fig_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"\n  Saved figure: {fig_path}")

print(f"\nCHUNK 6 done {elapsed()}")


# ════════════════════════════════════════════════════════════════════════════
# CHUNK 7 — GROUP AGGREGATION + PUBLICATION FIGURES
#
# Stats: per-ROI random-effects t-test (subjects as unit), Hedge's g,
#        BH-FDR across all ROI × hemi. Semantic independence ratio =
#        r2_wiped / r2_raw (how much linguistic signal survives vision wipe).
#
# Figures (all 300 DPI, PDF):
#   Fig 1 — Regional dissociation:
#            Left panel:  R²_wiped per ROI, ROI-type grouped,
#                         LH + RH as paired bars, SEM across subjects,
#                         FDR stars, early visual as negative control at bottom
#            Right panel: Semantic independence ratio same layout,
#                         individual subject dots overlaid on group bars
#   Fig 2 — Subject-level replication:
#            Paired lines per subject connecting EBA / ventral stream / V1v
#            (within-subject dissociation visible at a glance)
#   Fig 3 — Cortical flatmap:
#            Group-average R²_wiped on fsaverage surface per hemisphere.
#            Mean weighted by n_voxels per subject so subjects with more
#            cortex don't dominate. Lateral + ventral views.
#
# CSVs:
#   T3_group_roi_r2.csv       — group stats all ROIs (random-effects)
#   T4_fig1_plot_data.csv     — Fig 1 underlying data (one row per ROI×hemi)
#   T5_fig2_subject_dots.csv  — Fig 2 per-subject 3 key ROIs
#   T6_flatmap_group.csv      — per-vertex group R²_wiped (LH + RH stacked)
# ════════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}\nCHUNK 7: GROUP AGGREGATION + PUBLICATION FIGURES (N={N_SUBJ})\n{'='*70}")

from matplotlib.lines import Line2D
from matplotlib.patches import Patch
import matplotlib.gridspec as gridspec

DPI = 300

# ── ROI colour palette ────────────────────────────────────────────────────
_ROI_PAL = {
    'prf-visualrois': '#B0413E',   # red   — early visual (negative control)
    'floc-bodies':    '#2B8C7E',   # teal  — body-selective
    'floc-faces':     '#E8A838',   # amber — face-selective
    'floc-places':    '#4A7FB5',   # blue  — place-selective
    'floc-words':     '#7B52AB',   # purple — word-selective
    'streams':        '#5A8A5A',   # green — streams
}
# Display order: body/face/place/word/streams (high→low expected signal),
# early visual last as the negative control.
_ROI_TYPE_ORDER = ['floc-bodies','floc-faces','floc-places','floc-words',
                   'streams','prf-visualrois']
_ROI_TYPE_LABEL = {
    'prf-visualrois': 'Visual (V1–V4)',
    'floc-bodies':    'Body-selective',
    'floc-faces':     'Face-selective',
    'floc-places':    'Place-selective',
    'floc-words':     'Word-selective',
    'streams':        'Streams',
}

def _hedges_g(vals):
    n = len(vals); m = float(np.mean(vals)); s = float(np.std(vals, ddof=1))
    if s < 1e-12 or n < 2: return 0.0
    return (m / s) * (1.0 - 3.0 / (4.0 * (n - 1) - 1))

# ── Build group table (random-effects: subjects as unit) ─────────────────
# SEM is std across subjects / sqrt(N_subjects), not within-ROI voxel SEM.
grp_rows = []
roi_keys = T1[['hemi','roi_type','roi_name']].drop_duplicates().values.tolist()
for hemi, rt, rname in roi_keys:
    sub_df = T1[(T1['hemi']==hemi) & (T1['roi_name']==rname)]
    sub_w  = sub_df['r2_wiped_mean'].values   # one value per subject
    sub_r  = sub_df['r2_raw_mean'].values
    n      = len(sub_w)
    if n < 2: continue
    m_w    = float(sub_w.mean())
    sem_w  = float(sub_w.std(ddof=1) / np.sqrt(n))   # SEM across subjects
    m_r    = float(sub_r.mean())
    sem_r  = float(sub_r.std(ddof=1) / np.sqrt(n))
    t, p   = stats.ttest_1samp(sub_w, 0.0)
    g      = _hedges_g(sub_w)
    ratios      = sub_w / np.maximum(sub_r, 1e-8)
    ratio_mean  = float(ratios.mean())
    ratio_sem   = float(ratios.std(ddof=1) / np.sqrt(n))
    grp_rows.append({
        'hemi': hemi, 'roi_type': rt, 'roi_name': rname,
        'n_subjects':    n,
        'r2_wiped_mean': m_w,        'r2_wiped_sem': sem_w,
        'r2_raw_mean':   m_r,        'r2_raw_sem':   sem_r,
        'ratio_mean':    ratio_mean, 'ratio_sem':    ratio_sem,
        't_stat': float(t), 'p_val': float(p), 'hedges_g': g,
    })

T_group = pd.DataFrame(grp_rows)
_, q_vals, _, _ = smm.multipletests(T_group['p_val'].values, alpha=0.05, method='fdr_bh')
T_group['q_fdr'] = q_vals
T_group['sig']   = T_group['q_fdr'] < 0.05
T_group.to_csv(os.path.join(TABLES_DIR, 'T3_group_roi_r2.csv'), index=False)
n_sig = T_group['sig'].sum()
print(f"  Group table: {len(T_group)} ROIs  |  FDR sig (q<0.05): {n_sig}")
print(T_group.sort_values('r2_wiped_mean', ascending=False)
      [['hemi','roi_name','r2_wiped_mean','r2_wiped_sem','ratio_mean',
        't_stat','p_val','q_fdr','hedges_g','sig']].head(20).to_string(index=False))

# ══════════════════════════════════════════════════════════════════════════
# FIGURE 1 — Regional dissociation
#
# Layout: ONE figure, 2 panels side by side.
#   Left  — R²_wiped bar chart, LH and RH as side-by-side paired bars per ROI,
#            ROIs grouped by functional type in the order:
#            Body > Face > Place > Word > Streams > Visual (negative control)
#            Within each group sorted by LH mean descending.
#            Error bars = SEM across subjects. FDR stars above bars.
#   Right — Semantic independence ratio (R²_wiped / R²_raw), same ROI/group
#            ordering. Individual subject dots overlaid on group mean bars.
# ══════════════════════════════════════════════════════════════════════════
print(f"\n  Generating Figure 1 {elapsed()}")

def _build_fig1_order(tg):
    """
    Return list of (roi_name, roi_type) tuples in the display order:
    grouped by ROI type (body→face→place→word→streams→visual),
    within each group sorted by mean(LH, RH) r2_wiped_mean descending.
    Each ROI appears once (bilateral average used only for sorting).
    """
    rows = []
    tg_avg = (tg.groupby(['roi_type','roi_name'])['r2_wiped_mean']
                .mean().reset_index())
    for rt in _ROI_TYPE_ORDER:
        sub = tg_avg[tg_avg['roi_type']==rt].sort_values(
                  'r2_wiped_mean', ascending=False)
        for _, row in sub.iterrows():
            rows.append((row['roi_name'], row['roi_type']))
    return rows

roi_order_f1 = _build_fig1_order(T_group)
roi_names_f1 = [r for r, _ in roi_order_f1]
roi_types_f1 = [t for _, t in roi_order_f1]
N_ROI        = len(roi_names_f1)

# Bar positions: each ROI has a pair of bars (LH, RH)
BAR_W   = 0.35
rng     = np.random.RandomState(42)
xs_lh   = np.arange(N_ROI) - BAR_W / 2
xs_rh   = np.arange(N_ROI) + BAR_W / 2

def _get_grp(rname, hemi):
    """Return the T_group row for a given ROI and hemi, or None."""
    rows = T_group[(T_group['roi_name']==rname) & (T_group['hemi']==hemi)]
    return rows.iloc[0] if len(rows) else None

def _get_subj_vals(rname, hemi, col='r2_wiped_mean'):
    rows = T1[(T1['roi_name']==rname) & (T1['hemi']==hemi)]
    return rows[col].values if len(rows) else np.array([])

# Build per-ROI bar values for both panels
lh_w, lh_sem, lh_ratio, lh_ratio_sem = [], [], [], []
rh_w, rh_sem, rh_ratio, rh_ratio_sem = [], [], [], []
lh_sig, rh_sig = [], []

for rname in roi_names_f1:
    for store_w, store_sem, store_ratio, store_rsem, store_sig, hemi in [
        (lh_w, lh_sem, lh_ratio, lh_ratio_sem, lh_sig, 'LH'),
        (rh_w, rh_sem, rh_ratio, rh_ratio_sem, rh_sig, 'RH'),
    ]:
        row = _get_grp(rname, hemi)
        if row is not None:
            store_w.append(row['r2_wiped_mean'])
            store_sem.append(row['r2_wiped_sem'])
            store_ratio.append(row['ratio_mean'])
            store_rsem.append(row['ratio_sem'])
            store_sig.append(bool(row['sig']))
        else:
            store_w.append(np.nan); store_sem.append(0)
            store_ratio.append(np.nan); store_rsem.append(0)
            store_sig.append(False)

fig1, (ax1, ax2) = plt.subplots(1, 2, figsize=(22, 6))

for ax, vals_lh, sems_lh, vals_rh, sems_rh, sig_lh, sig_rh, ylabel, title_sfx in [
    (ax1, lh_w, lh_sem, rh_w, rh_sem, lh_sig, rh_sig,
     'Mean R²_wiped ± SEM (across subjects)',
     'R²_wiped per ROI'),
    (ax2, lh_ratio, lh_ratio_sem, rh_ratio, rh_ratio_sem, lh_sig, rh_sig,
     'Semantic independence ratio  (R²_wiped / R²_raw)',
     'Semantic independence ratio'),
]:
    clrs = [_ROI_PAL.get(rt, '#888') for rt in roi_types_f1]

    # LH bars (lighter)
    bars_lh = ax.bar(xs_lh, vals_lh, width=BAR_W,
                     color=clrs, alpha=0.60, edgecolor='white', linewidth=0.4,
                     zorder=2, label='LH')
    ax.errorbar(xs_lh, vals_lh, yerr=sems_lh,
                fmt='none', color='#333', capsize=2, linewidth=0.8, zorder=3)
    # RH bars (darker / hatched)
    bars_rh = ax.bar(xs_rh, vals_rh, width=BAR_W,
                     color=clrs, alpha=0.95, edgecolor='white', linewidth=0.4,
                     hatch='//', zorder=2, label='RH')
    ax.errorbar(xs_rh, vals_rh, yerr=sems_rh,
                fmt='none', color='#111', capsize=2, linewidth=0.8, zorder=3)

    # FDR stars — compute y_range from actual data values (safe in Agg backend)
    all_tops = [v + s for v, s in zip(vals_lh + vals_rh, sems_lh + sems_rh)
                if not np.isnan(v)]
    y_hi    = max(all_tops) if all_tops else 0.01
    y_lo    = min([v for v in vals_lh + vals_rh if not np.isnan(v)] or [0])
    y_range = max(y_hi - y_lo, 1e-6)
    for xi, (rname, rt) in enumerate(roi_order_f1):
        for xs_h, vals_h, sems_h, sig_h, offset in [
            (xs_lh, vals_lh, sems_lh, sig_lh, -BAR_W/2),
            (xs_rh, vals_rh, sems_rh, sig_rh,  BAR_W/2),
        ]:
            if sig_h[xi] and not np.isnan(vals_h[xi]):
                y_star = vals_h[xi] + sems_h[xi] + y_range * 0.015
                ax.text(xi + offset, y_star, '★',
                        ha='center', va='bottom', fontsize=7, color='#111',
                        fontweight='bold', zorder=5)

    # Individual subject dots on ratio panel only (ax2)
    if ax is ax2:
        for xi, rname in enumerate(roi_names_f1):
            for xs_h, hemi in [(xs_lh[xi], 'LH'), (xs_rh[xi], 'RH')]:
                w_vals = _get_subj_vals(rname, hemi, 'r2_wiped_mean')
                r_vals = _get_subj_vals(rname, hemi, 'r2_raw_mean')
                if len(w_vals) == 0: continue
                ratios = w_vals / np.maximum(r_vals, 1e-8)
                jit = rng.uniform(-0.06, 0.06, len(ratios))
                ax.scatter(xs_h + jit, ratios, s=9, color='#111',
                           alpha=0.50, zorder=4, linewidths=0)

    ax.axhline(0, color='#444', linewidth=0.5, linestyle='--', zorder=1)
    ax.set_xticks(np.arange(N_ROI))
    ax.set_xticklabels(roi_names_f1, rotation=50, ha='right', fontsize=7)
    ax.set_ylabel(ylabel, fontsize=9)
    ax.set_title(f'{title_sfx}  (N={N_SUBJ})  ★ = FDR q<0.05', fontsize=10, pad=8)

    # Group-type dividers and labels
    y_lo2, _ = ax.get_ylim()
    prev_rt  = None
    type_starts = {}
    for xi, (_, rt) in enumerate(roi_order_f1):
        if rt != prev_rt:
            if xi > 0:
                ax.axvline(xi - 0.5, color='#bbb', linewidth=0.7,
                           linestyle=':', zorder=0)
            type_starts[rt] = xi
            prev_rt = rt
    # Type labels at top
    for rt, xi_start in type_starts.items():
        xi_end = xi_start
        for j, (_, t) in enumerate(roi_order_f1):
            if t == rt: xi_end = j
        xi_mid = (xi_start + xi_end) / 2
        ax.text(xi_mid, ax.get_ylim()[1] * 0.97,
                _ROI_TYPE_LABEL.get(rt, rt),
                ha='center', va='top', fontsize=6.5, color=_ROI_PAL.get(rt,'#888'),
                fontweight='bold', style='italic')

    # Hemisphere legend
    leg_hemi = [Patch(fc='grey', alpha=0.60, ec='none', label='LH'),
                Patch(fc='grey', alpha=0.95, hatch='//', ec='none', label='RH')]
    # ROI type legend
    leg_type = [Patch(fc=_ROI_PAL[rt], ec='none',
                      label=_ROI_TYPE_LABEL.get(rt, rt))
                for rt in _ROI_TYPE_ORDER if rt in roi_types_f1]
    ax.legend(handles=leg_hemi + leg_type, fontsize=6.5,
              loc='upper right', framealpha=0.85, edgecolor='none', ncol=2)

fig1.suptitle(
    'Figure 1 — Regional dissociation of non-visual linguistic encoding\n'
    'R²_wiped: fMRI variance explained by vision-residualised BERT embeddings',
    fontsize=11, y=1.01)
plt.tight_layout()
p1 = os.path.join(FIGS_DIR, 'fig1_regional_dissociation.pdf')
fig1.savefig(p1, dpi=DPI, bbox_inches='tight')
plt.close(fig1)
print(f"    Saved {p1}")

# Fig 1 CSV
T4_rows = []
for rname, rt in roi_order_f1:
    for hemi in ['LH', 'RH']:
        row = _get_grp(rname, hemi)
        if row is None: continue
        T4_rows.append({
            'roi_name': rname, 'roi_type': rt, 'hemi': hemi,
            'n_subjects':    row['n_subjects'],
            'r2_wiped_mean': row['r2_wiped_mean'],
            'r2_wiped_sem':  row['r2_wiped_sem'],
            'r2_raw_mean':   row['r2_raw_mean'],
            'r2_raw_sem':    row['r2_raw_sem'],
            'ratio_mean':    row['ratio_mean'],
            'ratio_sem':     row['ratio_sem'],
            't_stat':        row['t_stat'],
            'p_val':         row['p_val'],
            'q_fdr':         row['q_fdr'],
            'hedges_g':      row['hedges_g'],
            'sig':           row['sig'],
        })
T4 = pd.DataFrame(T4_rows)
T4.to_csv(os.path.join(TABLES_DIR, 'T4_fig1_plot_data.csv'), index=False)
print(f"    Saved T4_fig1_plot_data.csv ({len(T4)} rows)")

# ══════════════════════════════════════════════════════════════════════════
# FIGURE 2 — Subject-level replication
#
# Three key ROIs:
#   EBA (body-selective, RH preferred)
#   ventral stream (streams)
#   V1v (early visual — negative control)
# One panel. Per-subject ratio as coloured dots. Paired lines connect each
# subject's three ROI values. Group mean bar + SEM. This makes the
# within-subject dissociation (EBA > ventral > V1v) immediately obvious.
# ══════════════════════════════════════════════════════════════════════════
print(f"\n  Generating Figure 2 {elapsed()}")

_KEY_ROIS = [
    ('EBA',     'RH', 'Body-selective\n(EBA, RH)'),
    ('ventral', 'LH', 'Ventral stream\n(LH)'),
    ('V1v',     'LH', 'Early visual\n(V1v, LH) — null'),
]
fig2_rows = []
for rname, pref_hemi, label in _KEY_ROIS:
    sub_df = T1[(T1['roi_name']==rname) & (T1['hemi']==pref_hemi)]
    if sub_df.empty:
        sub_df = T1[T1['roi_name']==rname]
        if sub_df.empty: continue
        pref_hemi = sub_df['hemi'].iloc[0]
    for _, row in sub_df.iterrows():
        fig2_rows.append({
            'subject':   row['subject'],
            'roi_name':  rname,
            'roi_label': label,
            'hemi':      pref_hemi,
            'r2_wiped':  row['r2_wiped_mean'],
            'r2_raw':    row['r2_raw_mean'],
            'ratio':     row['r2_wiped_mean'] / max(row['r2_raw_mean'], 1e-8),
        })

T5 = pd.DataFrame(fig2_rows)
T5.to_csv(os.path.join(TABLES_DIR, 'T5_fig2_subject_dots.csv'), index=False)
print(f"    Saved T5_fig2_subject_dots.csv ({len(T5)} rows)")

if not T5.empty:
    key_rnames  = [r for r, _, _ in _KEY_ROIS if r in T5['roi_name'].values]
    key_labels  = {r: l for r, _, l in _KEY_ROIS}
    key_clrs    = {
        'EBA':     _ROI_PAL['floc-bodies'],
        'ventral': _ROI_PAL['streams'],
        'V1v':     _ROI_PAL['prf-visualrois'],
    }
    xs_f2 = np.arange(len(key_rnames))

    fig2, ax2m = plt.subplots(figsize=(6, 5.5))

    # Group mean bars
    grp_m  = [T5[T5['roi_name']==r]['ratio'].mean() for r in key_rnames]
    grp_se = [T5[T5['roi_name']==r]['ratio'].std(ddof=1) /
              np.sqrt(max(len(T5[T5['roi_name']==r]), 1)) for r in key_rnames]
    ax2m.bar(xs_f2, grp_m, color=[key_clrs.get(r,'#888') for r in key_rnames],
             edgecolor='white', linewidth=0.4, zorder=2, width=0.45, alpha=0.65)
    ax2m.errorbar(xs_f2, grp_m, yerr=grp_se,
                  fmt='none', color='#111', capsize=5, linewidth=1.2, zorder=3)

    # Per-subject dots + paired connecting lines
    subjects   = sorted(T5['subject'].unique())
    subj_pal   = plt.cm.tab10(np.linspace(0, 0.9, len(subjects)))
    subj_col   = {s: subj_pal[i] for i, s in enumerate(subjects)}
    rng2       = np.random.RandomState(7)
    for sid in subjects:
        xs_s, ys_s = [], []
        for xi, rname in enumerate(key_rnames):
            row_s = T5[(T5['subject']==sid) & (T5['roi_name']==rname)]
            if row_s.empty: continue
            xs_s.append(xi)
            ys_s.append(float(row_s['ratio'].values[0]))
        if len(xs_s) > 1:
            ax2m.plot(xs_s, ys_s, color=subj_col[sid],
                      alpha=0.4, linewidth=1.0, zorder=3)
        jit = rng2.uniform(-0.07, 0.07, len(xs_s))
        ax2m.scatter([x + j for x, j in zip(xs_s, jit)], ys_s,
                     s=38, color=subj_col[sid], alpha=0.9,
                     zorder=4, linewidths=0.5, edgecolors='white')

    ax2m.axhline(0, color='#444', linewidth=0.6, linestyle='--', zorder=1)
    ax2m.set_xticks(xs_f2)
    ax2m.set_xticklabels([key_labels.get(r, r) for r in key_rnames], fontsize=9)
    ax2m.set_ylabel('Semantic independence ratio  (R²_wiped / R²_raw)', fontsize=9)
    ax2m.set_title(
        f'Figure 2 — Subject-level replication  (N={N_SUBJ})\n'
        'Bars = group mean ± SEM   •  = individual subjects',
        fontsize=10)

    leg = [Line2D([0],[0], marker='o', color=subj_col[s], lw=0.9,
                  markersize=5, label=s) for s in subjects]
    ax2m.legend(handles=leg, fontsize=6.5, loc='upper right',
                ncol=2, framealpha=0.85, edgecolor='none')
    plt.tight_layout()
    p2 = os.path.join(FIGS_DIR, 'fig2_subject_replication.pdf')
    fig2.savefig(p2, dpi=DPI, bbox_inches='tight')
    plt.close(fig2)
    print(f"    Saved {p2}")

# ══════════════════════════════════════════════════════════════════════════
# FIGURE 3 — Cortical flatmap
#
# Group-average R²_wiped on fsaverage surface (163842 vertices per hemi).
# Per-vertex mean is computed as a weighted average: each subject contributes
# only to vertices within their challenge-space mask. Vertices with no
# subjects contributing are NaN (not plotted). This avoids subjects with
# larger cortical coverage dominating the group map.
# Lateral + ventral views saved separately per hemisphere.
# ══════════════════════════════════════════════════════════════════════════
print(f"\n  Generating Figure 3 (flatmaps) {elapsed()}")

flatmap_csv_rows = []

try:
    from nilearn import plotting as nilplot
    from nilearn import datasets as nildatasets
    fsaverage = nildatasets.fetch_surf_fsaverage('fsaverage')

    for hemi_u, hemi_l, fs_surf, fs_bg in [
        ('LH', 'lh', 'infl_left',  'sulc_left'),
        ('RH', 'rh', 'infl_right', 'sulc_right'),
    ]:
        N_VERT     = 163842
        sum_map    = np.zeros(N_VERT, dtype=np.float64)
        count_map  = np.zeros(N_VERT, dtype=np.int32)

        for sid in list(subj_data.keys()):
            zpath = next((z for z in SUBJ_ZIPS if sid in z), None)
            if zpath is None: continue
            try:
                with zipfile.ZipFile(zpath, 'r') as z:
                    af     = z.namelist()
                    mask_f = [f for f in af
                              if f'{hemi_l}.all-vertices_fsaverage_space' in f
                              and f.endswith('.npy')]
                    if not mask_f: continue
                    with z.open(mask_f[0]) as f:
                        vert_mask = np.load(f).astype(bool)   # (163842,)
            except Exception as e:
                print(f"    Warning: fsaverage mask load failed {sid}: {e}")
                continue

            r2w_path = os.path.join(ARRAYS_DIR, f'{sid}_{hemi_u}_r2_wiped_vox.npy')
            if not os.path.exists(r2w_path): continue
            r2w_ch = np.load(r2w_path).astype(np.float64)

            vert_idx = np.where(vert_mask)[0]
            n_match  = min(len(vert_idx), r2w_ch.shape[0])
            if n_match < len(vert_idx):
                print(f"    Warning {sid}/{hemi_u}: mask has {len(vert_idx)} vertices "
                      f"but r2w has {r2w_ch.shape[0]} — using first {n_match}")
            # Weighted sum: add each subject's values only at their vertices
            sum_map[vert_idx[:n_match]]   += r2w_ch[:n_match]
            count_map[vert_idx[:n_match]] += 1

        # Weighted mean: divide only where at least one subject contributed
        grp_map         = np.full(N_VERT, np.nan, dtype=np.float32)
        valid           = count_map > 0
        grp_map[valid]  = (sum_map[valid] / count_map[valid]).astype(np.float32)

        np.save(os.path.join(ARRAYS_DIR, f'group_{hemi_u}_r2_wiped_fsaverage.npy'),
                grp_map)

        # Archive as CSV (vertex index + value, only valid vertices)
        valid_idx = np.where(valid)[0]
        for vi in valid_idx:
            flatmap_csv_rows.append({
                'hemi': hemi_u, 'vertex': int(vi),
                'r2_wiped_group_mean': float(grp_map[vi]),
                'n_subjects': int(count_map[vi]),
            })

        # Colour scale: symmetric around 0, driven by 99th pctile of positives
        pos_vals = grp_map[valid & (grp_map > 0)]
        vmax     = float(np.percentile(pos_vals, 99)) if len(pos_vals) else 0.05
        vmax     = max(vmax, 1e-4)   # never zero

        surf_mesh = getattr(fsaverage, fs_surf)
        surf_bg   = getattr(fsaverage, fs_bg)

        for view, view_tag in [('lateral', 'lateral'), ('ventral', 'ventral')]:
            fig3, ax3 = plt.subplots(figsize=(11, 4.5))
            ax3.axis('off')
            nilplot.plot_surf_stat_map(
                surf_mesh=surf_mesh,
                stat_map=grp_map,
                hemi=hemi_l,
                view=view,
                bg_map=surf_bg,
                cmap='RdBu_r',
                vmax=vmax,
                symmetric_cbar=True,
                colorbar=True,
                title=(f'Figure 3 — Group R²_wiped  {hemi_u} ({view_tag})'
                       f'  N={int(count_map.max())} subjects\n'
                       'Weighted mean: vision-residualised BERT → fMRI'),
                figure=fig3,
                axes=ax3,
            )
            p3 = os.path.join(FIGS_DIR, f'fig3_flatmap_{hemi_u}_{view_tag}.pdf')
            fig3.savefig(p3, dpi=DPI, bbox_inches='tight')
            plt.close(fig3)
            print(f"    Saved {p3}")

    # Save flatmap CSV
    if flatmap_csv_rows:
        T6 = pd.DataFrame(flatmap_csv_rows)
        T6.to_csv(os.path.join(TABLES_DIR, 'T6_flatmap_group.csv'), index=False)
        print(f"    Saved T6_flatmap_group.csv ({len(T6)} vertices)")

except ImportError:
    print("    nilearn not available — skipping Figure 3 (flatmaps)")
except Exception as e:
    print(f"    Figure 3 failed: {e}")
    import traceback; traceback.print_exc()

# ══════════════════════════════════════════════════════════════════════════
# SUMMARY
# ══════════════════════════════════════════════════════════════════════════
print(f"\nCHUNK 7 done {elapsed()}")
print(f"\n{'='*70}\nPIPELINE v9 COMPLETE {elapsed()}  |  N={N_SUBJ} subjects\n{'='*70}")
print(f"Outputs in: {OUT_DIR}")
print(f"  arrays/  : bert_wiped, bert_raw, r2_wiped_vox, r2_raw_vox, delta_r2_vox")
print(f"             group_LH/RH_r2_wiped_fsaverage.npy")
print(f"  tables/  : T1_roi_r2.csv  T2_voxelwise_r2_summary.csv")
print(f"             T3_group_roi_r2.csv  T4_fig1_plot_data.csv")
print(f"             T5_fig2_subject_dots.csv  T6_flatmap_group.csv")
print(f"  figures/ : fig1_regional_dissociation.pdf  (1 combined figure)")
print(f"             fig2_subject_replication.pdf")
print(f"             fig3_flatmap_LH_lateral.pdf  fig3_flatmap_LH_ventral.pdf")
print(f"             fig3_flatmap_RH_lateral.pdf  fig3_flatmap_RH_ventral.pdf")

"""
NSD SIGN-FLIP TEST — standalone block
======================================
Run this AFTER nsd_pipeline_v9.py has finished.

Requires in memory (already present if run in same Colab session):
  T1          — per-subject ROI table (built in Chunk 6)
  T_group     — group ROI table with t-test results (built in Chunk 7)
  TABLES_DIR  — path to nsd_results_v9/tables/
  N_SUBJ      — number of subjects

If running in a fresh session, set LOAD_FROM_CSV = True below and
point TABLES_DIR to your Drive path — the block will reload T1 and
T_group from the saved CSVs.

What this does
--------------
For each ROI × hemisphere:
  1. Collect the N subject-level r2_wiped_mean values.
  2. Enumerate all 2^N sign-flip configurations (exact, no sampling).
  3. For each configuration, flip the sign of a random subset of values
     and compute the group mean — building the exact null distribution
     of the mean under H0: signs are exchangeable (i.e. effects are
     equally likely to be positive or negative).
  4. p_signflip = fraction of null means >= observed mean (one-tailed,
     since our directional prediction is r2_wiped > 0).
  5. BH-FDR across all ROI × hemi p_signflip values.

The result is appended to T_group as two new columns:
  p_signflip   — exact sign-flip p-value
  q_signflip   — BH-FDR corrected

T3_group_roi_r2.csv is overwritten with the enriched table.
A new T3b_signflip_summary.csv is also written with just the key columns.

With N=7: 2^7 = 128 permutations. Minimum achievable p = 1/128 ≈ 0.0078.
Runtime: negligible (pure numpy, no regression).
"""

# ── Config ────────────────────────────────────────────────────────────────
LOAD_FROM_CSV = False   # set True if running in a fresh Colab session
TABLES_DIR_CSV = '/content/drive/MyDrive/nsd_results_v9/tables'  # only used if LOAD_FROM_CSV

import numpy as np
import pandas as pd
import itertools
import statsmodels.stats.multitest as smm

if LOAD_FROM_CSV:
    TABLES_DIR = TABLES_DIR_CSV
    T1      = pd.read_csv(f'{TABLES_DIR}/T1_roi_r2.csv')
    T_group = pd.read_csv(f'{TABLES_DIR}/T3_group_roi_r2.csv')
    N_SUBJ  = T1['subject'].nunique()
    print(f"Loaded T1 ({len(T1)} rows) and T_group ({len(T_group)} rows) from CSV")
    print(f"N_SUBJ = {N_SUBJ}")

# ── Sign-flip test ────────────────────────────────────────────────────────
def sign_flip_p(vals):
    """
    Exact one-tailed sign-flip test for H0: mean(vals) <= 0.

    Enumerates all 2^n sign configurations, computes the mean under
    each, returns p = fraction of null means >= observed mean.

    Parameters
    ----------
    vals : array-like, shape (n,)
        Per-subject effect sizes (r2_wiped_mean for one ROI).

    Returns
    -------
    p : float in [1/2^n, 1.0]
    """
    vals = np.asarray(vals, dtype=np.float64)
    n    = len(vals)
    obs  = vals.mean()

    # All 2^n sign vectors: shape (2^n, n)
    signs = np.array(list(itertools.product([-1, 1], repeat=n)),
                     dtype=np.float64)          # (2^n, n)
    null_means = (signs * vals[np.newaxis, :]).mean(axis=1)  # (2^n,)

    p = float((null_means >= obs).mean())
    return p

print(f"\nRunning sign-flip tests across {len(T_group)} ROI×hemi combinations "
      f"(2^{N_SUBJ} = {2**N_SUBJ} permutations each)...")

p_sf_list = []
for _, grp_row in T_group.iterrows():
    hemi  = grp_row['hemi']
    rname = grp_row['roi_name']
    sub_vals = T1[(T1['hemi'] == hemi) & (T1['roi_name'] == rname)]['r2_wiped_mean'].values
    if len(sub_vals) < 2:
        p_sf_list.append(1.0)
    else:
        p_sf_list.append(sign_flip_p(sub_vals))

T_group['p_signflip'] = p_sf_list

# BH-FDR on sign-flip p-values
_, q_sf, _, _ = smm.multipletests(T_group['p_signflip'].values,
                                   alpha=0.05, method='fdr_bh')
T_group['q_signflip'] = q_sf
T_group['sig_signflip'] = T_group['q_signflip'] < 0.05

print(f"Done.")
print(f"\nFDR significant (q_signflip < 0.05): {T_group['sig_signflip'].sum()} / {len(T_group)} ROIs")
print(f"FDR significant (q_ttest   < 0.05): {T_group['sig'].sum()} / {len(T_group)} ROIs")

# ── Print comparison table ────────────────────────────────────────────────
display_cols = ['hemi', 'roi_name', 'r2_wiped_mean', 'r2_wiped_sem',
                't_stat', 'p_val', 'q_fdr',
                'p_signflip', 'q_signflip', 'sig_signflip']
print("\nTop 20 ROIs by r2_wiped_mean:")
print(T_group.sort_values('r2_wiped_mean', ascending=False)
      [display_cols].head(20).to_string(index=False))

# ── Save enriched tables ──────────────────────────────────────────────────
import os
T_group.to_csv(os.path.join(TABLES_DIR, 'T3_group_roi_r2.csv'), index=False)
print(f"\nOverwrote T3_group_roi_r2.csv with p_signflip + q_signflip columns")

T3b = T_group[['hemi', 'roi_type', 'roi_name', 'n_subjects',
               'r2_wiped_mean', 'r2_wiped_sem',
               'ratio_mean', 'ratio_sem',
               't_stat', 'p_val', 'q_fdr', 'sig',
               'p_signflip', 'q_signflip', 'sig_signflip',
               'hedges_g']].copy()
T3b = T3b.sort_values('r2_wiped_mean', ascending=False).reset_index(drop=True)
T3b.to_csv(os.path.join(TABLES_DIR, 'T3b_signflip_summary.csv'), index=False)
print(f"Saved T3b_signflip_summary.csv ({len(T3b)} rows)")

# ── Agreement check ───────────────────────────────────────────────────────
agree    = ((T_group['sig'] == True)  & (T_group['sig_signflip'] == True)).sum()
tonly    = ((T_group['sig'] == True)  & (T_group['sig_signflip'] == False)).sum()
sfonly   = ((T_group['sig'] == False) & (T_group['sig_signflip'] == True)).sum()
neither  = ((T_group['sig'] == False) & (T_group['sig_signflip'] == False)).sum()
print(f"\nAgreement between t-test and sign-flip (FDR q<0.05):")
print(f"  Both significant      : {agree}")
print(f"  t-test only           : {tonly}   (parametric assumption inflated these)")
print(f"  Sign-flip only        : {sfonly}  (t-test was too conservative here)")
print(f"  Neither significant   : {neither}")

"""
NSD DATA EXPORT — full results consolidation
=============================================
Run after nsd_pipeline_v9.py + nsd_signflip_chunk.py have completed.

Reads all existing tables from Drive and produces 3 clean master CSVs:

  MASTER_subject_roi.csv
      One row per subject × ROI × hemisphere.
      Contains: r2_wiped, r2_raw, ratio, delta_r2, n_voxels,
                frac_pos_wiped, r2_wiped_p95, alpha_wipe, r2_vis_bert.
      This is the rawest complete record — everything at subject level.

  MASTER_group_roi.csv
      One row per ROI × hemisphere.
      Contains: group mean/SEM r2_wiped, r2_raw, ratio,
                t-statistic, p_val (t-test), q_fdr (t-test), sig_ttest,
                p_signflip, q_signflip, sig_signflip,
                hedges_g, n_subjects.
      Primary table for reporting. Sorted by r2_wiped_mean descending.

  MASTER_voxelwise_summary.csv
      One row per subject × hemisphere.
      Whole-brain summary: mean r2_wiped, fraction positive voxels,
      r2_raw, delta_r2, alpha chosen for residualisation, r2_vis_bert.

All files written to TABLES_DIR on Drive.
Prints a full console summary of significant results.
"""

import os
import numpy as np
import pandas as pd

# ── Config ────────────────────────────────────────────────────────────────
# If running fresh session set LOAD_FROM_DRIVE = True
LOAD_FROM_DRIVE = False
TABLES_DIR = '/content/drive/MyDrive/nsd_results_v9/tables'

if LOAD_FROM_DRIVE:
    # Reload all tables from Drive CSVs
    T1      = pd.read_csv(f'{TABLES_DIR}/T1_roi_r2.csv')
    T2      = pd.read_csv(f'{TABLES_DIR}/T2_voxelwise_r2_summary.csv')
    T_group = pd.read_csv(f'{TABLES_DIR}/T3_group_roi_r2.csv')
    print(f"Loaded from Drive:")
    print(f"  T1      : {len(T1)} rows  (subject × ROI × hemi)")
    print(f"  T2      : {len(T2)} rows  (subject × hemi summary)")
    print(f"  T_group : {len(T_group)} rows  (group ROI stats)")
    # Check sign-flip columns are present
    if 'p_signflip' not in T_group.columns:
        print("  WARNING: p_signflip not found in T3 — run nsd_signflip_chunk.py first")

# ── Verify required columns exist ────────────────────────────────────────
required_t1 = ['subject','hemi','roi_type','roi_name',
                'r2_wiped_mean','r2_wiped_median','r2_wiped_std','r2_wiped_p95',
                'r2_raw_mean','delta_r2_mean','frac_pos_wiped','n_voxels']
required_tg = ['hemi','roi_type','roi_name','n_subjects',
                'r2_wiped_mean','r2_wiped_sem','r2_raw_mean','r2_raw_sem',
                'ratio_mean','ratio_sem','t_stat','p_val','q_fdr','sig',
                'hedges_g']

missing_t1 = [c for c in required_t1 if c not in T1.columns]
missing_tg = [c for c in required_tg if c not in T_group.columns]
if missing_t1: print(f"WARNING T1 missing columns: {missing_t1}")
if missing_tg: print(f"WARNING T_group missing columns: {missing_tg}")

has_signflip = 'p_signflip' in T_group.columns

# ═════════════════════════════════════════════════════════════════════════
# MASTER 1 — Subject-level ROI table
# Merge T1 with per-subject alpha and r2_vis_bert from T2
# ═════════════════════════════════════════════════════════════════════════
print("\nBuilding MASTER_subject_roi.csv...")

# Compute per-subject ratio (r2_wiped / r2_raw)
T1 = T1.copy()
T1['ratio'] = T1['r2_wiped_mean'] / T1['r2_raw_mean'].clip(lower=1e-8)

# Join alpha_wipe and r2_vis_bert from T2
T2_sub = T2[['subject','hemi','alpha_wipe','r2_vis_bert',
             'n_voxels']].copy()
T2_sub = T2_sub.rename(columns={'n_voxels': 'n_voxels_total'})

M1 = T1.merge(T2_sub, on=['subject','hemi'], how='left')

# Add group significance flags per ROI so subject rows know if their ROI
# is group-significant
grp_sig = T_group[['hemi','roi_name','sig']].copy()
grp_sig = grp_sig.rename(columns={'sig': 'group_sig_ttest'})
if has_signflip:
    grp_sig2 = T_group[['hemi','roi_name','sig_signflip']].copy()
    grp_sig  = grp_sig.merge(grp_sig2, on=['hemi','roi_name'], how='left')

M1 = M1.merge(grp_sig, on=['hemi','roi_name'], how='left')

# Clean column order
col_order_m1 = [
    'subject','hemi','roi_type','roi_name',
    'n_voxels','n_voxels_total',
    'r2_wiped_mean','r2_wiped_median','r2_wiped_std','r2_wiped_p95',
    'r2_raw_mean','delta_r2_mean','frac_pos_wiped',
    'ratio',
    'alpha_wipe','r2_vis_bert',
    'group_sig_ttest',
]
if has_signflip:
    col_order_m1.append('sig_signflip')
M1 = M1[[c for c in col_order_m1 if c in M1.columns]]
M1 = M1.sort_values(['roi_type','roi_name','hemi','subject']).reset_index(drop=True)

M1.to_csv(os.path.join(TABLES_DIR, 'MASTER_subject_roi.csv'), index=False)
print(f"  Saved MASTER_subject_roi.csv  ({len(M1)} rows, {len(M1.columns)} columns)")

# ═════════════════════════════════════════════════════════════════════════
# MASTER 2 — Group ROI table (primary reporting table)
# ═════════════════════════════════════════════════════════════════════════
print("\nBuilding MASTER_group_roi.csv...")

M2 = T_group.copy()

# Add readable significance stars column
def sig_stars(row):
    p = row['p_signflip'] if has_signflip else row['p_val']
    q = row['q_signflip'] if has_signflip else row['q_fdr']
    if q < 0.001: return '***'
    if q < 0.01:  return '**'
    if q < 0.05:  return '*'
    return 'ns'

M2['sig_label'] = M2.apply(sig_stars, axis=1)

# Rename columns for clarity
rename_map = {
    'sig':           'sig_ttest_fdr',
    'r2_wiped_mean': 'r2_wiped_mean',
    'r2_wiped_sem':  'r2_wiped_sem_across_subjects',
    'r2_raw_mean':   'r2_raw_mean',
    'r2_raw_sem':    'r2_raw_sem_across_subjects',
}
M2 = M2.rename(columns=rename_map)

# Column order for reporting
col_order_m2 = [
    'hemi','roi_type','roi_name','n_subjects',
    'r2_wiped_mean','r2_wiped_sem_across_subjects',
    'r2_raw_mean','r2_raw_sem_across_subjects',
    'ratio_mean','ratio_sem',
    't_stat','p_val','q_fdr','sig_ttest_fdr',
]
if has_signflip:
    col_order_m2 += ['p_signflip','q_signflip','sig_signflip']
col_order_m2 += ['hedges_g','sig_label']

M2 = M2[[c for c in col_order_m2 if c in M2.columns]]
M2 = M2.sort_values('r2_wiped_mean', ascending=False).reset_index(drop=True)

M2.to_csv(os.path.join(TABLES_DIR, 'MASTER_group_roi.csv'), index=False)
print(f"  Saved MASTER_group_roi.csv  ({len(M2)} rows, {len(M2.columns)} columns)")

# ═════════════════════════════════════════════════════════════════════════
# MASTER 3 — Voxelwise whole-brain summary
# ═════════════════════════════════════════════════════════════════════════
print("\nBuilding MASTER_voxelwise_summary.csv...")

M3 = T2.copy()
M3 = M3.sort_values(['subject','hemi']).reset_index(drop=True)
M3.to_csv(os.path.join(TABLES_DIR, 'MASTER_voxelwise_summary.csv'), index=False)
print(f"  Saved MASTER_voxelwise_summary.csv  ({len(M3)} rows, {len(M3.columns)} columns)")

# ═════════════════════════════════════════════════════════════════════════
# CONSOLE SUMMARY
# ═════════════════════════════════════════════════════════════════════════
print(f"\n{'='*70}")
print(f"RESULTS SUMMARY  (N={M2['n_subjects'].max()} subjects)")
print(f"{'='*70}")

primary_sig_col  = 'sig_signflip' if has_signflip else 'sig_ttest_fdr'
primary_q_col    = 'q_signflip'   if has_signflip else 'q_fdr'
primary_p_col    = 'p_signflip'   if has_signflip else 'p_val'

sig_df = M2[M2[primary_sig_col] == True].copy()
print(f"\nSignificant ROIs ({primary_sig_col}, q<0.05): {len(sig_df)} / {len(M2)}")
print(f"\n{'ROI':<14} {'Hemi':<5} {'R²_wiped':>9} {'SEM':>7} {'ratio':>7} "
      f"{'t':>7} {'p':>9} {'q':>9} {'g':>6} {'sig':<5}")
print('-' * 80)
for _, row in sig_df.iterrows():
    print(f"{row['roi_name']:<14} {row['hemi']:<5} "
          f"{row['r2_wiped_mean']:>9.5f} "
          f"{row['r2_wiped_sem_across_subjects']:>7.5f} "
          f"{row['ratio_mean']:>7.3f} "
          f"{row['t_stat']:>7.3f} "
          f"{row[primary_p_col]:>9.5f} "
          f"{row[primary_q_col]:>9.5f} "
          f"{row['hedges_g']:>6.2f} "
          f"{row['sig_label']:<5}")

if has_signflip:
    ttest_only = M2[(M2['sig_ttest_fdr']==True) & (M2['sig_signflip']==False)]
    print(f"\nROIs significant by t-test only (parametric inflation, N={len(ttest_only)}):")
    for _, row in ttest_only.iterrows():
        print(f"  {row['hemi']} {row['roi_name']:<14}  "
              f"q_ttest={row['q_fdr']:.4f}  q_signflip={row['q_signflip']:.4f}")

print(f"\n{'='*70}")
print(f"Negative controls (early visual, should be non-significant):")
early = M2[M2['roi_type'] == 'prf-visualrois'][
    ['hemi','roi_name','r2_wiped_mean','t_stat',primary_q_col,'sig_label']]
print(early.to_string(index=False))

print(f"\n{'='*70}")
print(f"Files written to: {TABLES_DIR}")
print(f"  MASTER_subject_roi.csv        — {len(M1)} rows (subject level)")
print(f"  MASTER_group_roi.csv          — {len(M2)} rows (group level, primary)")
print(f"  MASTER_voxelwise_summary.csv  — {len(M3)} rows (whole-brain per subject)")