# -*- coding: utf-8 -*-
"""visualization script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Jp4F7kY6opb-Uk1-ZWcq8w1VXiGXWAY
"""

"""
NSD v9 — TRUE 2D CORTICAL FLATMAP  (bilateral, publication figure)
Uses matplotlib tripcolor to render directly onto mesh triangles —
only fills pixels inside actual cortex faces, zero bleed outside.
"""
import os, sys, zipfile, subprocess
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
import matplotlib.tri as mtri
from matplotlib.colors import Normalize, LinearSegmentedColormap
from scipy.ndimage import binary_dilation, binary_fill_holes

subprocess.run([sys.executable,'-m','pip','install',
                'nibabel','nilearn','adjustText','-q'], check=True)
import nibabel as nib
from nilearn import datasets as nildatasets
from adjustText import adjust_text

matplotlib.rcParams.update({'font.family':'DejaVu Sans',
                             'pdf.fonttype':42,'ps.fonttype':42})

# ══════════════════════════════════════════════════════════════════════════
# CONFIGURE
# ══════════════════════════════════════════════════════════════════════════
ARRAYS_DIR = '/content/drive/MyDrive/nsd_results_v9/arrays'
SUBJ_DIR   = '/content/drive/MyDrive/nsd'
FIGS_OUT   = '/content/drive/MyDrive/nsd_results_v9/figures_flatmap'
os.makedirs(FIGS_OUT, exist_ok=True)

SUBJECTS = [f'subj0{i}' for i in range(1, 8)]
DPI      = 300
N_VERT   = 163842

ROI_TYPES = ['prf-visualrois','floc-bodies','floc-faces',
             'floc-places','floc-words','streams']
ROI_NAMES = {
    'prf-visualrois': {1:'V1v',2:'V1d',3:'V2v',4:'V2d',5:'V3v',6:'V3d',7:'hV4'},
    'floc-bodies':    {1:'EBA',2:'FBA-1',3:'FBA-2',4:'mTL-bodies'},
    'floc-faces':     {1:'OFA',2:'FFA-1',3:'FFA-2',4:'mTL-faces',5:'aTL-faces'},
    'floc-places':    {1:'OPA',2:'PPA',3:'RSC'},
    'floc-words':     {1:'OWFA',2:'VWFA-1',3:'VWFA-2',4:'mfs-words',5:'mTL-words'},
    'streams':        {1:'early',2:'midventral',3:'midlateral',
                       4:'midparietal',5:'ventral',6:'lateral',7:'parietal'},
}
ROI_TYPE_COLOR = {
    'prf-visualrois': '#E63946',
    'floc-bodies':    '#FF6B35',
    'floc-faces':     '#FF4DC4',
    'floc-places':    '#457B9D',
    'floc-words':     '#9B5DE5',
    'streams':        '#00B4D8',
}
ROI_TYPE_LABEL = {
    'prf-visualrois': 'Early visual (V1\u2013hV4)',
    'floc-bodies':    'Body-selective',
    'floc-faces':     'Face-selective',
    'floc-places':    'Place-selective',
    'floc-words':     'Word-selective',
    'streams':        'Streams',
}

# ══════════════════════════════════════════════════════════════════════════
# STEP 1 — R² MAPS
# ══════════════════════════════════════════════════════════════════════════
print("Loading R² maps...")
grp = {}
for h in ['LH','RH']:
    grp[h] = np.load(os.path.join(ARRAYS_DIR,
              f'group_{h}_r2_wiped_fsaverage.npy')).astype(np.float32)
all_pos = np.concatenate([grp['LH'][grp['LH']>0], grp['RH'][grp['RH']>0]])
VMAX = max(float(np.percentile(all_pos, 99)), 1e-4)
print(f"  vmax={VMAX:.5f}")

# ══════════════════════════════════════════════════════════════════════════
# STEP 2 — SURFACES
# ══════════════════════════════════════════════════════════════════════════
print("Fetching surfaces...")
fsa = nildatasets.fetch_surf_fsaverage('fsaverage')

def _load_flat(path):
    img = nib.load(str(path))
    return img.darrays[0].data[:, :2].astype(np.float64), \
           img.darrays[1].data.astype(np.int32)

def _load_sulc(path):
    return nib.load(str(path)).darrays[0].data.astype(np.float32)

xy_L, faces_L = _load_flat(fsa.flat_left)
xy_R, faces_R = _load_flat(fsa.flat_right)
sulc_L = _load_sulc(fsa.sulc_left)
sulc_R = _load_sulc(fsa.sulc_right)

# ══════════════════════════════════════════════════════════════════════════
# STEP 3 — ROI VERTEX SETS
# ══════════════════════════════════════════════════════════════════════════
print("Building ROI vertex sets...")
roi_verts = {h: {rt: {} for rt in ROI_TYPES} for h in ['LH','RH']}

for sid in SUBJECTS:
    zp = os.path.join(SUBJ_DIR, f'{sid}.zip')
    if not os.path.exists(zp): print(f"  {sid}: not found"); continue
    try:
        with zipfile.ZipFile(zp,'r') as z:
            af = z.namelist()
            for hemi_u, hemi_l in [('LH','lh'),('RH','rh')]:
                fsf = [f for f in af
                       if f'{hemi_l}.all-vertices_fsaverage_space' in f
                       and f.endswith('.npy')]
                if not fsf: continue
                with z.open(fsf[0]) as fz:
                    fs_idx = np.where(np.load(fz).astype(bool))[0]
                for rt in ROI_TYPES:
                    rf = [f for f in af
                          if f'{hemi_l}.{rt}_challenge_space' in f
                          and f.endswith('.npy')]
                    if not rf: continue
                    with z.open(rf[0]) as fz:
                        roi_arr = np.load(fz)
                    n = min(len(fs_idx), len(roi_arr))
                    for lid, rname in ROI_NAMES[rt].items():
                        v = set(fs_idx[:n][(roi_arr[:n]==lid)].tolist())
                        if v:
                            roi_verts[hemi_u][rt].setdefault(
                                rname, set()).update(v)
        print(f"  {sid}: OK")
    except Exception as e:
        print(f"  {sid}: {e}")

# ══════════════════════════════════════════════════════════════════════════
# STEP 4 — CROP EXTENTS
# From diagnostic: hardcode the known tight ROI bounds (+3% pad).
# LH: x=[-106.7, 163.7] is WRONG — that's because LH flat is mirrored.
# Actual LH ROI vertices from diagnostic:
#   All ROIs combined x=[-99.0, 156.0] but these are the FULL mesh coords.
# We use the per-hemi vertex bounding boxes directly.
# ══════════════════════════════════════════════════════════════════════════

def _tight_extent(xy, roi_verts_hemi, pad_frac=0.04, min_verts=50):
    """
    Bounding box of ROI vertices, ignoring any per-region cluster
    with fewer than min_verts vertices (orphan specks like the tiny
    streams fragment that sits far from the main ROI body).
    """
    all_idx = sorted(set(
        v for rt in ROI_TYPES
        for rname, vset in roi_verts_hemi[rt].items()
        if len(vset) >= min_verts          # ← skip tiny orphan clusters
        for v in vset
    ))
    if not all_idx:                        # fallback: use everything
        all_idx = sorted(set(
            v for rt in ROI_TYPES
            for vset in roi_verts_hemi[rt].values()
            for v in vset))
    idx = np.array(all_idx, dtype=np.int32)
    xs, ys = xy[idx, 0], xy[idx, 1]
    xw, yw = xs.max()-xs.min(), ys.max()-ys.min()
    return (float(xs.min()-xw*pad_frac), float(xs.max()+xw*pad_frac),
            float(ys.min()-yw*pad_frac), float(ys.max()+yw*pad_frac))

xmin_L, xmax_L, ymin_L, ymax_L = _tight_extent(xy_L, roi_verts['LH'])
xmin_R, xmax_R, ymin_R, ymax_R = _tight_extent(xy_R, roi_verts['RH'])
print(f"  LH crop: x=[{xmin_L:.1f},{xmax_L:.1f}] y=[{ymin_L:.1f},{ymax_L:.1f}]")
print(f"  RH crop: x=[{xmin_R:.1f},{xmax_R:.1f}] y=[{ymin_R:.1f},{ymax_R:.1f}]")

# ══════════════════════════════════════════════════════════════════════════
# STEP 5 — BUILD TRIMESH RESTRICTED TO CROP WINDOW
# Key insight: only keep faces where ALL 3 vertices fall inside the crop box.
# tripcolor then only draws those triangles — perfect pixel-exact masking.
# ══════════════════════════════════════════════════════════════════════════

def _roi_trimesh(xy, faces, roi_verts_hemi, n_rings=3):
    """
    Keep only faces within n_rings of connectivity from any ROI vertex.
    This correctly handles non-convex ROI layouts (like LH flat map)
    without pulling in vast empty cortex between distant ROI clusters.

    Steps:
    1. Seed: all ROI vertices
    2. Expand by n_rings of face-adjacency (each ring adds faces that
       share a vertex with the current frontier)
    3. Return Triangulation of those faces + bool mask of included verts
    """
    # seed set — all ROI vertices, excluding tiny orphan clusters
    MIN_SEED = 50
    seed = set()
    for rt in ROI_TYPES:
        for rname, vset in roi_verts_hemi[rt].items():
            if len(vset) >= MIN_SEED:
                seed.update(vset)
    seed = np.array(sorted(seed), dtype=np.int32)

    # build vertex → face lookup
    n_faces = len(faces)
    from collections import defaultdict
    v2f = defaultdict(list)
    for fi, (a,b,c) in enumerate(faces):
        v2f[a].append(fi); v2f[b].append(fi); v2f[c].append(fi)

    # expand rings
    included_faces = set()
    frontier_verts = set(seed.tolist())
    for _ in range(n_rings):
        new_verts = set()
        for v in frontier_verts:
            for fi in v2f[v]:
                if fi not in included_faces:
                    included_faces.add(fi)
                    new_verts.update(faces[fi].tolist())
        frontier_verts = new_verts - frontier_verts
        if not frontier_verts:
            break

    crop_faces = faces[np.array(sorted(included_faces), dtype=np.int32)]
    # which vertices are used
    used_verts = np.zeros(len(xy), dtype=bool)
    used_verts[crop_faces.ravel()] = True
    tri = mtri.Triangulation(xy[:,0], xy[:,1], crop_faces)
    return tri, used_verts

print("Building ROI-adjacency trimeshes (n_rings=3)...")
tri_L, inbox_L = _roi_trimesh(xy_L, faces_L, roi_verts['LH'], n_rings=3)
tri_R, inbox_R = _roi_trimesh(xy_R, faces_R, roi_verts['RH'], n_rings=3)
print(f"  LH: {inbox_L.sum():,} vertices  RH: {inbox_R.sum():,} vertices")

# ══════════════════════════════════════════════════════════════════════════
# STEP 6 — ROI CONTOUR RASTERISATION (for outline drawing)
# Use a modest grid; scatter ROI vertices → dilate → contour.
# The contour is drawn in data coordinates so it aligns with tripcolor.
# ══════════════════════════════════════════════════════════════════════════
GRID_RES = 1000

def _roi_pixel_mask(xy, vert_indices, xmin, xmax, ymin, ymax,
                    res=GRID_RES, dilate=4):
    """Scatter ROI verts onto grid, dilate, return bool (res,res)."""
    idx = vert_indices
    px  = np.clip(((xy[idx,0]-xmin)/(xmax-xmin)*(res-1)).astype(int),0,res-1)
    py  = np.clip(((xy[idx,1]-ymin)/(ymax-ymin)*(res-1)).astype(int),0,res-1)
    g   = np.zeros((res,res), dtype=bool)
    g[py, px] = True
    return binary_dilation(binary_fill_holes(
           binary_dilation(g, iterations=2)), iterations=dilate)

# ══════════════════════════════════════════════════════════════════════════
# STEP 7 — CUSTOM GREY-THEN-HOT COLOURMAP
# Bottom layer: sulcal grey  (rendered as separate tripcolor pass)
# Top layer:    R² hot_r     (only where r2 > 0, semi-transparent)
# ══════════════════════════════════════════════════════════════════════════

# Sulcal grey: dark sulci, light gyri — clip to [-2, 2]
SULC_VMIN, SULC_VMAX = -2.0, 2.0

# R² colormap: transparent white at 0 → fully opaque hot_r at vmax
# We achieve this by masking: only render positive R² triangles
HOT = plt.cm.hot_r

# ══════════════════════════════════════════════════════════════════════════
# STEP 8 — DRAW
# ══════════════════════════════════════════════════════════════════════════
print("Drawing figure...")

def _asp(xmin,xmax,ymin,ymax): return (xmax-xmin)/(ymax-ymin)
asp_L = _asp(xmin_L,xmax_L,ymin_L,ymax_L)
asp_R = _asp(xmin_R,xmax_R,ymin_R,ymax_R)

PANEL_H = 8.0
# Fixed equal-width panels — don't scale by aspect ratio,
# let set_aspect('equal') + set_xlim/ylim handle the proportions.
# This keeps the figure centred and legend/title aligned correctly.
FIG_W = 20.0   # fixed total width

fig = plt.figure(figsize=(FIG_W, PANEL_H + 1.8),
                 facecolor='white', dpi=DPI)
gs  = gridspec.GridSpec(1, 2, figure=fig,
                         width_ratios=[1, 1],
                         wspace=0.08,
                         left=0.03, right=0.88,
                         top=0.87, bottom=0.13)

HEMI_DATA = {
    'LH': dict(tri=tri_L, inbox=inbox_L, sulc=sulc_L, r2=grp['LH'],
               xy=xy_L, xmin=xmin_L, xmax=xmax_L, ymin=ymin_L, ymax=ymax_L),
    'RH': dict(tri=tri_R, inbox=inbox_R, sulc=sulc_R, r2=grp['RH'],
               xy=xy_R, xmin=xmin_R, xmax=xmax_R, ymin=ymin_R, ymax=ymax_R),
}

for col, hemi_u in enumerate(['LH','RH']):
    d    = HEMI_DATA[hemi_u]
    ax   = fig.add_subplot(gs[0, col], facecolor='white')
    tri  = d['tri']
    xy   = d['xy']
    xmin, xmax, ymin, ymax = d['xmin'], d['xmax'], d['ymin'], d['ymax']

    # ── 1. Sulcal grey — tripcolor (fills ONLY mesh triangles) ────────
    sulc_norm = Normalize(vmin=SULC_VMIN, vmax=SULC_VMAX)
    ax.tripcolor(tri, d['sulc'],
                 cmap='gray', norm=sulc_norm,
                 shading='gouraud', zorder=1)

    # ── 2. R² overlay — all faces, symmetric RdBu_r ──────────────────
    # blue = negative (BERT below vision baseline, e.g. early visual)
    # white = 0, red = positive (BERT explains variance above vision)
    # Exclude only faces where ALL 3 vertices are exactly 0 (no data)
    from matplotlib.colors import TwoSlopeNorm
    face_r2  = d['r2'][tri.triangles].mean(axis=1)
    has_data = np.abs(face_r2) > 0
    if has_data.any():
        tri_dat = mtri.Triangulation(xy[:,0], xy[:,1],
                                      tri.triangles[has_data])
        ax.tripcolor(tri_dat, d['r2'],
                     cmap='RdBu_r',
                     norm=TwoSlopeNorm(vmin=-VMAX, vcenter=0, vmax=VMAX),
                     shading='gouraud', alpha=0.88, zorder=2)

    # ── 3. ROI contour outlines ───────────────────────────────────────
    texts = []
    for rt in ROI_TYPES:
        col_rt = ROI_TYPE_COLOR[rt]
        for rname, vset in roi_verts[hemi_u][rt].items():
            if not vset: continue
            vidx = np.array(sorted(vset), dtype=np.int32)
            # only vertices inside crop box
            vidx_in = vidx[d['inbox'][vidx]]
            if len(vidx_in) < 10: continue

            pmask = _roi_pixel_mask(xy, vidx_in, xmin, xmax, ymin, ymax)
            ax.contour(pmask.astype(np.float32),
                       levels=[0.5], colors=[col_rt],
                       linewidths=[1.8], origin='lower',
                       extent=[xmin,xmax,ymin,ymax],
                       alpha=1.0, zorder=5)

            # label at vertex centroid (clipped to box)
            cx = float(np.clip(xy[vidx_in,0].mean(), xmin, xmax))
            cy = float(np.clip(xy[vidx_in,1].mean(), ymin, ymax))
            t  = ax.text(cx, cy, rname,
                         fontsize=7, ha='center', va='center',
                         color='black', fontweight='bold', zorder=7,
                         bbox=dict(boxstyle='round,pad=0.2',
                                   facecolor='white', alpha=0.88,
                                   edgecolor=col_rt, linewidth=1.0))
            texts.append(t)

    # ── 4. Label de-collision ─────────────────────────────────────────
    adjust_text(
        texts, ax=ax,
        expand_points=(1.6,1.8), expand_text=(1.4,1.5),
        force_points=(0.2,0.25), force_text=(0.15,0.18),
        arrowprops=dict(arrowstyle='-', color='#555',
                        lw=0.6, alpha=0.8, shrinkA=4, shrinkB=2),
        lim=400,
    )



    ax.set_xlim(xmin, xmax)
    ax.set_ylim(ymin, ymax)
    ax.set_aspect('equal')
    ax.axis('off')

    # ── 6. Hemisphere title — set_title sits above axes frame ─────────
    ax.set_title('Left hemisphere' if hemi_u=='LH' else 'Right hemisphere',
                 fontsize=13, fontweight='bold', color='#111',
                 pad=10, loc='center')

# ── Colourbar ─────────────────────────────────────────────────────────────
cax = fig.add_axes([0.895, 0.22, 0.012, 0.52])
from matplotlib.colors import TwoSlopeNorm as _TSN
sm  = plt.cm.ScalarMappable(cmap='RdBu_r',
                              norm=_TSN(vmin=-VMAX, vcenter=0, vmax=VMAX))
sm.set_array([])
cb  = fig.colorbar(sm, cax=cax)
cb.set_label('Group mean R\u00b2_wiped\n(blue=neg, red=pos)',
             fontsize=9, labelpad=10)
cb.set_ticks([-VMAX, -VMAX/2, 0, VMAX/2, VMAX])
cb.set_ticklabels([f'-{VMAX:.3f}', f'-{VMAX/2:.3f}', '0',
                    f'{VMAX/2:.3f}', f'{VMAX:.3f}'])
cb.ax.tick_params(labelsize=8)
cb.outline.set_linewidth(0.8)

# ── Legend ─────────────────────────────────────────────────────────────────
handles = [mpatches.Patch(facecolor='none', edgecolor=ROI_TYPE_COLOR[rt],
                           linewidth=2.5, label=ROI_TYPE_LABEL[rt])
           for rt in ROI_TYPES]
fig.legend(handles=handles, loc='lower center', bbox_to_anchor=(0.455, 0.0),
           ncol=6, fontsize=9, frameon=True, edgecolor='#ccc',
           facecolor='white', title='ROI type  (outline colour)',
           title_fontsize=9.5, handlelength=1.8, borderpad=0.8)

fig.suptitle(
    ' \u00b7  Group cortical flatmap: R\u00b2_wiped '
    '(BERT, vision-residualised)  \u00b7  N=8 subjects  \u00b7  fsaverage',
    fontsize=12, fontweight='bold', y=0.985, color='#111')

for ext_s in ['pdf','png']:
    out = os.path.join(FIGS_OUT, f'flatmap_bilateral_group.{ext_s}')
    fig.savefig(out, dpi=DPI, bbox_inches='tight', facecolor='white')
    print(f"Saved: {out}")
plt.close(fig)
print("Done.")

"""
NSD v9.1 — COMPLETE PUBLICATION FIGURE SCRIPT
==============================================
Run in a fresh Colab session (no pipeline re-run needed).

Required files (load from Drive):
    T3_group_roi_r2.csv       — group stats, all 6 wipe_keys  (T3)
    MASTER_subject_roi.csv    — per-subject ROI values, bert_Xa only (MS)

OR run in the live v9.1 session and set LOAD_FROM_CSV = False
(then T3 and MS must already be in memory as DataFrames).

Figures produced (all 300 DPI, saved as PDF + PNG):
  Fig 1  — R²_wiped heatmap: all ROIs × all 6 wipe keys (LH / RH)
  Fig 2  — R²_wiped bar chart: all ROIs, all 6 wipe keys grouped, LH / RH
  Fig 3  — Semantic independence ratio bar chart (same layout as Fig 2)
  Fig 4  — Subject-level replication: EBA/RH, lateral/LH, V1v/LH
  Fig 5  — Wipe diagnostics: R²_vis and alpha per subject

Significance scheme (fixed — see notes below):
  ***  BH-FDR t-test q < 0.001
  **   BH-FDR t-test q < 0.01
  *    sign-flip FDR q < 0.05  AND t-test FDR q < 0.05  (both passed)
  †    t-test FDR q < 0.05 only (sign-flip not reached)

NOTE on sign-flip resolution: with 2^8 = 256 permutations the minimum
achievable p_signflip = 1/256 ≈ 0.0039, so after BH-FDR correction
q_signflip can never go below ~0.027. Using q_signflip alone for ** and
*** thresholds (as in the original script) means those branches are dead
code that never fire. The fix: ** and *** use q_ttest; * requires both.
"""

# ── CONFIGURE ────────────────────────────────────────────────────────────────
LOAD_FROM_CSV = True   # True → load CSVs from paths below
                       # False → expects T3, MS DataFrames already in memory

T3_PATH = '/content/drive/MyDrive/nsd_results_v9.1/tables/T3_group_roi_r2.csv'
MS_PATH = '/content/drive/MyDrive/nsd_results_v9/tables/MASTER_subject_roi.csv'
FIGS_OUT = '/content/drive/MyDrive/nsd_results_v9.1/figures_full'

DPI     = 300
N_SUBJ  = 8   # updated from 7 → 8

# ── IMPORTS ──────────────────────────────────────────────────────────────────
import os, warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
from matplotlib.colors import TwoSlopeNorm
warnings.filterwarnings('ignore')

os.makedirs(FIGS_OUT, exist_ok=True)

# ── LOAD DATA ─────────────────────────────────────────────────────────────────
if LOAD_FROM_CSV:
    print("Loading CSVs...")
    T3 = pd.read_csv(T3_PATH)
    MS = pd.read_csv(MS_PATH)
else:
    print("Using in-memory DataFrames (T3, MS)...")
    # T3 and MS must already exist in the namespace

T3['sig']          = T3['sig'].astype(bool)
T3['sig_ttest_only'] = (T3['q_ttest'] < 0.05) & (~T3['sig'])

SUBJECTS = sorted(MS['subject'].unique())
N_SUBJ   = len(SUBJECTS)
print(f"  N subjects: {N_SUBJ}  {SUBJECTS}")
print(f"  T3: {len(T3)} rows  |  MS: {len(MS)} rows")

# ── SHARED CONSTANTS ──────────────────────────────────────────────────────────
WIPE_KEY_ORDER = ['bert_Xa', 'bert_Xb', 'gpt2_Xa', 'gpt2_Xb', 'clip_Xa', 'clip_Xb']
WIPE_LABELS    = [
    'BERT | X_vis-A', 'BERT | X_vis-B',
    'GPT-2 | X_vis-A', 'GPT-2 | X_vis-B',
    'CLIP-txt | X_vis-A', 'CLIP-txt | X_vis-B',
]
N_WK = len(WIPE_KEY_ORDER)

WKEY_COLOR = {
    'bert_Xa': '#1F77B4', 'bert_Xb': '#AEC7E8',
    'gpt2_Xa': '#D62728', 'gpt2_Xb': '#F7B6B6',
    'clip_Xa': '#2CA02C', 'clip_Xb': '#98DF8A',
}

ROI_TYPE_ORDER = ['floc-bodies', 'floc-faces', 'floc-places',
                  'floc-words',  'streams',    'prf-visualrois']
ROI_TYPE_LABEL = {
    'floc-bodies':    'Body',
    'floc-faces':     'Face',
    'floc-places':    'Place',
    'floc-words':     'Word',
    'streams':        'Streams',
    'prf-visualrois': 'Visual (null)',
}
ROI_TYPE_COLOR = {
    'floc-bodies':    '#E8843A',
    'floc-faces':     '#4CAF6F',
    'floc-places':    '#D94F3D',
    'floc-words':     '#8B5BB5',
    'streams':        '#3A7DC9',
    'prf-visualrois': '#8B6144',
}

# Stable ROI order: within group, descending mean R²_wiped across all wipe_keys
_avg = T3.groupby(['roi_name', 'roi_type'])['r2_wiped_mean'].mean().reset_index()
ROI_ORDER = []
for rt in ROI_TYPE_ORDER:
    sub = _avg[_avg['roi_type'] == rt].sort_values('r2_wiped_mean', ascending=False)
    ROI_ORDER += [(r, rt) for r in sub['roi_name']]
ROI_NAMES = [r for r, _ in ROI_ORDER]
ROI_TYPES = [t for _, t in ROI_ORDER]
N_ROI     = len(ROI_NAMES)

# Group boundary positions (computed once)
GROUP_SPANS = {}
for xi, (_, rt) in enumerate(ROI_ORDER):
    if rt not in GROUP_SPANS:
        GROUP_SPANS[rt] = [xi, xi]
    else:
        GROUP_SPANS[rt][1] = xi

# Subject colours
_subj_pal = plt.cm.tab10(np.linspace(0, 0.9, N_SUBJ))
SUBJ_COLOR = {s: _subj_pal[i] for i, s in enumerate(SUBJECTS)}

# rcParams
plt.rcParams.update({
    'font.family':       'DejaVu Sans',
    'font.size':         8,
    'axes.labelsize':    8.5,
    'axes.titlesize':    9,
    'xtick.labelsize':   7,
    'ytick.labelsize':   7.5,
    'legend.fontsize':   7,
    'axes.linewidth':    0.65,
    'xtick.major.width': 0.65,
    'ytick.major.width': 0.65,
    'xtick.major.size':  2.5,
    'ytick.major.size':  2.5,
    'axes.spines.top':   False,
    'axes.spines.right': False,
    'figure.dpi':        DPI,
    'savefig.dpi':       DPI,
    'pdf.fonttype':      42,
})

# ── HELPERS ───────────────────────────────────────────────────────────────────
def _sig_marker(q_ttest, q_signflip, sig_both):
    """
    Corrected significance marker.
    *** = BH-FDR t-test q < 0.001
    **  = BH-FDR t-test q < 0.01
    *   = sign-flip q < 0.05 AND t-test q < 0.05 (sig_both == True)
    †   = t-test q < 0.05 only
        = ns
    Sign-flip uses 2^8 = 256 permutations → min achievable q_signflip ≈ 0.027,
    so ** and *** must use q_ttest to be reachable.
    """
    if   q_ttest  < 0.001:                    return '***'
    elif q_ttest  < 0.01:                     return '**'
    elif sig_both and q_signflip < 0.05:      return '*'
    elif q_ttest  < 0.05:                     return '†'
    else:                                      return ''

def _get_t3(hemi, rname, wkey, col):
    """Safe scalar lookup into T3."""
    rows = T3[(T3['hemi'] == hemi) &
              (T3['roi_name'] == rname) &
              (T3['wipe_key'] == wkey)]
    return float(rows[col].iloc[0]) if not rows.empty else np.nan

def _get_marker(hemi, rname, wkey):
    rows = T3[(T3['hemi'] == hemi) &
              (T3['roi_name'] == rname) &
              (T3['wipe_key'] == wkey)]
    if rows.empty: return ''
    r = rows.iloc[0]
    return _sig_marker(float(r['q_ttest']), float(r['q_signflip']), bool(r['sig']))

def _draw_group_dividers(ax, orientation='horizontal', color='#aaaaaa',
                         lw=1.0, ls=':'):
    """Draw divider lines between ROI type groups."""
    prev_rt = None
    for xi, (_, rt) in enumerate(ROI_ORDER):
        if rt != prev_rt and xi > 0:
            pos = xi - 0.5
            if orientation == 'horizontal':
                ax.axhline(pos, color=color, lw=lw, ls=ls, zorder=0)
            else:
                ax.axvline(pos, color=color, lw=lw, ls=ls, zorder=0)
        prev_rt = rt

def _draw_group_labels_left(ax, y_data_coords, fontsize=6.5):
    """Type labels to the left of y-axis (for heatmaps / horizontal bar charts)."""
    for rt in ROI_TYPE_ORDER:
        if rt not in GROUP_SPANS: continue
        ys, ye = GROUP_SPANS[rt]
        mid = (ys + ye) / 2
        ax.text(-0.65, mid, ROI_TYPE_LABEL[rt],
                transform=ax.get_yaxis_transform(),
                ha='right', va='center', fontsize=fontsize,
                color=ROI_TYPE_COLOR[rt], fontweight='bold',
                style='italic', clip_on=False)

def _draw_group_labels_top(ax, y_top, y_range, fontsize=6):
    """Type labels above bars for vertical bar charts."""
    for rt in ROI_TYPE_ORDER:
        if rt not in GROUP_SPANS: continue
        xs, xe = GROUP_SPANS[rt]
        mid = (xs + xe) / 2
        ax.text(mid, y_top + y_range * 0.01, ROI_TYPE_LABEL[rt],
                ha='center', va='bottom', fontsize=fontsize,
                color=ROI_TYPE_COLOR[rt], fontweight='bold',
                style='italic', clip_on=False)

def _savefig(fig, stem):
    pdf = os.path.join(FIGS_OUT, f'{stem}.pdf')
    png = os.path.join(FIGS_OUT, f'{stem}.png')
    fig.savefig(pdf, dpi=DPI, bbox_inches='tight', format='pdf')
    fig.savefig(png, dpi=DPI, bbox_inches='tight')
    plt.close(fig)
    print(f"  Saved: {stem}.pdf / .png")

SIG_LEGEND = (
    '*** $t$-test FDR $q<0.001$   '
    '** $t$-test FDR $q<0.01$   '
    '* sign-flip + $t$-test FDR $q<0.05$   '
    '† $t$-test FDR $q<0.05$ only'
)

rng = np.random.RandomState(42)

# ══════════════════════════════════════════════════════════════════════════════
# FIG 1 — R²_wiped HEATMAP  (all ROIs × 6 wipe keys, LH / RH)
# ══════════════════════════════════════════════════════════════════════════════
print("\n── Fig 1: Heatmap ──")

def _build_val_matrix(hemi):
    mat = np.full((N_ROI, N_WK), np.nan)
    for ri, rname in enumerate(ROI_NAMES):
        for ci, wk in enumerate(WIPE_KEY_ORDER):
            mat[ri, ci] = _get_t3(hemi, rname, wk, 'r2_wiped_mean')
    return mat

def _build_marker_matrix(hemi):
    mat = np.empty((N_ROI, N_WK), dtype=object)
    mat[:] = ''
    for ri, rname in enumerate(ROI_NAMES):
        for ci, wk in enumerate(WIPE_KEY_ORDER):
            mat[ri, ci] = _get_marker(hemi, rname, wk)
    return mat

CELL_H = 0.30
CELL_W = 0.72
FIG1_W = CELL_W * N_WK * 2 + 5.5
FIG1_H = CELL_H * N_ROI + 3.5

fig1 = plt.figure(figsize=(FIG1_W, FIG1_H))
gs1  = gridspec.GridSpec(1, 3, figure=fig1,
                         left=0.15, right=0.96,
                         top=0.90, bottom=0.15,
                         wspace=0.5,
                         width_ratios=[N_WK, N_WK, 0.3])
ax1_LH = fig1.add_subplot(gs1[0])
ax1_RH = fig1.add_subplot(gs1[1])
ax1_cb = fig1.add_subplot(gs1[2])

val_LH = _build_val_matrix('LH')
val_RH = _build_val_matrix('RH')
mkr_LH = _build_marker_matrix('LH')
mkr_RH = _build_marker_matrix('RH')

# Shared symmetric colour scale
vmax = np.nanmax([np.nanmax(np.abs(val_LH)), np.nanmax(np.abs(val_RH))])
vmax = np.ceil(vmax * 1000) / 1000
norm1 = TwoSlopeNorm(vmin=-vmax, vcenter=0, vmax=vmax)

def _draw_heatmap(ax, val, mkr, hemi, show_yticks=True):
    im = ax.imshow(val, aspect='auto', cmap='RdBu_r',
                   norm=norm1, interpolation='nearest', origin='upper')

    # White grid
    for x in np.arange(-0.5, N_WK):
        ax.axvline(x, color='white', lw=0.4, zorder=3)
    for y in np.arange(-0.5, N_ROI):
        ax.axhline(y, color='white', lw=0.4, zorder=3)

    # Cell annotations
    for ri in range(N_ROI):
        for ci in range(N_WK):
            v = val[ri, ci]
            if np.isnan(v): continue
            txt_col = 'white' if abs(v) > vmax * 0.58 else '#222222'
            ax.text(ci, ri, f'{v:.4f}',
                    ha='center', va='center',
                    fontsize=4.6, color=txt_col, zorder=4)
            mk = mkr[ri, ci]
            if mk:
                ax.text(ci + 0.33, ri - 0.30, mk,
                        ha='center', va='center',
                        fontsize=5.0, color='#111111',
                        fontweight='bold', zorder=5)

    # Group boundary lines
    prev_rt = None
    for yi, (_, rt) in enumerate(ROI_ORDER):
        if rt != prev_rt and yi > 0:
            ax.axhline(yi - 0.5, color='#777777', lw=1.1, zorder=4)
        prev_rt = rt

    ax.set_xticks(np.arange(N_WK))
    ax.set_xticklabels(WIPE_LABELS, rotation=42, ha='right',
                       fontsize=6.5, rotation_mode='anchor')
    ax.tick_params(bottom=False, left=False)

    if show_yticks:
        ax.set_yticks(np.arange(N_ROI))
        ax.set_yticklabels(ROI_NAMES, fontsize=6.6)
        _draw_group_labels_left(ax, None, fontsize=6.5)
    else:
        ax.set_yticks([])

    # Right-side group labels for RH panel
    if not show_yticks:
        for rt in ROI_TYPE_ORDER:
            if rt not in GROUP_SPANS: continue
            ys, ye = GROUP_SPANS[rt]
            mid = (ys + ye) / 2
            ax.text(N_WK - 0.3, mid, ROI_TYPE_LABEL[rt],
                    transform=ax.get_yaxis_transform(),
                    ha='left', va='center', fontsize=6.5,
                    color=ROI_TYPE_COLOR[rt], fontweight='bold',
                    style='italic', clip_on=False)

    ax.set_title(f'{hemi}  —  $R^2_{{\\mathrm{{wiped}}}}$ (group mean)',
                 fontsize=8.5, pad=5, fontweight='semibold')
    ax.set_xlim(-0.5, N_WK - 0.5)
    ax.set_ylim(N_ROI - 0.5, -0.5)
    return im

im1 = _draw_heatmap(ax1_LH, val_LH, mkr_LH, 'LH', show_yticks=True)
_draw_heatmap(ax1_RH, val_RH, mkr_RH, 'RH', show_yticks=False)

cb1 = fig1.colorbar(im1, cax=ax1_cb, orientation='vertical')
cb1.set_label('$R^2_{\\mathrm{wiped}}$', fontsize=8, labelpad=3)
cb1.ax.tick_params(labelsize=7)
cb1.outline.set_linewidth(0.5)
tick_v = np.linspace(-vmax, vmax, 7)
cb1.set_ticks(tick_v)
cb1.set_ticklabels([f'{v:.3f}' for v in tick_v])

fig1.suptitle(
    f'$R^2_{{\\mathrm{{wiped}}}}$ heatmap: all ROIs × all 6 wipe keys  ($N={N_SUBJ}$)\n'
    + SIG_LEGEND,
    fontsize=9, y=1.005)

_savefig(fig1, 'fig1_heatmap_roi_x_wipekey')

# ══════════════════════════════════════════════════════════════════════════════
# FIG 2 — R²_wiped BAR CHART  (all ROIs, 6 grouped bars, LH / RH)
# ══════════════════════════════════════════════════════════════════════════════
print("── Fig 2: R²_wiped bar chart ──")

BAR_W2 = 0.12
xs2    = np.arange(N_ROI)

fig2, axes2 = plt.subplots(1, 2, figsize=(26, 7.5), sharey=False)
fig2.suptitle(
    f'$R^2_{{\\mathrm{{wiped}}}}$ per ROI — all 6 wipe keys  ($N={N_SUBJ}$)\n'
    + SIG_LEGEND,
    fontsize=9, y=1.01)

for ax, hemi in zip(axes2, ['LH', 'RH']):
    all_vals = []
    for wi, wk in enumerate(WIPE_KEY_ORDER):
        offsets = xs2 + (wi - N_WK / 2 + 0.5) * BAR_W2
        means, sems, markers = [], [], []
        for rname in ROI_NAMES:
            m  = _get_t3(hemi, rname, wk, 'r2_wiped_mean')
            s  = _get_t3(hemi, rname, wk, 'r2_wiped_sem')
            mk = _get_marker(hemi, rname, wk)
            means.append(m); sems.append(s if not np.isnan(s) else 0)
            markers.append(mk)
        means = np.array(means); sems = np.array(sems)
        all_vals.extend(means[~np.isnan(means)])

        valid = ~np.isnan(means)
        ax.bar(offsets[valid], means[valid], width=BAR_W2,
               color=WKEY_COLOR[wk], alpha=0.85,
               label=WIPE_LABELS[wi], edgecolor='white',
               linewidth=0.3, zorder=2)
        ax.errorbar(offsets[valid], means[valid], yerr=sems[valid],
                    fmt='none', color='#1a1a1a',
                    capsize=1.2, linewidth=0.55, capthick=0.55, zorder=3)

        # Sig markers
        for xi, mk in enumerate(markers):
            if mk and not np.isnan(means[xi]):
                yoff = means[xi] + sems[xi] + abs(np.nanstd(all_vals) * 0.05)
                ax.text(offsets[xi], yoff, mk,
                        ha='center', va='bottom',
                        fontsize=5.5, color='#111', fontweight='bold', zorder=5)

    ax.axhline(0, color='#555', lw=0.6, ls='--', zorder=1)
    ax.set_xticks(xs2)
    ax.set_xticklabels(ROI_NAMES, rotation=52, ha='right',
                       fontsize=6.5, rotation_mode='anchor')
    ax.set_title(f'{"Left hemisphere" if hemi=="LH" else "Right hemisphere"}',
                 fontsize=9, pad=4, fontweight='semibold')
    ax.set_ylabel('$R^2_{\\mathrm{wiped}}$')

    # Group dividers + labels
    _draw_group_dividers(ax, orientation='vertical', color='#cccccc', lw=0.6)
    ylim = ax.get_ylim()
    y_range = ylim[1] - ylim[0]
    ax.set_ylim(ylim[0], ylim[1] + y_range * 0.14)
    ylim = ax.get_ylim()
    _draw_group_labels_top(ax, ylim[1] - (ylim[1]-ylim[0])*0.04,
                           ylim[1]-ylim[0], fontsize=6)

axes2[1].legend(loc='upper right', fontsize=6.8, ncol=2,
                framealpha=0.92, edgecolor='#cccccc',
                handlelength=1.1, handletextpad=0.4)
plt.tight_layout()
_savefig(fig2, 'fig2_r2wiped_bars')

# ══════════════════════════════════════════════════════════════════════════════
# FIG 3 — SEMANTIC INDEPENDENCE RATIO  (same layout as Fig 2)
# ══════════════════════════════════════════════════════════════════════════════
print("── Fig 3: Ratio bar chart ──")

fig3, axes3 = plt.subplots(1, 2, figsize=(26, 7.5), sharey=False)
fig3.suptitle(
    f'Semantic independence ratio ($R^2_{{\\mathrm{{wiped}}}}\\,/\\,R^2_{{\\mathrm{{raw}}}}$)'
    f' per ROI — all 6 wipe keys  ($N={N_SUBJ}$)\n' + SIG_LEGEND,
    fontsize=9, y=1.01)

for ax, hemi in zip(axes3, ['LH', 'RH']):
    all_vals = []
    for wi, wk in enumerate(WIPE_KEY_ORDER):
        offsets = xs2 + (wi - N_WK / 2 + 0.5) * BAR_W2
        means, sems, markers = [], [], []
        for rname in ROI_NAMES:
            m  = _get_t3(hemi, rname, wk, 'ratio_mean')
            s  = _get_t3(hemi, rname, wk, 'ratio_sem')
            mk = _get_marker(hemi, rname, wk)
            means.append(m); sems.append(abs(s) if not np.isnan(s) else 0)
            markers.append(mk)
        means = np.array(means); sems = np.array(sems)
        all_vals.extend(means[~np.isnan(means)])

        valid = ~np.isnan(means)
        ax.bar(offsets[valid], means[valid], width=BAR_W2,
               color=WKEY_COLOR[wk], alpha=0.85,
               label=WIPE_LABELS[wi], edgecolor='white',
               linewidth=0.3, zorder=2)
        ax.errorbar(offsets[valid], means[valid], yerr=sems[valid],
                    fmt='none', color='#1a1a1a',
                    capsize=1.2, linewidth=0.55, capthick=0.55, zorder=3)

        for xi, mk in enumerate(markers):
            if mk and not np.isnan(means[xi]):
                yoff = means[xi] + sems[xi] + abs(np.nanstd(all_vals + [0]) * 0.05)
                ax.text(offsets[xi], yoff, mk,
                        ha='center', va='bottom',
                        fontsize=5.5, color='#111', fontweight='bold', zorder=5)

    ax.axhline(0, color='#555', lw=0.6, ls='--', zorder=1)
    ax.set_xticks(xs2)
    ax.set_xticklabels(ROI_NAMES, rotation=52, ha='right',
                       fontsize=6.5, rotation_mode='anchor')
    ax.set_title(f'{"Left hemisphere" if hemi=="LH" else "Right hemisphere"}',
                 fontsize=9, pad=4, fontweight='semibold')
    ax.set_ylabel('$R^2_{\\mathrm{wiped}}\\,/\\,R^2_{\\mathrm{raw}}$')

    _draw_group_dividers(ax, orientation='vertical', color='#cccccc', lw=0.6)
    ylim = ax.get_ylim()
    y_range = ylim[1] - ylim[0]
    ax.set_ylim(ylim[0], ylim[1] + y_range * 0.14)
    ylim = ax.get_ylim()
    _draw_group_labels_top(ax, ylim[1] - (ylim[1]-ylim[0])*0.04,
                           ylim[1]-ylim[0], fontsize=6)

axes3[1].legend(loc='upper right', fontsize=6.8, ncol=2,
                framealpha=0.92, edgecolor='#cccccc',
                handlelength=1.1, handletextpad=0.4)
plt.tight_layout()
_savefig(fig3, 'fig3_ratio_bars')

# ══════════════════════════════════════════════════════════════════════════════
# FIG 4 — SUBJECT-LEVEL REPLICATION  (EBA/RH, lateral/LH, V1v/LH)
# Uses MS (MASTER_subject_roi) — bert_Xa only
# ══════════════════════════════════════════════════════════════════════════════
print("── Fig 4: Subject replication ──")

KEY_ROIS = [
    ('EBA',     'RH', 'Body-selective\n(EBA, RH)'),
    ('lateral', 'LH', 'Lateral stream\n(LH)'),
    ('V1v',     'LH', 'Early visual\n(V1v, LH) — null'),
]
BAR_COLS = {'EBA': '#5BAD92', 'lateral': '#5BAD92', 'V1v': '#C06070'}

fig4, ax4 = plt.subplots(figsize=(7.0, 6.8))
fig4.subplots_adjust(left=0.16, right=0.97, top=0.88, bottom=0.18)

xs4 = np.arange(len(KEY_ROIS))

# Group means from T3 (bert_Xa)
grp_means4, grp_sems4 = [], []
for rname, hemi, _ in KEY_ROIS:
    grp_means4.append(_get_t3(hemi, rname, 'bert_Xa', 'ratio_mean'))
    grp_sems4.append(_get_t3(hemi, rname, 'bert_Xa', 'ratio_sem'))

ax4.bar(xs4, grp_means4,
        width=0.52,
        color=[BAR_COLS[r] for r, _, _ in KEY_ROIS],
        alpha=0.65, edgecolor='none', zorder=2)
ax4.errorbar(xs4, grp_means4, yerr=grp_sems4,
             fmt='none', color='#111',
             capsize=5, linewidth=1.2, capthick=1.2, zorder=5)

# Subject dots + connecting lines
subj_xy = {sid: [] for sid in SUBJECTS}
for xi, (rname, hemi, _) in enumerate(KEY_ROIS):
    col_data = MS[(MS['roi_name'] == rname) &
                  (MS['hemi'] == hemi)].set_index('subject')['ratio']
    for sid in SUBJECTS:
        if sid not in col_data.index: continue
        y   = float(col_data[sid])
        jit = rng.uniform(-0.07, 0.07)
        ax4.scatter(xi + jit, y, s=52,
                    color=SUBJ_COLOR[sid], zorder=6,
                    linewidths=0.6, edgecolors='white', clip_on=False)
        subj_xy[sid].append((xi, y))

for sid in SUBJECTS:
    pts = subj_xy[sid]
    if len(pts) < 2: continue
    ax4.plot([p[0] for p in pts], [p[1] for p in pts],
             color=SUBJ_COLOR[sid], lw=0.9, alpha=0.5,
             zorder=4, solid_capstyle='round')

# Significance markers
all_y4 = []
for rname, hemi, _ in KEY_ROIS:
    all_y4.extend(MS[(MS['roi_name']==rname)&(MS['hemi']==hemi)]['ratio'].values)
y4_lo, y4_hi = min(all_y4), max(all_y4)
y4_pad = (y4_hi - y4_lo) * 0.12
ax4.set_ylim(y4_lo - y4_pad, y4_hi + y4_pad * 2.8)
ylim4 = ax4.get_ylim()
y4_range = ylim4[1] - ylim4[0]

for xi, (rname, hemi, _) in enumerate(KEY_ROIS):
    mk = _get_marker(hemi, rname, 'bert_Xa')
    if mk:
        se = abs(grp_sems4[xi])
        ax4.text(xi, grp_means4[xi] + se + y4_range * 0.022, mk,
                 ha='center', va='bottom',
                 fontsize=9, color='#111', fontweight='bold', zorder=7)

ax4.axhline(0, color='#444', lw=0.9, ls='--', zorder=1, alpha=0.7)
ax4.set_xticks(xs4)
ax4.set_xticklabels([lbl for _, _, lbl in KEY_ROIS],
                    fontsize=9, ha='center', multialignment='center')
ax4.set_ylabel(
    'Semantic independence ratio  '
    '($R^2_{\\mathrm{wiped}}\\,/\\,R^2_{\\mathrm{raw}}$)',
    fontsize=9, labelpad=6)
ax4.set_xlim(-0.55, len(KEY_ROIS) - 0.45)

leg4 = [Line2D([0],[0], marker='o', color=SUBJ_COLOR[s], ms=6,
               lw=0.8, markeredgecolor='white',
               markeredgewidth=0.5, label=s)
        for s in SUBJECTS]
ax4.legend(handles=leg4, loc='upper right', ncol=2,
           fontsize=7.5, frameon=True,
           framealpha=0.92, edgecolor='#cccccc',
           handlelength=1.0, handletextpad=0.4,
           labelspacing=0.35, borderpad=0.5).get_frame().set_linewidth(0.5)

fig4.text(0.5, 0.955,
          f'Subject-level replication  ($N={N_SUBJ}$)',
          ha='center', va='top', fontsize=10.5, fontweight='bold')
fig4.text(0.5, 0.928,
          'Bars = group mean ± SEM   •  = individual subjects  (BERT | X$_{\\mathrm{vis}}$-A)',
          ha='center', va='top', fontsize=8.5, color='#333')

_savefig(fig4, 'fig4_subject_replication')

# ══════════════════════════════════════════════════════════════════════════════
# FIG 5 — WIPE DIAGNOSTICS  (R²_vis and alpha per subject, bert_Xa)
# ══════════════════════════════════════════════════════════════════════════════
print("── Fig 5: Wipe diagnostics ──")

fig5, axes5 = plt.subplots(1, 2, figsize=(12, 4.5))
fig5.suptitle(
    f'Wipe diagnostics — visual→BERT regression quality  ($N={N_SUBJ}$, BERT | X$_{{\\mathrm{{vis}}}}$-A)',
    fontsize=10, fontweight='bold')

DIAG_ROIS  = ROI_NAMES  # all 28
xs5 = np.arange(len(DIAG_ROIS))
bw5 = 0.8 / N_SUBJ

for sid_i, sid in enumerate(SUBJECTS):
    df_s = MS[MS['subject'] == sid]
    for ax, col, ylabel, log_y in [
        (axes5[0], 'r2_vis_bert', '$R^2_{\\mathrm{vis}}$ (visual → BERT, train)', False),
        (axes5[1], 'alpha_wipe',  'RidgeCV $\\alpha$ (wipe)',                      True),
    ]:
        vals = []
        for rname in DIAG_ROIS:
            row = df_s[df_s['roi_name'] == rname]
            vals.append(float(row[col].iloc[0]) if not row.empty else np.nan)
        offset = xs5 + (sid_i - N_SUBJ / 2 + 0.5) * bw5
        valid  = ~np.isnan(np.array(vals))
        ax.bar(offset[valid], np.array(vals)[valid], width=bw5,
               color=SUBJ_COLOR[sid], alpha=0.8,
               label=sid, edgecolor='white', linewidth=0.2, zorder=2)

for ax, col, ylabel, log_y in [
    (axes5[0], 'r2_vis_bert', '$R^2_{\\mathrm{vis}}$ (visual → BERT)', False),
    (axes5[1], 'alpha_wipe',  'RidgeCV $\\alpha$',                     True),
]:
    if log_y: ax.set_yscale('log')
    ax.set_xticks(xs5)
    ax.set_xticklabels(DIAG_ROIS, rotation=55, ha='right',
                       fontsize=6, rotation_mode='anchor')
    ax.set_ylabel(ylabel, fontsize=8)
    _draw_group_dividers(ax, orientation='vertical', color='#cccccc', lw=0.5)

axes5[1].legend(loc='upper right', fontsize=6.5, ncol=2,
                framealpha=0.9, edgecolor='#cccccc',
                handlelength=0.9, handletextpad=0.3)
plt.tight_layout()
_savefig(fig5, 'fig5_wipe_diagnostics')

# ══════════════════════════════════════════════════════════════════════════════
print(f"\nAll figures saved to: {FIGS_OUT}")
print("Files: fig1_heatmap_roi_x_wipekey, fig2_r2wiped_bars, fig3_ratio_bars,")
print("       fig4_subject_replication, fig5_wipe_diagnostics")
print("Each as both .pdf (vector) and .png (300 DPI raster)")